### ISSUE TITLE
AEMaaCS SDK and archetype compatibility

### ISSUE THREAD

**Issue by krystian-panek-vmltech** [adobe/aem-project-archetype#1043]
According to "Cloud-Ready" mentioned here: https://experienceleague.adobe.com/docs/experience-manager-core-components/using/developing/archetype/overview.html I see "continual" at the system requirements...

Is it somewhere stated which exact archetype version is compatible with which SDK version? I was expecting that the recent SDK would be consistent with the current archetype but unfortunately seems that not.

I just started playing with the recent AEMaaCS SDK - aem-sdk-2023.1.10912 and generating project from archetype 40 recently released however I spotted that the dispatcher validator complains that immutable dispatcher config files generated from archetype are changed ;/

![image](https://user-images.githubusercontent.com/81212505/217945481-3d06155d-e6bd-4393-b8c5-1de9c6b5b2ec.png)

![image](https://user-images.githubusercontent.com/81212505/217946155-87262232-6831-444f-a343-b36abe8f2812.png)

Archetype needs to be aligned, I suppose?

Greetings, Krystian

**Comment by krystiannowak** [comment]
There is a mvn shell script located in bin directory of Dispatcher SDK tooling which updates immutable files in your local pointed directory to the one from the SDK and patches your pom.xml to match their checksums.

**Comment by krystian-panek-vmltech** [comment]
ok, so from time to time this script need to be launched to keep things synchronised. fair enough. thanks for clarifying this

**Comment by krystiannowak** [comment]
Resolved with https://github.com/adobe/aem-project-archetype/pull/1045 from Dispatcher SDK tooling version 2.0.166 - to be available in Archetype 41 (next to be released)
