### ISSUE TITLE
ui.tests (both cypress and wdio) throw errors with "install" or "deploy" phases

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#1172]
The modules at https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/ui.tests.cypress/pom.xml and https://github.com/adobe/aem-project-archetype/blob/develop/src/main/archetype/ui.tests.wdio/pom.xml have default packaging (=`jar`) but only build a secondary/attached artifact with the `maven-archiver-plugin`. That leads to issues with more recent versions of `maven-install-plugin` and `maven-deploy-plugin` (https://issues.apache.org/jira/browse/MINSTALL-118) failing the build with

```
The packaging plugin for this project did not assign a main file to the project but it has attachments. Change packaging to 'pom'
```

The packaging should be `pom` and also the `tar.gz` should only be conditionally created (in a profile only active in Cloud Manager), as for local execution with docker it is not used at all.

**Comment by buuhuu** [comment]
@dulvac something you could look into?

**Comment by dulvac** [comment]
> should only be conditionally created (in a profile only active in Cloud Manager)

@kwin, unfortunately I can't change the behaviour, but I will change the packaging
