### ISSUE TITLE
Add additional open source files

### ISSUE THREAD

**Issue by macdonst** [adobe/aem-project-archetype#157]
We'll also need a few tweaks to the repo please add the following:

1. We need contribution guidelines in place. We recommend adding a `CONTRIBUTING.md` to your repo which, at a minimum, makes explicit that external contributors sign [Adobe's CLA](http://opensource.adobe.com/cla.html). We have a [sample `CONTRIBUTING.md` file you can copy or steal from in our starter repo](https://github.com/adobe/starter-repo/blob/master/.github/CONTRIBUTING.md).
1. Please consider adding a code of conduct and issue / pull request templates. Once more: [the starter repo](https://github.com/adobe/starter-repo/) has sample files you can use for this.

As well:

1. We recently rolled out a GitHub App to a growing list of repos on github.com/adobe that we call the [CLA Bot](https://github.com/adobe/cla-bot). The app is pretty simple: whenever someone opens a pull request to a repo the bot is enabled for, we check whether the person who opened the pull request is either a) a member of the org, denoting they are an Adobe employee, or b) have signed the [Adobe CLA](http://opensource.adobe.com/cla.html). The result of this check is rendered on the pull request as a GitHub Check. [Here](https://github.com/adobe/cla-bot-playground/pull/40/checks)'s an example of a pull request by a non-employee who has not signed the CLA, and [here](https://github.com/adobe/spectrum-css/pull/70/checks)'s an example of a PR by someone who has signed the CLA - just so you get an idea of how the bot works and looks like. If this interests you, we can enable the bot for your repo. The bot is still fairly new - about a month old - so we haven't enabled it yet for all repos and are still testing it out, but we aim to roll it out for ALL repos at some point early this year.

Let me know if you have any questions!

(CQ-4264192)

**Comment by vladbailescu** [comment]
@macdonst, +1 for the CLA Bot. Can we also have it added to https://github.com/adobe/aem-core-wcm-components ?

**Comment by macdonst** [comment]
@vladbailescu I've enabled the CLA bot for this repo and aem-core-wcm-components.
