### ISSUE TITLE
Running mvn test fails

### ISSUE THREAD

**Issue by rombert** [adobe/aem-project-archetype#161]
### Expected Behaviour

`mvn test` builds the project succesfully.

### Actual Behaviour

```
[ERROR] Failed to execute goal org.apache.jackrabbit:filevault-package-maven-plugin:1.0.1:analyze-classes (default-analyze-classes) on project test.ui.apps: Error while analysing imports: /home/robert/sources/test/core/target/classes (Is a directory) -> [Help 1]
```

### Reproduce Scenario (including but not limited to)

Run `mvn test`

**Comment by viveksr2** [comment]
I was facing the same issue, trying with the user having proper permissions resolved the issue for me.
