### ISSUE TITLE
[RTC] Include /etc/map url mappings in archetype

### ISSUE THREAD

**Issue by shsteimer** [adobe/aem-project-archetype#163]
**User Story:**
 
As an AEM admin/developer, I want url mappings from long urls to short urls to be provided so that I can easily provide SEO friendly URLS

**Acceptance Criteria:**
 - /content/{siteName} is hidden from the urls when written in links by AEM components
 - AEM project archetype auto-generates /etc/map rules based on archetype inputs
 - /etc/map rules can be customized by project team during development as needed eg. to make the mappings environment specific.

**Comment by joerghoh** [comment]
Addition: The mappings should only be applied on publish.

**Comment by bpauli** [comment]
CQ-4266078

**Comment by gabrielwalt** [comment]
Hi @shsteimer, this makes sense!
This will probably require the addition of a domain name variable to the archetype, so that the mapping can be setup accordingly.

**Comment by bstopp** [comment]
I think we should support rewrite rules as part of a Dispatcher definition. `/etc` is known to be deprecated and until there is a new location, IMO, the best place for managing these is in the dispatcher.

**Comment by gabrielwalt** [comment]
We have basic url rewrite rules in place. Closing this as the remaining `/etc` rules is not something we want to add anymore, because of it being deprecated.
