### ISSUE TITLE
How to build project with AEM6.4?

### ISSUE THREAD

**Issue by EasonPai** [adobe/aem-project-archetype#168]
### Expected Behaviour
I built project with

> mvn archetype:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=17 -DoptionAemVersion=6.4

### Actual Behaviour
I get project with dependency

>             
>             <dependency>
>                 <groupId>com.adobe.aem</groupId>
>                 <artifactId>uber-jar</artifactId>
>                 <version>6.3.0</version>
>                 <classifier>apis</classifier>
>                 <scope>provided</scope>
>             </dependency>

#### Platform and Version
AEM 6.4
Apache Maven 3.6.0 
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"

**Comment by bpauli** [comment]
@EasonPai #159 will be part of the next version 18 auf the archetype. If you want to use this feature already now you have to build this project locally and add use the 18-SNAPSHOT version from your local repo.
But version 18 should be also public available in the next few days.
