### ISSUE TITLE
Use bnd-maven-plugin instead of maven-bundle-plugin

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#172]
The `bnd-maven-plugin` (https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin) and the `bnd-baseline-maven-plugin` (https://github.com/bndtools/bnd/tree/master/maven/bnd-baseline-maven-plugin) are nowadays better maintained than the `maven-bundle-plugin`and are always released along with the underlying `bnd` (which is also the foundation for `maven-bundle-plugin`). Also the former is designed much more in line with the Maven build life cycle (further information in https://blogs.paremus.com/2015/03/announcing-the-bnd-maven-plugin/).
Apache Sling tries to move away from `maven-bundle-plugin` (http://apache-sling.73963.n3.nabble.com/hackathon-bnd-maven-plugin-vs-maven-bundle-plugin-td4086273.html) as well.

There are a few important differences to the `maven-bundle-plugin` to consider while migrating:

1. Packages are no longer automatically exported (but there is a handy directive for exporting all versioned packages)
1. In-POM instructions are supported but need to be enclosed in a `CDATA` section

This was also mentioned in https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1560#issuecomment-456720819.

**Comment by bmickunas** [comment]
Can anyone speak to a solution for `org.apache.sling.testing.mock.osgi.NoScrMetadataException: No OSGi SCR metadata found for class` when running unit tests since this change was implemented? The previous use of the maven-bundle-plugin seemed to have a solution for generating the SCR metadata when the unit tests were executed
