### ISSUE TITLE
[RTC] Core Component - Default Policy & Style

### ISSUE THREAD

**Issue by ynakagawa** [adobe/aem-project-archetype#173]
**User Story:**
As a Front End Developer, I would like to be able quickly alter or enhance the visual style of a Core Component via the style system by modifying a pre-built style.

**Acceptance Criteria:**
1  FED should be able to navigate to an existing template & open the policy editor to view a default layout & display style.
2 FED should be able to navigate to a pre-defined location and easily find the css file for the teaser component & modify the appropriate CSS defaults for the following:

Layout:  Banner (height: 150), Hero (height:450)
Display:  Border (on|off)

3. FED should have the following Core Components already pre-configured with a policy & default style options:
a. Carousel
b. Content Fragment
c. List
d. Separator
e. Social Sharing
f. Tabs
g. Teaser
h. Text
i. Title

**Comment by gabrielwalt** [comment]
To me, this RTC is describing the needs for a component theme with some style presets.

**Comment by ynakagawa** [comment]
Can you please elaborate what that means?  I do not think of a theme in a optional add on sense.  If a core component has a default set of rendering, it should be included as a base style.
