### ISSUE TITLE
[RTC] Header/Footer Setup

### ISSUE THREAD

**Issue by ynakagawa** [adobe/aem-project-archetype#174]
User Story:
As a Front End Developer, I would like to be able quickly alter or enhance the visual style my header/footer via a combination of experience fragment, style system.

Acceptance Criteria:
1. The header/footer should be consistent across a website
2. The header/footer should work with MSM based live/language copies
3. The header/footer should allow for external JS libraries (ie.  munchkin.js for marketo)
4. The header/footer should be editable by a FED, but locked to content authors.
5. The header/footer should allow for customer specific HTML fragments (ie.  copy/paste HTML fragment source)
6. The header/footer should work within AEM's responsive grid

**Comment by gabrielwalt** [comment]
+1 to the concept of having template Header and Footer setup via Experience Fragments in the Archetype.

Some notes on the acceptance criteria:
3. Loading of JS libraries can and should be done via Client Libraries (code).
5. This would require a dedicated HTML component and cannot be done alone within the Header and Footer setup in the Archetype.

**Comment by ynakagawa** [comment]
removed requirement for "copy/paste HTML fragment source"

**Comment by godanny86** [comment]
I'm wondering if this development work should delay until https://github.com/adobe/aem-core-wcm-components/issues/558 on the Core Components project is implemented?
