### ISSUE TITLE
[RTC] Base Proxy Components

### ISSUE THREAD

**Issue by kmurugulla** [adobe/aem-project-archetype#175]
**User Story**

As a AEM Archetype user, I should be able to create a project which has all the Core content components available through proxy components.
All these proxy components should be listed under component group as specified in componentGroupName parameter.

Note: Following should be handled under page templates automation.
Pre-configure the policy to allow the usage of these components on the content page.

Open for discussion:

Should we provide a mechanism to pick the list of core components for which a proxy component should get created? This way we will be also able to provide a custom name for each of the proxy core components. Example:

core/wcm/components/title/v1/title=Site Title
core/wcm/components/image/v1/image= Picture

**Comment by gabrielwalt** [comment]
Hi @kmurugulla, I think that the creation of proxy components that are listed under the specified component group is already the case. Here's for example the proxy title component that gets generated, and note the `{componentGroupName}` variable:
https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/title/.content.xml#L6

Further cherry picking and renaming of components would be nice, but it would require a more sophisticated system and UI than the Archetype currently offers. I'd keep that idea for later as we have more urgent missing features in the archetype.

If I didn't properly understand what was meant with this RTC, then please clarify, else I'll close it within the next couple of days.

**Comment by gabrielwalt** [comment]
I'm closing this as the Archetype already generates the proxy components.
If there's a need to rename the components with archetype variables, we can always create a specific issue just for that.
