### ISSUE TITLE
[RTC] User Groups and Permissions

### ISSUE THREAD

**Issue by kmurugulla** [adobe/aem-project-archetype#178]
**User Story**
As an AEM Archetype user, I would like to set up an initial set of user groups and permissions and include them into the package

**Acceptance Criteria**
As an AEM Archtype user, I am able  to
a)Name and Create one Super User Group during project creation - Super Users are  AEM Administrators and get access to WebConsole a.k.a Felix Console
b)Name and Create a Content Administrator group - who can manage editable templates , component Policies and Styles
c)Enter the number of Content Approver groups and name each of them for creation - Content Approvers gets all permissions of Content Authors + Ability to approve and publish pages
d)Enter the number of Content Author groups and name each of them for creation - Content Authors get permissions to create, update and delete pages . They will also have read access to all digital assets
Enter the number of Digital Asset Managers and name them for creation - Digital Asset Managers will be able to upload assets, edit metadata and delete the assets without causing broken links on the website.

**Comment by joerghoh** [comment]
Question: Should these groups and their permissions get deployed with every deployment of the "ui-content" package or should it be a dedicated package? I would prefer the second.

**Comment by ynakagawa** [comment]
I think it should be the latter as well.  would prefer these nodes get created with mode=merge

**Comment by bstopp** [comment]
Couple of notes

> a)Name and Create one Super User Group during project creation - Super Users are AEM Administrators and get access to WebConsole a.k.a Felix Console

 If we are granting _administrator_ access - should we not use the administrators group that is OOTB?

> b)Name and Create a Content Administrator group - who can manage editable templates , component Policies and Styles

We shouldn't conflate administration with these actions - the term that the ACS UX consultants have been using is `Template Editors`. Using the term _administrator_ has certain implications which are not necessarily valid here.

> c)Enter the number of Content Approver groups and name each of them for creation - Content Approvers gets all permissions of Content Authors + Ability to approve and publish pages
d)Enter the number of Content Author groups and name each of them for creation - Content Authors get permissions to create, update and delete pages . They will also have read access to all digital assets
Enter the number of Digital Asset Managers and name them for creation - Digital Asset Managers will be able to upload assets, edit metadata and delete the assets without causing broken links on the website.

Do we need more than one group for each of these? Isn't it the minimal need to achieve the desired functionality 3 groups: `Content Author`, `Content Approver`, and `Asset Managers`, not _n_ copies of these.

> d)Enter the number of Content Author groups and name each of them for creation - Content Authors get permissions to create, update and delete pages . They will also have read access to all digital assets

Content Authors cannot delete pages if they are not permitted to publish them. There is an implicit requirement for this action, so Content Authors can only Create, Update pages and request to publish or delete, but not perform the delete action.

**Comment by gabrielwalt** [comment]
If we're adding these groups, then they need to be optional.

I am closing this for now as the core team currently can't work on it, and because there hasn't been activity for over ten months. Anybody, feel free to reopen if you're willing to contribute a parameter to the Archetype to make these groups optional.
