### ISSUE TITLE
[RTC] Page Templates

### ISSUE THREAD

**Issue by kmurugulla** [adobe/aem-project-archetype#179]
**User Story**
As AEM Archtype user , I would like to include three basic page templates based on the Editable Templates concept. 
The three templates are 
- Landing
- Article
- Information

**Acceptance Criteria**
a)As a Web Administrator, I want to be able to create variations of a page template to allow different types of components to be used by different groups of authors.

b)As a Marketer responsible for Landing Pages (secondary pages off the main nav - /home/main-nav/{landing-pages}), I want to be able to create a landing page quickly without having to ask an administrator or FED for assistance

c)As a Content Author responsible for content pages, I want to be able to create a content page quickly without having to ask an Admin for assistance

d)As a delegate to the marketing director, I want to be able to modify the home & primary nav pages

**Comment by gabrielwalt** [comment]
Closing this for now, because we plan to integrate different page templates rather via a "starter kit" content package, and because there hasn't been any activity here for over a year.
