### ISSUE TITLE
[RTC] Workflows

### ISSUE THREAD

**Issue by kmurugulla** [adobe/aem-project-archetype#180]
**User Story**
As an Archetype user, I would like to include three base workflows in the package
Make sure the following workflows are available for initiation and assignment as shown in the flow

**Acceptance Criteria**
1) Content Author sends a request to delete the content page (author -> approver -> delete action) - work flow available out of the box 
2) Content Author requests to publish the content page (author -> approver[n] -> publish) - out of the box
3) Content Approver or Author requests to modify the content page (author|approver -> author -> requestor) - new workflow to develop
4) Content Author requests Creative user to upload digital asset(s) (author -> creative -> requestor) - new workflow to develop
5) All flows sends an email and create an inbox notification to the user or group assigned

Question :
Should we consider hiding all other workflows for the customer-specific author/approver groups gets created in [RTC] 178 - https://github.com/adobe/aem-project-archetype/issues/178

**Comment by gabrielwalt** [comment]
The implementation of the new workflows to develop would make sense to be isolated in a separate package. The setup of the user groups and associated workflows should be parametrizable when executing the archetype, which can then also trigger the inclusion of that package if the groups have been setup. I'm ok with hiding the other workflows when these groups are configured.

**Comment by gabrielwalt** [comment]
closing this for now as there hasn't been activity for over 1 year.
