### ISSUE TITLE
No recently released archetype available on Adobe Public Maven repository

### ISSUE THREAD

**Issue by pun-ky** [adobe/aem-project-archetype#201]
### Expected Behaviour

Recently released archetypes are published on Adobe Public Maven Repository

### Actual Behaviour

No recently released archetypes available on Adobe Public Maven Repository

### Reproduce Scenario (including but not limited to)

https://mvnrepository.com/artifact/com.adobe.granite.archetypes/aem-project-archetype?repo=adobe-public

#### Steps to Reproduce

running command as mentioned in README.MD ends with error

```
mvn archetype:generate \
 -DarchetypeGroupId=com.adobe.granite.archetypes \
 -DarchetypeArtifactId=aem-project-archetype \
 -DarchetypeVersion=19
```

#### Logs taken while reproducing problem

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3 .0.1:generate (default-cli) on project standalone-pom: The desired archetype doe s not exist (com.adobe.granite.archetypes:aem-project-archetype:19) -> [Help 1]
```

**Comment by vladbailescu** [comment]
The archetype is published in the Adobe Public repo: https://repo.adobe.com/nexus/content/repositories/releases/com/adobe/granite/archetypes/aem-project-archetype/19/

Please refer to https://helpx.adobe.com/experience-manager/kb/SetUpTheAdobeMavenRepository.html for setting up the repository!

**Comment by pun-ky** [comment]
Hmm OK. Mislooked that. Thanks. On mvnrepository site it is looking like missing 😉
