### ISSUE TITLE
Excluding resources in ui.app project

### ISSUE THREAD

**Issue by dineshkumar-l** [adobe/aem-project-archetype#203]
Could someone help me out, how to exclude certain files under a folder in ui.app project.
In the old Archetype projects, I used to do it as shown in the below plugin. But while trying the similar kind in Archetype19, is not excluding the folder in the built zip package.

`<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				
				<configuration>
					<resources>
						<resource>
							<directory>src/main/content/jcr_root</directory>
							<excludes>
								<exclude>**/sass/**</exclude>
							</excludes>
						</resource>
					</resources>
					<includeEmptyDirs>true</includeEmptyDirs>
				</configuration>
			</plugin>`

Thanks

**Comment by kwin** [comment]
Use the plugin parameter excludes (http://jackrabbit.apache.org/filevault-package-maven-plugin/package-mojo.html#excludes).

**Comment by dineshkumar-l** [comment]
Hi Kwin,

Thanks for API documentation pointer. I could now solve my issue after understanding the POM XML properties.

**Comment by dineshkumar-l** [comment]
Hi Kwin,

Thanks for API documentation pointer. I could now solve my issue after understanding the POM XML properties.

**Comment by sujeet-singh** [comment]
Joining late but this can be achived using configuration property **[<jcrRootSourceDirectory>${project.build.outputDirectory}</jcrRootSourceDirectory>](http://jackrabbit.apache.org/filevault-package-maven-plugin/package-mojo.html#jcrRootSourceDirectory)** of filevault-package-maven-plugin.

By adding the value I mentioned above, One can use excludes of resource section.
