### ISSUE TITLE
Update the i18n dictionary from sling:MessageEntry based to JSON-file based

### ISSUE THREAD

**Issue by deenamo** [adobe/aem-project-archetype#208]
According to the [Sling documentation](https://sling.apache.org/documentation/bundles/internationalization-support-i18n.html), loading of JSON-file based dictionaries is [much faster](https://issues.apache.org/jira/browse/SLING-4543) than loading the ones based on `sling:MessageEntry`s and should be used preferably.

Please update the Archetype to generate a JSON-file based dictionary.

### Expected Behaviour
The archetype should generate a JSON-file dictionary in the following format:
```
   /apps/__appsFolderName__/i18n/
           +-- fr.json (nt:file, mix:language)
           |    +-- jcr:language = fr
           |    +-- jcr:content (nt:resource)
           |         + jcr:data
```

The `jcr:data` of the file:
```
{ 
    "&copy; {0} iZotope Site. All rights reserved.": "&copy; {0} iZotope Site. Tous droits réservés.", 
} 
```

### Actual Behaviour
The archetype generates a `sling:MessageEntry` dictionary in the following format:
```
   /apps/__appsFolderName__/i18n/
           +-- fr (nt:folder, mix:language)
           |    +-- jcr:language = fr
           |    +-- copyright (nt:folder, sling:Message)
           |    |    +-- sling:key = "&copy; {0} iZotope Site. All rights reserved."
           |    |    +-- sling:message = "&copy; {0} iZotope Site. Tous droits réservés."
```

**Comment by andreeadracea** [comment]
(CQ-4276179)
