### ISSUE TITLE
Package imports should be automatically determined during build-time

### ISSUE THREAD

**Issue by jckautzmann** [adobe/aem-project-archetype#211]
See the conversation that was started in a different pull request:
https://github.com/adobe/aem-project-archetype/pull/209/#discussion_r301188597

**Comment by bpauli** [comment]
@jckautzmann the asteristix in the line `Import-Package: javax.inject;version="0.0.0",javax.annotation;version="0.0.0",* ` does already import the dependencies automatically. Therefore I'll close this issue.
