### ISSUE TITLE
ContextHubPath is pointing to wrong location in Archetype 19

### ISSUE THREAD

**Issue by anoopkumargarg** [adobe/aem-project-archetype#213]
### Expected Behaviour
cq:contextHubPath property on root page should have to point /libs/settings/cloudsetting/legacy/contexthub
### Actual Behaviour 
cq:contextHubPath property on root page is  pointing to /etc/cloudsettings/default/contexthub

#### Steps to Reproduce
Build your project using archetype 19. 
Open en page in edit mode 
Open page properties and navigate to Personalization tab
Check ContextHub Path

#### Platform and Version
Windows, AEM 6.5
#### Sample Code that illustrates the problem
NA
#### Logs taken while reproducing problem
NA

**Comment by andreeadracea** [comment]
(CQ-4276182)
