### ISSUE TITLE
[RTC] Dispatcher Support

### ISSUE THREAD

**Issue by bstopp** [adobe/aem-project-archetype#218]
**User Story:**

As a AEM admin/developer, I want a default Dispatcher configuration generated to support Adobe Experience Cloud.

**Acceptance Criteria:**

* /content/{siteName} is hidden from the URL when written in links by AEM components
  * E.g. JCR Resource Resolver configuration of /content/{sitename}/</ 

* Rewrite rules exist to map shortened URL to repository path
  * E.g. /en.html -> /content/{siteName}/en.html

* Dispatcher security check completes without any issues.

* Standard Dispatcher virtualhost, renderers, cache, filters, invalidate rules, etc are created/applied.

**Comment by joerghoh** [comment]
H @bstopp, can you be more specific about:

* Is it for author or publish?
* With "dispatcher" do you mean the AEM dispatcher only or the role "dispatcher", which is typically performed by Apache httpd 2.4.x plus the dispatcher module?
