### ISSUE TITLE
[RTC] Cloud Configuration Support

### ISSUE THREAD

**Issue by bstopp** [adobe/aem-project-archetype#220]
User Story:

As a AEM admin/developer, I want the Cloud Configurations to be enabled on my Configuration 

Acceptance Criteria:

* The /conf/{confFolderName}/settings/cloudconfigs is created with all of the appropriate properties.
* An author can create a Launch configuration definition in the created Cloud Config folder (This is something that should work, not an action that the archetype should perform).

* [Question] If i select to create the skeleton content, this Cloud Configuration should be applied to the root of that skeleton.

**Comment by gabrielwalt** [comment]
closing this for now as there hasn't been activity for over 1 year.
