### ISSUE TITLE
Sling Models are not working if Model classes are inside subfolders.

### ISSUE THREAD

**Issue by arunpatidar02** [adobe/aem-project-archetype#221]
With Archtype 20, Maven classes are not getting resolved as type inside model's subfolders if Sling-Model-Packages: com.myapp.core.models is defined in bnd-maven-plugin  e.g. **com.myapp.core.models.sub**

````xml
<plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bnd-process</id>
                        <goals>
                            <goal>bnd-process</goal>
                        </goals>
                        <configuration>
                            <bnd><![CDATA[
Bundle-Category: MyApp
-exportcontents: ${packages;VERSIONED}
Sling-Model-Packages: com.myapp.core.models
-snapshot: ${tstamp;yyyyMMddHHmmssSSS}
Bundle-DocURL:
                                ]]></bnd>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
````

We get following error, if we use create model inside subfolder:
com.myapp.core.models.sub.HelloWorldModel cannot be resolved to a type

**Comment by arunpatidar02** [comment]
I dig more into the issue and found that the packages/sub packages apart from default packages are not getting added in Export-Package header in MANIFEST.MF file. All the new packages are getting added in Private-Package header, because of missing package-info.java file in sub/new packages.

To resolve above issue either you can create package-info.java with with version annotation or update core pom to remove VERSIONED filter from -exportcontents.

````xml
<plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bnd-process</id>
                        <goals>
                            <goal>bnd-process</goal>
                        </goals>
                        <configuration>
                            <bnd><![CDATA[
Bundle-Category: MyApp
-exportcontents: ${packages;}
Sling-Model-Packages: com.myapp.core.models
-snapshot: ${tstamp;yyyyMMddHHmmssSSS}
Bundle-DocURL:
                                ]]></bnd>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
````

**Comment by bpauli** [comment]
@arunpatidar02 Thank you for bringing this up! With the newly added bnd-maven-plugin it necessary and recommended to define a package-info.java with a proper version information in each subpackage.

**Comment by WwHG10** [comment]
I'm having a similar issue.  I have a package com.abc.models with my model interface and com.abc.models.impl with my model implementation.  The Exported Package is always displayed as com.abc.models.impl, therefore my HTL code cannot reference the Model interface.
The MANIFEST.MF shows both the com.abc.models and com.abc.models.impl but when I open the deployed bundle the onlyh Exported Package is the com.abc.models.impl.  
I have a package-info.java file at the interface level with 
package com.abc.models;
Why is the Exported Packages for my interface not working?

**Comment by bpauli** [comment]
@WwHG10, are you able to share your codebase?

**Comment by WwHG10** [comment]
> @WwHG10, are you able to share your codebase?

package ca.abc.aem.shared.components.models;

import java.util.Calendar;
import java.util.List;

import org.apache.sling.models.annotations.Model;
import org.osgi.annotation.versioning.ConsumerType;

/**
 * Defines the {@code Thirdcomponent} Sling Model used for the {@code bmdaem/shared/components/thirdcomponent} component.
 *
*/
@ConsumerType
public interface Thirdcomponent {


    /**
     * Returns a text value tooltip used somewhere in the component
     * 
     * @return String
     * 
     */
    String getAtextfield();
}
@Model(adaptables = {
    Resource.class
}, adapters = Thirdcomponent.class, resourceType = "abc/shared/components/thirdcomponent")
public class ThirdcomponentImpl implements Thirdcomponent
{
    @OSGiService
    private SlingSettingsService settings;
    @SlingObject
    private Resource currentResource;
    @SlingObject
    private ResourceResolver resourceResolver;

    @ValueMapValue(injectionStrategy = InjectionStrategy.OPTIONAL)
    private String atextfield;

   // @Override
    public String getAtextfield() {
        return atextfield;
    }


}
HTL
<sly data-sly-use.thirdcomponentModel="ca.abc.aem.shared.components.models.Thirdcomponent"
     data-sly-test.configured="${false}">
    
</sly>

<sly data-sly-use.templates="core/wcm/components/commons/v1/templates.html"
  ----
From pom.xml in the core module:
        <plugins>
            <plugin>
                <groupId>org.apache.sling</groupId>
                <artifactId>sling-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>bnd-process</id>
                        <goals>
                            <goal>bnd-process</goal>
                        </goals>
                        <configuration>
                            <bnd><![CDATA[
Bundle-Category: thirdcomponent
-exportcontents: ${packages;VERSIONED}
Sling-Model-Packages: ca.abc.aem.shared.components.models
-snapshot: ${tstamp;yyyyMMddHHmmssSSS}
Bundle-DocURL:
                                ]]></bnd>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by WwHG10** [comment]
That may not be the complete story, tried another project and the same issue is appearing.

**Comment by WwHG10** [comment]
I have finally found the issue, the bundle was using a classpath for the model which was the same as a previously deployed bundle, therefore the model was not available.
Thanks for your help and suggestions.

**Comment by dabe5651** [comment]
My issue was a with Sling-Model-Packages: com.myapp.core.models 

needed to be Sling-Model-Packages: com.myapp.core

**Comment by bartoszWesolowski** [comment]
@bpauli  hello, I am facing the same issue with the latest version of archetype. Could you please let me know where I could find this recommendation, to be honest I am not sure whether I should look for it in bnd plugin or in `org.apache.sling.bnd.models.ModelsScannerPlugin` or maybe somewhere else. I think this kind of stuff could be OOTB configured for the archetype or at least clearly docummented somewhere. Thanks :) 

> @arunpatidar02 Thank you for bringing this up! With the newly added bnd-maven-plugin it necessary and recommended to define a package-info.java with a proper version information in each subpackage.

**Comment by Jdruwe** [comment]
I am having the same issue, not sure what is going wrong.

**Comment by Jdruwe** [comment]
I've added the package-info in my sub folder and it got resolved.
