### ISSUE TITLE
Update `artifactId` default value

### ISSUE THREAD

**Issue by vikramca06** [adobe/aem-project-archetype#222]
### Expected Behaviour
1. parent module artifact name should be the same name as given while creating the project
2. appsFolderName property should be created in parent module
### Actual Behaviour
1. Parent module artifact name is appended with groupName and even folder name of parent module is also same
2. appsFolderName property was not included in properties

### Reproduce Scenario (including but not limited to)
create new maven project using archetype 20

#### Logs taken while reproducing problem

**Comment by bpauli** [comment]
@vikramca06 Thank you for the hands up!

I'm not sure if I understand correctly this request. Can you please provide some more context on this? Or even better we would highly appreciate a PR, so we can see what you would like to change. Thanks!

**Comment by richardhand** [comment]
@vikramca06 - could you also please make sure you provide a more descriptive issue title that describes the problem, the current one is a bit vague, thanks!

**Comment by vikramca06** [comment]
![image](https://user-images.githubusercontent.com/2004186/64063901-3b156b00-cbfb-11e9-9602-9dcb7903f61d.png)

artifactid should be ${appsFolderName} only. if its ${groupid}.${appsFolderName} then build is failing. please check the screenshot

**Comment by gabrielwalt** [comment]
See also #294.
