### ISSUE TITLE
Duplicate entry for biz.aQute.bnd in pom.xml

### ISSUE THREAD

**Issue by greggthomason** [adobe/aem-project-archetype#223]
### Expected Behaviour
Only one biz.aQute.bnd plugin ref
### Actual Behaviour
There are 2
### Reproduce Scenario (including but not limited to)
Create a basic project
#### Steps to Reproduce
Create a basic project
#### Platform and Version
HEAD
#### Sample Code that illustrates the problem
mvn archetype:generate  -DarchetypeGroupId=com.adobe.granite.archetypes  -DarchetypeArtifactId=aem-project-archetype  -DarchetypeVersion=20 -DoptionIncludeFrontendModule=y
#### Logs taken while reproducing problem
n/a

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-project-archetype/pull/228
