### ISSUE TITLE
no ui.frontend folder from archetype 20

### ISSUE THREAD

**Issue by HaroldPutman** [adobe/aem-project-archetype#224]
### Expected Behaviour

After running maven expected a ui.frontend folder to be created. The readme says to
"Navigate to ui.frontend in your project and run npm install." 

### Actual Behaviour

no ui.frontend folder

### Reproduce Scenario (including but not limited to)

In empty folder

#### Steps to Reproduce

```
mvn archetype:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=20
```

#### Platform and Version

```
$ mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_172, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

#### Logs taken while reproducing problem

**Comment by HaroldPutman** [comment]
Oops, found my answer by looking at #223  I missed the `-DoptionIncludeFrontendModule=y` parameter in the commandline. I see it now in the readme, but I also see how I missed it. Not sure if it makes sense to add to the archetype  readme /src/main/archetype/README.md, but I would have seen it there.

**Comment by bpauli** [comment]
Documentation enhanced in https://github.com/adobe/aem-project-archetype/pull/225
