### ISSUE TITLE
javax.annotation,version -- Cannot be resolved

### ISSUE THREAD

**Issue by kishoresirimane** [adobe/aem-project-archetype#229]
Hi, I'm working with Archetype 15 and AEM 6.4 version. When deploying the snapshot I got this error
![issue](https://user-images.githubusercontent.com/53344060/63989803-4daa7a00-caff-11e9-878a-18c948cfa7f7.PNG)

Do anyone know if I need to add some other dependency to my mvn project?

**Comment by kishoresirimane** [comment]
I tried adding javax.annotation dependency version 1.3 and 1.2 to parent POM file, still the same issue exist

**Comment by mowadigital** [comment]
+1, how do we fix the org.apache.sling.api.resource 2.11 issue shown above?

**Comment by mowadigital** [comment]
I found the fix, I put the right version on the core/pom file:

https://youtu.be/lKWHsVh1hRA

**Comment by kishoresirimane** [comment]
@mowadigital 
<Import-Package>
			javax.inject;version=0.0.0,
			javax.annotation;version=0.0.0,			
			org.apache.sling.api.resource;version="[2.10,3)"
</Import-Package>
Is this the only thing need to be added to core/pom file? or some other dependencies needed

**Comment by kishoresirimane** [comment]
Thank you so much @mowadigital 
The solution worked for me
