### ISSUE TITLE
Unnecessary linting leads to longer processing

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-project-archetype#231]
### Expected Behaviour

When the ui.frontend module is run it should only lint against files in the `src` folder. It doesn't seem like the tslint.json file is even used/referenced...

### Actual Behaviour

The ui.frontend module incorrectly lints against files in the node_module/node folders. This makes the build process take much longer then it should.

#### Steps to Reproduce

1. Generate a new project using the archetype (20) and include the ui.frontend module
2. run `npm run dev` or `npm run prod`

#### Sample Code that illustrates the problem

Clean up the regular expressions to force linting/processing only on files in the `src` folder:

`webpack.common.js`:

```diff
   new TSLintPlugin({
-                files: ['./**/components/**/*.ts', './**/components/**/*.tsx']
+                files: ['./src/**/*.ts', './src/**/*.tsx'],
+                config: './tslint.json'
            })
```

There may be other clean up as well related to the use of `**`...

https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.frontend/webpack.common.js#L91

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-project-archetype/commit/700aaf57ca1d469203b94d4b4b6bf2c6df3eaa32

@godanny86 Thank you!
