### ISSUE TITLE
Feature: Add empty "Experience Fragment" template type to build Experience Fragment templates

### ISSUE THREAD

**Issue by ksurendra** [adobe/aem-project-archetype#232]
**Feature request:**
Since Experience Fragments are an integral part of AEM and are important, adding an empty "Experience Fragment" template type will allow users to build Experience Fragment templates.

I have the code built and can raise a "Pull Request" if this is approved.

**Why?**
Here's the issue/solution:
An "Experience Fragment" needs to be built in a certain way only.. as follows:

- An Experience Fragment <-- Editable Template <-- Template Type that uses **xfpage** (like sling:resourceType="wknd/components/structure/xfpage"/> and the xfpage component should use sling:resourceSuperType="cq/experience-fragments/components/xfpage")
- The name of the template need to be used for an XF should have the prefix "**experience-fragment**-<name>" [I didn't like this hard rule but the designers of this may have some reasons for this]

Refer: [AEM 6.4 Authoring Guide - Experience Fragments](https://docs.adobe.com/content/help/en/experience-manager-64/authoring/authoring/experience-fragments.html)

So if the Experience Fragment is built using a Template (Editable.. and which is built using a Template Type ) built as above.. ONLY then the XF will show the Variations option.

As of now this "empty experience fragment" template type is missing from the base and will be a lot of help (and saves times) to developers adding this as part of the Archetype. Using this developers can build Templates specifically for Experience Fragments.

**What will be added:**
A template type that uses **XFPage** and a Template that is built using the "template type".

1. XFPage component at  /ui.apps/src/main/content/jcr_root/apps/<proj name>/components/structure/
2. Empty template type at /ui.content/src/main/content/jcr_root/conf/proj name>/settings/wcm/template-types/empty-experience-fragment

**How they appear after deploy:**
1. Template Type
![aem-archetype-xf-empty-tempalte-type](https://user-images.githubusercontent.com/902972/64813393-de08a600-d566-11e9-957b-9ac28dbd03ea.png)

### Expected Behaviour
-NA-

### Actual Behaviour
-NA-

### Reproduce Scenario (including but not limited to)
-NA-

#### Steps to Reproduce
-NA-

#### Platform and Version
-NA-

#### Sample Code that illustrates the problem
-NA-

#### Logs taken while reproducing problem
-NA-

**Comment by gabrielwalt** [comment]
Agreed, we need such templates, which should also be addressed by #191.

**Comment by bpauli** [comment]
Has been fixed in #252
