### ISSUE TITLE
Move template types into /apps/settings

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-project-archetype#233]
As template types currently cannot be edited by the Template Editor and must be provided by the developers, it would be more meaningful to have them by default located inside `/apps/settings` than inside `/conf`.

**Comment by davidjgonzalez** [comment]
@gabrielwalt should this still be open due to `/apps/settings` lack of tenant support?

**Comment by gabrielwalt** [comment]
This doesn't seem supported well enough yet in AEM
