### ISSUE TITLE
[Frontend] Add aemsync package to ui.frontend module

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-project-archetype#236]
Story:
As a developer I want to easily validate my changes to clientlib files (JS / CSS) on an AEM based page.

Acceptance Criteria:
Saved changes to a JS and CSS file get automatically synced to a preconfigured AEM instance when a specific npm task is running. Moreover it should be possible to push all files from the ui.frontend module to the AEM instance.

Possible Solution:
Usage of the npm aemsync (https://www.npmjs.com/package/aemsync) package to watch for file changes and push them immediately to an AEM instance. Two new script handlers will be added to either run npm in watch mode or to push all files (filtered JS, CSS, assets) from the ui.frontend module to AEM.

**Comment by austen-wade** [comment]
https://github.com/adobe/aem-project-archetype/pull/376

Created a potential solution for this enhancement.
