### ISSUE TITLE
Integration Tests not executing on Archetype 18-20

### ISSUE THREAD

**Issue by GuillaumeCleme** [adobe/aem-project-archetype#243]
### Expected Behaviour
Running `mvn clean verify -PintegrationTests` on AEM Archetype 20 should trigger server-side integration tests.

### Actual Behaviour
Running `mvn clean verify -PintegrationTests` does not run any tests:

```
[INFO] --- maven-failsafe-plugin:2.22.1:integration-test (integration-test) @ com.test.test.it.launcher ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.1:verify (verify) @ com.test.test.it.launcher ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.027 s
[INFO] Finished at: 2019-10-02T15:22:02-04:00
[INFO] ------------------------------------------------------------------------
```

#### Steps to Reproduce
- Create new AEM Archetype version 20 Project
- Start AEM 6.5 server
- (Optional) Build and deploy the application to the local server using `mvn clean install -PautoInstallPackage`. Add the `-Padobe-public` profile if dependencies are not resolved.
- Run `mvn clean verify -PintegrationTests`
- Profile will run and complete with 0 tests run

#### Platform and Version
- Windows 10.0
- AEM 6.5
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: C:\Program Files (x86)\Maven\apache-maven-3.6.0\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

#### Logs taken while reproducing problem
- Archetype 17 (**Successful Tests**): [archetype17.log](https://github.com/adobe/aem-project-archetype/files/3683119/archetype17.log)
- Archetype 18 (No Tests Run): [archetype18.log](https://github.com/adobe/aem-project-archetype/files/3683120/archetype18.log)
- Archetype 19 (No Tests Run): [archetype19.log](https://github.com/adobe/aem-project-archetype/files/3683122/archetype19.log)
- Archetype 20 (No Tests Run): [archetype20.log](https://github.com/adobe/aem-project-archetype/files/3683123/archetype20.log)

### Hypothesis
In Archetype 18, the `it.launcher` module testing dependencies were updated from `junit` to `junit-jupiter` and `junit-vintage-engine` along with the move to `junit-jupiter` for unit testing in other modules. Switching back to `junit` dependencies and annotations triggers integration tests to run.

This issue could be caused by the `maven-failsafe-plugin` not finding any tests to run due to the expected annotations.

**Comment by GuillaumeCleme** [comment]
Looking at [Maven Failsafe Plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/junit-platform.html) configurations, the Maven Surefire JUnit version detection algorithm is documented in the Provider Selection section. Seeing as all of the `org.apache.sling.junit.*` test dependencies have not been migrated to JUnit5 (Jupiter) yet, the default JUnit5 provider does not seem to process JUnit4 tests located in the `it.launcher` module for them to be launched locally. 

Even though the `junit-vintage-engine` is used, the fact that the JUnit5 dependencies are available means that they take precedence which causes the JUnit4 tests not to run therefore explaining the test report showing 0 tests.

**Comment by vladbailescu** [comment]
@GuillaumeCleme , thanks for reporting this issue and, even better, sending a fix PR!

I'm very interested to understand how you are using the ITs as we were discussing recently about removal of these tests since we thought customers are not really using them.

**Comment by GuillaumeCleme** [comment]
@vladbailescu opened #247 as a PR which includes a fix. 

Very interesting that you mention customers not using IT tests! The issue has gone unnoticed for some time so I believe it, but I still think that integration tests belong in any robust CI implementation. Perhaps adding an archetype option to include IT packages or not would be viable?

There's no doubt a lot of this testing can now be handled as unit tests with the [JcrMock ](https://sling.apache.org/documentation/development/jcr-mock.html) and [SlingMock](https://sling.apache.org/documentation/development/sling-mock.html) but in the case of AEM Forms we still write several integration tests to test unmocked integrations and server-side APIs which cannot easily be run in the context of a unit test.
