### ISSUE TITLE
Double minification of clientlibs generated by ui.frontend module

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-project-archetype#245]
### Expected Behaviour

The CSS and JS generated by the **ui.frontend** module is minified *before* it gets pushed into AEM. I would expect that CSS/JS generated by the ui.frontend module will be ignored by AEM's internal minification engine. I do not want to turn off AEM's minification completely as I also want clientlibraries in AEM (core components, aem grid) to be minified in production.

### Actual Behaviour

CSS and JS generated by the **ui.frontend** module ends up getting double minified because it gets surfaced on the page as an embedded clientlibrary in the [clientlib.base](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-base/.content.xml#L6).

#### Steps to Reproduce

Vanilla config with archetype 21.

#### Potential Solution

A potential solution would be to include any client libraries generated by the **ui.frontend** module on the page by adding them separately and **not** as an embed via clientlib.base. This could be done by updating [customheaderlibs.html](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/customheaderlibs.html#L17) or an even cleaner approach may be to add the generated ui.frontend categories as part of the template page policy:

![image](https://user-images.githubusercontent.com/8974514/66091954-b93c9880-e53e-11e9-87b3-41ae71c00180.png)

Using the template page policy means less reliance on updating the HTL scripts, see the following PR for an example: https://github.com/adobe/aem-guides-wknd/pull/23/files

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-project-archetype/pull/250
