### ISSUE TITLE
Separator Proxy Component not Available from Core

### ISSUE THREAD

**Issue by mac4ru** [adobe/aem-project-archetype#259]
### Expected Behaviour
All the core components proxy should be available in your project code base
### Actual Behaviour
Separator proxy Component is missing
### Reproduce Scenario (including but not limited to)
Create a maven project with archtype 20 and check on separator component
#### Steps to Reproduce
open the components created from the maven archtype 20 and search for separator component
#### Platform and Version
AEM 6.5
#### Logs taken while reproducing problem

**Comment by vladbailescu** [comment]
Fixed in https://github.com/adobe/aem-project-archetype/commit/fa6c046c8c845b627d9e4a90302fb2ace2c478d9
