### ISSUE TITLE
Placeholders with String.split function are not getting replaced 

### ISSUE THREAD

**Issue by bpauli** [adobe/aem-project-archetype#271]
When a project is generated with the Eclipse maven plugin placeholders which contains a string.split function are not getting replaced.

![image](https://user-images.githubusercontent.com/689884/68674569-67802880-0556-11ea-9bac-56ea01ec1469.png)

**Comment by rahuljain7th** [comment]
I am also facing the same issue.
![image](https://user-images.githubusercontent.com/4212328/72304766-86c33100-363f-11ea-8544-b8d3604be5d7.png)
