### ISSUE TITLE
Documentation for the "all" module

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-project-archetype#272]
I just wanted to come up with some documentation for the "all" module, and therefor analyzed the the details of the pom. But to be honest, I don't really get it. I am especially wondering about the "clean" in the "install" phase.

So I assume that a simple ```mvn clean install```is not intended to be used here, but some profile should be used as well, to install the application including the latest WCM components into an AEM instance.

So it would be great, if someone could shed some light on the purpose of this "all" module.

**Comment by msagolj** [comment]
@joerghoh FYI: The 'clean' step at 'install' phase looks like a bug. I filed an issue to fix it , see #289

**Comment by godanny86** [comment]
is the `autoInstallSinglePackage` profile recommended to build the entire project? i.e if you want to build and deploy the project for the first time from within the parent?

cc. @richardhand

**Comment by pmichelotti** [comment]
Adding on a specific question here, how is the all module intended to be used in the context of the cloud manager where any zip files found under target directories are deployed.  Would the all module not result in the code effectively being deployed twice?

**Comment by vladbailescu** [comment]
@pmichelotti , as per https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html#marking-packages-for-deployment-by-adoube-cloud-manager , adding `<cloudManagerTarget>none</cloudManagerTarget>` (such as in https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.content/pom.xml#L56) ensures not all zip files are being picked up.

**Comment by vesankar** [comment]
@joerghoh One of my customer claims that presence of ALL module ends up in not installing packages. Removing ALL module avoids the installation issue.. Any idea on why we need ALL module?

**Comment by Eduardo-SBorges** [comment]
Hi guys, the "all" module is very important. It's responsable to keep all the package of our project.

See this image: https://prnt.sc/ejLlS0g9ObKh

If you try to delete the folder "apps/example-packages" on CRXDE, all the application will crash, because all the reference of the project is there.
