### ISSUE TITLE
webpack plugin clean-webpack-plugin not encoding svg file url's properly

### ISSUE THREAD

**Issue by chitikenasatish** [adobe/aem-project-archetype#273]
### Expected Behaviour

After SAAS compile clean css plugin used to encode svg file url's 

It needs to be like this 
url(data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg…26%2C42.85Z%22%20transform%3D%22translate(0%20-91.06)%22%2F%3E%3C%2Fsvg%3E);

when minified, the spaces in the data uris are not converted to %20.
url(data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="htt….33,6.93-57.42,21.11-66.26,42.85Z" transform="translate(0 -91.06)"/></svg>);
 

### Actual Behaviour
Even though it has clean webpack plugin it is not encoding spaces.

#### Steps to Reproduce
Add the below line to scss file.
 $svg-icon: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="750" height="750"><path fill="#{$color}" stroke="#{$stroke-color}" stroke-width="#{$stroke-width}" d="M751.16,658q-173.65-70.74-376.33-70.82Q172.39,587.18,0,658q100.1-59,220.92-82.63c1-7.83,2-20.15,3-36.85s1.47-29.27,1.47-37.63-1-19.91-2.94-34.66v-7.41c0-11.78,2.64-27.55,8.09-47.19s8.59-34.42,9.58-44.26c4.85-15.77,13.71-25.57,26.49-29.53a12.25,12.25,0,0,0,1.47-4.35c3.92-20.68,1.92-32.47-5.9-35.4-8.83-4-14.28-10.35-16.19-19.25a17.87,17.87,0,0,1-3-10.32c7,4,12.82,5.46,17.72,4.41-1.46-3-2.21-4.41-2.21-4.41l-2.22-2.94c-11.76-2.93-17.15-9.89-16.13-20.68,6.85,4.94,11.22,3.92,13.23-2.94V225q0-12.47.72-19.91A147.66,147.66,0,0,1,257,188.14c1.47-6.39,3.68-11.55,6.65-15.53a126.61,126.61,0,0,1,36.11-50.17A138.22,138.22,0,0,1,355,93.69q30.9-8.14,68.47,8.85t69.94,59.78q36.74,50.15,25,91.48c-1.92,2.91-3.93,4.38-5.84,4.38s-4,1.5-6,4.37q-16.12,22.18-30.93,28c-7.84,5.9-10.3,12.5-7.36,19.91s4.22,14.51,3.68,21.38-6.14,10.82-16.94,11.81l-.69,6.59c-.6,4.44-2.22,7.17-5.21,8.13-5.9,1-9.31,2-10.3,2.94a10,10,0,0,1-4.43,8.84,33.76,33.76,0,0,1-6.62-1.5c-3.44-.89-5.15-.48-5.15,1.5q-13.25,17.69-39.7,1.5c31.35,34.45,48.59,61.5,51.47,81.11,0,3,1.77,13,5.21,30.28s5.15,28.24,5.15,33.19c24.55-7.85,41.76-16.73,51.46-26.57a91.62,91.62,0,0,1,11.86-10.34c1.23-.48,2.46-1,3.68-1.47l2.22-1.5c4.91-2.93,7.42-4.37,7.42-4.37l4.34-1.47a10.06,10.06,0,0,1,7.37-2.91l1.46-2.94c2.94-3,5.9-4,8.83-3a14.41,14.41,0,0,1,2.94,4.38v1.53c0,3.93-1.86,8.3-5.84,13.22-1.11,2.13-4.1,4.11-9,6,2.93.93,6.88.51,11.77-1.47l6-5.94c2.88-4.91,5.33-7.85,7.31-8.84,2-1.95,4-2.49,5.9-1.47l3,3V475l2.87-4.37c3-1.95,5.45-2.49,7.43-1.47l1.46,1.47a16.57,16.57,0,0,1,5.16.75c1.46.47,2.21,1.73,2.21,3.71a11.21,11.21,0,0,1-1.47,4.38h2.94a6.1,6.1,0,0,1,1.46,4.44l-1.46,4.38-1.47,2.93,1.47-1.41c-5.84,11.79-9.34,18.12-10.3,19.13-5.9,6.9-10.81,11.88-14.73,14.79-7.85,5.9-18.71,9.32-32.39,10.34h-1.53c-3.92,2.94-13.27,14.78-28,35.41Q637.85,591.57,751.16,658ZM293.07,510.48c3.92,2.91,6.91,3.9,8.89,2.91q33.85-39.84,83.92-41.34l2.93-1.47V466.2c-3.92-7.92-14.28-10.34-30.92-7.44h-1.53c-35.33,6.93-57.42,21.11-66.26,42.85Z" transform="translate(0 -91.06)"/></svg>';
 
run the build 

#### Logs taken while reproducing problem

**Comment by bpauli** [comment]
@chitikenasatish spaces don't need to be encoded to support SVG in IE. Please have a look at https://codepen.io/tigt/post/optimizing-svgs-in-data-uris for more information. If you need a special encoding in your sass files you can probably also include https://codepen.io/jakob-e/pen/doMoML to you project.

As this is a very special requirement we're going to keep the current css optimization with cssnano and svgo.
