### ISSUE TITLE
Update htl-maven-plugin

### ISSUE THREAD

**Issue by dhardtke** [adobe/aem-project-archetype#275]
Similar to https://github.com/adobe/aem-core-wcm-components/issues/302 the currently used htl-maven-plugin (1.0.6) is quite old now and does not support newer features like the `in` operator or `decorationTagName`.

Can this be updated? It's defined in src/main/archetype/pom.xml.

**Comment by joerghoh** [comment]
Hi @dhardtke , can you provide a pull request for this?

**Comment by dhardtke** [comment]
Done: https://github.com/adobe/aem-project-archetype/pull/280

I'll sign the CLA as soon as possible 👅

**Comment by bpauli** [comment]
done in https://github.com/adobe/aem-project-archetype/pull/280
