### ISSUE TITLE
Allow optional properties to be specified on the first interactive pass

### ISSUE THREAD

**Issue by jtriemstra** [adobe/aem-project-archetype#281]
The README notes that "If the archetype is executed in interactive mode the first time properties with default values can't be changed (see ARCHETYPE-308 for more details). The value can be changed when the property confirmation at the end is denied and the questionnaire gets repeated, or by passing the parameter in the command line (e.g. -DoptionIncludeExamples=n)."

This appears to only be the case if the default is set as a literal, instead of an expression. So replacing properties like

        
        <requiredProperty key="language_country">
            <defaultValue>en_us</defaultValue>
            <validationRegex>[a-z]{2,3}_[a-z]{2,3}</validationRegex>
        </requiredProperty>    

with pairs like

        
        <requiredProperty key="placeholder_language_country">
            <defaultValue>en_us</defaultValue>
            <validationRegex>[a-z]{2,3}_[a-z]{2,3}</validationRegex>
        </requiredProperty>
        <requiredProperty key="language_country">
            <defaultValue>${placeholder_language_country}</defaultValue>
            <validationRegex>[a-z]{2,3}_[a-z]{2,3}</validationRegex>
        </requiredProperty>

would allow the developer to change the defaults on the first pass through the properties, rather than going through all of them once, answering 'n' to the confirmation, and then going through a second time.

I see that as a better experience overall, and the Maven owners don't seem interested in changing their behavior. Before I file a PR, I'm curious how the project owners here feel.

**Comment by gabrielwalt** [comment]
This should get fixed with #294.
