### ISSUE TITLE
Merge with SPA Archetype

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-project-archetype#282]
We want to merge the AEM SPA Archetype into the regular AEM Project Archetype, because there are many commonalities between the two, and because this should make it easier to keep the two in sync.

We want only one starting point for creating AEM Sites, regardless whether they are SPA/PWA or not. The AEM Project Archetype should be that starting point, but there will obviously be an option about whether a SPA should be generated out of it or not. We should however seek to keep the difference between the two as small as possible.

**Comment by godanny86** [comment]
+1 to this initiative!

**Comment by jbmatheson** [comment]
+1 to this for sure!
