### ISSUE TITLE
Maven Project Archtype 22 Issue

### ISSUE THREAD

**Issue by mahamoodahmed** [adobe/aem-project-archetype#288]
I am creating new Maven Project Arch Type 22.

mvn archetype:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=22

The project get created without any issues.

 

Post project creation when I run "mvn -U clean install" command. I am seeing this exception.

 

Unresolveable build extension: Plugin org.apache.jackrabbit:filevault-package-maven-plugin:1.0.1 or one of its dependencies could not be resolved: Failed to collect dependencies at org.apache.jackrabbit:filevault-package-maven-plugin:jar:1.0.1 -> org.apache.jackrabbit.vault:org.apache.jackrabbit.vault:jar:3.1.42: Failed to read artifact descriptor for org.apache.jackrabbit.vault:org.apache.jackrabbit.vault:jar:3.1.42: Could not transfer artifact org.apache.jackrabbit.vault:org.apache.jackrabbit.vault:pom:3.1.42 from/to adobe-public-releases (https://repo.adobe.com/nexus/content/groups/public): C:\Users\xyz\.m2\repository\org\apache\jackrabbit\vault\org.apache.jackrabbit.vault\3.1.4 2\org.apache.jackrabbit.vault-3.1.42.pom.part.lock (The system cannot find the path specified) -> [Help 2]

I noticed the jackrabit vault which showing as could not be resolved is not available in adobe repository Index of /groups/public .

Considering that I am using correct settings.xml  mentioned in Adobe Tutorial  1 - Project Setup .  Please advise if there is anything additionally I am missing in setup.

**Comment by mahamoodahmed** [comment]
I believe if this path is accessed from India getting 404 exception. The same URL if it hit from US its works and having files.

https://repo.adobe.com/nexus/content/groups/public/org/apache/jackrabbit/vault

404 - Path /org/apache/jackrabbit/vault not found in group repository "Public Repositories" [id=public].
Path /org/apache/jackrabbit/vault not found in group repository "Public Repositories" [id=public].

**Comment by gabrielwalt** [comment]
Looks like this issue has resolved itself. Please tell if that's not the case.
