### ISSUE TITLE
Simplify Archetype variables

### ISSUE THREAD

**Issue by gabrielwalt** [adobe/aem-project-archetype#294]
I'd like to encourage everybody who has an opinion on this to express himself/herself:
There seems to be room to reduce the number of variables that the archetype takes as parameter as we have currently over 20 variables.

My suggestions:
* `name` should replace:
  - `artifactName`
  - `packageGroup`
  - `componentGroupName`
  - `siteName`
* `id` should replace:
  - `artifactId`
  - `appsFolderName`
  - `confFolderName`
  - `contentFolderName`
  - `cssId`
* `package` should be removed and created out of: `${groupId}.${id}`
* `optionIncludeErrorHandler` after implementing #290, this option should go away entirely (always have an error handler)
* `optionIncludeFrontendModule` this option should be removed entirely (always include it)
* `optionAemVersion` should be used as well for `optionDispatcherConfig` (if possible?)
* `optionDispatcherConfig` should be removed entirely (always include it in the case of aem version being `cloud`)
* `version` should default to `0.0.1-SNAPSHOT`

This way, only following 6 parameters would be required:
* `archetypeGroupId=com.adobe.granite.archetypes`
* `archetypeArtifactId=aem-project-archetype`
* `archetypeVersion=23`
* `name`
* `id`
* `groupId`

And there would be following 5 optional parameters (notice some renaming):
* `aemVersion=6.5.0` (instead of `optionAemVersion`, and which can also be set to the `cloud` value for AEM as a Cloud Service)
* `projectVersion=0.0.1-SNAPSHOT` (instead of `version`)
* `languageCountry=en_us` (instead of `language_country`)
* `isSingleCountry=y` (instead of `isSingleCountryWebsite`)
* `includeExamples=y` (instead of `optionIncludeExamples`)

**Comment by gabrielwalt** [comment]
See also #281.

**Comment by vladbailescu** [comment]
IMO, the bare minimum:
* `groupId` - because Java
* `appId` - for all ^[a-zA-Z0-9\-_]+$  names
* `appTitle` - for all huma-readable names

Optional, for overrides by user:
* `aemVersion` - 6.5.0/cloud
* `appVersion` - 0.0.1-SNAPSHOT
* `languageCountry` - en_us
* `isSingleCountry` - y
* `includeExamples` - y

Maybe:
* `includeErrorHandler` - y
* `includeFrontendBuild` - y
* `sdkVersion`

**Comment by gabrielwalt** [comment]
plus probably something like:

- `isSinglePageApp` - n (could be `react` or `angular`)

**Comment by bstopp** [comment]
I'm not sure that i agree the `artifactId` should match the other items listed under `id`.

Generally the Maven Artifact Id is a more verbose, where as the conf/content/app folder name is very succinct.

**Comment by bstopp** [comment]
Removing `optionDispatcherConfig` prevents all AMS customers from having a pre-baked Dispatcher supported, Cloud Manager deployable module.

**Comment by bstopp** [comment]
`package` being based off of `${groupId}.${id}` presumes that the id is unique and succinct. It also assumes that the id will not have any package-invalid characters in it.

This does to my previous comment: Artifact Ids in a multi-tenant/complex environment should have more than a single-word name, to ensure clarity on their use and content.
