### ISSUE TITLE
Use org.apache.sling.bnd.models.ModelsScannerPlugin in core project

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#297]
It would be nice to move away from Sling Model package declaration, but rather use Sling's `org.apache.sling.bnd.models.ModelsScannerPlugin` which automatically identifies and registers SlingModels in the project. This allows customers to organize their code [1] as it makes sense to them.

[1] https://medium.com/@msandin/strategies-for-organizing-code-2c9d690b6f33

**Comment by bpauli** [comment]
Indeed, that makes sense. I'll prepare a PR for this.
