### ISSUE TITLE
[Angular] Document Model Manager Service inclusion

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#304]
https://github.com/adobe/aem-spa-project-archetype/blob/4ce2eaa02d49cedef6e68a29a5f613360862d9a0/src/main/resources/archetype-resources/angular-app/src/app/components/model-manager.service.ts#L21

It is unclear why the ModelManagerService is included - it does not appear useful or necessary. 

As a general rule, any code included that isn't self-documenting should be well documented in the comments.

**Comment by samuelmeuli** [comment]
**Internal issue:** CQ-4285258

**Comment by gabrielwalt** [comment]
Closing this for now, because the actual work isn't related to the Archetype but to the JS SDK and this is being tracked elsewhere already.
