### ISSUE TITLE
[Angular] MainContentComponent candidate for Node Module inclusion

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#305]
https://github.com/adobe/aem-spa-project-archetype/blob/4ce2eaa02d49cedef6e68a29a5f613360862d9a0/src/main/resources/archetype-resources/angular-app/src/app/components/main-content/main-content.component.ts#L29

It seems like the MainContentComponent is something that could/should be moved into the angular components npm module. Most ppl will use it as is, as its simply a pass-through for the <aem-page..> Component (which IS provided). If this needs to be customized it seems like the provided class could simply be extended.

**Comment by samuelmeuli** [comment]
**Internal issue:** CQ-4285257

**Comment by gabrielwalt** [comment]
Closing this for now, because the actual work isn't related to the Archetype but to the JS SDK and this is being tracked elsewhere already.
