### ISSUE TITLE
[Angular/React] Default Sling Model

### ISSUE THREAD

**Issue by ittaibaratz** [adobe/aem-project-archetype#306]
Use Case: As a Frontend developer with no Java skills, I do not want to always develop a Sling Model for my components.

Currently, if we create a new component (I tried with React but I guess its the same with Angular) that component will automatically dump all its props in the model when a model request is done at a parent level.

For example, lets say I have a new model-less button component at /content/mysamplespa/en/home/jcr:content/root/responsivegrid/button

These requests will be successful, dumping all properties automatically:
```http://localhost:4502/content/mysamplespa/en.model.json```
```http://localhost:4502/content/mysamplespa/en/home/_jcr_content/root/responsivegrid.model.json```
This request done at the component level will fail:
```
http://localhost:4502/content/mysamplespa/en/home/_jcr_content/root/responsivegrid/button.model.json

Invalid recursion selector value 'model'
Cannot serve request to /content/mysamplespa/en/home/_jcr_content/root/responsivegrid/button.model.json in org.apache.sling.servlets.get.DefaultGetServlet
```

This does not create a problem when running the app, it does create a problem during authoring, as the author will query the model at the component level after it was authored. 

Suggestions:

1. Model-less components should render at the component level, same as they render through their parents.

2. We should include a sample dump-all sling model that can be used as a super type for all components. I have created one in my SPA, however it puts all the properties under an "all" node:

```
public class BaseComponentExporter implements ComponentExporter {
    static final String RESOURCE_TYPE =
            "mysamplespa/components/base";

...

    private Map<String, Object> getExportedProps(Resource res) {
        Map<String, Object> props = res.getValueMap()
                .entrySet().stream().filter(x -> {
                    return !x.getKey().contains(":");
                })
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));

        res.getChildren().forEach((Resource child) -> {
            props.put(child.getName(),getExportedProps(child));
        });

        return props;
    }

    public Map<String, Object> getAll() {
        return getExportedProps(request.getResource());
    }
```

**Comment by samuelmeuli** [comment]
**Internal issue:** CQ-4285256

**Comment by davidjgonzalez** [comment]
IMO the archetype should not be adding code to the AEM Project - if there is value in having a `DialogPropertiesComponent` SlingModel, then that should be released as part of a SDK (Core Components, or some other vehicle).  The archetype should add ~0 logic to the project, and only "dumb" skeletal structures -- Any logic/impl (the royal) we deem as useful/best practice/whatever should be abstracted into a referencable, reusabe API/SDK.

Once an AEM project is generated from the archetype, all the code/logic/structure created is no longer under Adobe's control, so Adobe is no longer to improve it over time (bug fix or evolve features).

**Comment by joerghoh** [comment]
@davidjgonzalez too often I find the SampleFilter from the archetype running in production instances? In that case I would opt to remove that sample code, too.

**Comment by davidjgonzalez** [comment]
@joerghoh absolutely agree. None of that sample code (including tests) should be in the archetype that is used to create the baseline for a production codebase, as none of that code should ever be deployed to production.

**Comment by gabrielwalt** [comment]
Closing this for now, because the actual work isn't related to the Archetype but to the JS SDK and this is being tracked elsewhere already.
