### ISSUE TITLE
[Angular/React] Add SPA URL rewrite rules

### ISSUE THREAD

**Issue by samuelmeuli** [adobe/aem-project-archetype#309]
The Angular/React app root URLs should be the same as the one of the general build.

- Current SPA root: `http://localhost:4503/content/testing/us/en/home.html`
- Expected SPA root: `http://localhost:4503/content/testing/us/en.html`

Since the `home` directory (`/content/testing/us/en/home/`) is needed and the content cannot be placed directly in `/content/testing/us/en/` (the `page` JCR node must be below an `spa` node), this will probably have to be done using a URL rewrite rule.

**Internal issue:** CQ-4285274

**Comment by gabrielwalt** [comment]
Closing this for now, because the actual work isn't related to the Archetype but to the JS SDK and this is being tracked elsewhere already.
