### ISSUE TITLE
Wrong property value documented for frontend module

### ISSUE THREAD

**Issue by LukeGrover** [adobe/aem-project-archetype#318]
### Expected Behaviour
The documentation should match the actual property values needed, in this case, `optionIncludeFrontendModule`

### Actual Behaviour
The documentation is incorrect and if used does not produce expected results

### Reproduce Scenario (including but not limited to)
Running the following as documented does not produce the ui.frontend module
```
mvn archetype:generate \
 -DarchetypeGroupId=com.adobe.granite.archetypes \
 -DarchetypeArtifactId=aem-project-archetype \
 -DarchetypeVersion=22 \
 -DoptionFrontendModule=general
```
#### Steps to Reproduce
Execute the Maven command above, as documented nothing happens. The correct option is `-DoptionIncludeFrontendModule`. When used in place of property documented, the resulting multi-module project contains the expected ui.frontend project.

#### Platform and Version
N/A

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by claudiab** [comment]
Adding to this. I cannot generate an angular frontend directory with Maven command: 
mvn archetype:generate -B \
  -DarchetypeGroupId=com.adobe.granite.archetypes \
  -DarchetypeArtifactId=aem-project-archetype \
  -DarchetypeVersion=22 \
  -DgroupId=com.adobe.aem.guides \
  -Dversion=0.0.1-SNAPSHOT \
  -DappsFolderName=wknd \
  -DartifactId=aem-guides-wknd \
  -Dpackage=com.adobe.aem.guides.wknd \
  -DartifactName="WKND Sites Project" \
  -DcomponentGroupName=WKND \
  -DconfFolderName=wknd \
  -DcontentFolderName=wknd \
  -DcssId=wknd \
  -DisSingleCountryWebsite=n \
  -Dlanguage_country=en_us \
  -DoptionAemVersion=6.5.0 \
  -DoptionDispatcherConfig=none \
  -DoptionIncludeErrorHandler=n \
  -DoptionIncludeExaples=y \
  -DoptionFrontendModule=angular \
  -DpackageGroup=wknd \
  -DsiteName="WKND Site"

**Comment by 3ch023** [comment]
> Adding to this. I cannot generate an angular frontend directory with Maven command:
> mvn archetype:generate -B
> -DarchetypeGroupId=com.adobe.granite.archetypes
> -DarchetypeArtifactId=aem-project-archetype
> -DarchetypeVersion=22
> -DgroupId=com.adobe.aem.guides
> -Dversion=0.0.1-SNAPSHOT
> -DappsFolderName=wknd
> -DartifactId=aem-guides-wknd
> -Dpackage=com.adobe.aem.guides.wknd
> -DartifactName="WKND Sites Project"
> -DcomponentGroupName=WKND
> -DconfFolderName=wknd
> -DcontentFolderName=wknd
> -DcssId=wknd
> -DisSingleCountryWebsite=n
> -Dlanguage_country=en_us
> -DoptionAemVersion=6.5.0
> -DoptionDispatcherConfig=none
> -DoptionIncludeErrorHandler=n
> -DoptionIncludeExaples=y
> -DoptionFrontendModule=angular
> -DpackageGroup=wknd
> -DsiteName="WKND Site"

Hi @claudiab , does it work if you change these params?
1. "-DoptionFrontendModule=angular" to **"-DoptionIncludeFrontendModule=angular"**
2. "-DoptionIncludeExaples=y" to "-DoptionIncludeExamples=y" 

```
mvn archetype:generate -B  \
-DarchetypeGroupId=com.adobe.granite.archetypes \
-DarchetypeArtifactId=aem-project-archetype \
-DarchetypeVersion=22 \
-DgroupId=com.adobe.aem.guides \
-Dversion=0.0.1-SNAPSHOT \
-DappsFolderName=wknd \
-DartifactId=aem-guides-wknd \
-Dpackage=com.adobe.aem.guides.wknd \
-DartifactName="WKND Sites Project" \
-DcomponentGroupName=WKND \
-DconfFolderName=wknd \
-DcontentFolderName=wknd \
-DcssId=wknd \
-DisSingleCountryWebsite=n \
-Dlanguage_country=en_us \
-DoptionAemVersion=6.5.0 \
-DoptionDispatcherConfig=none \
-DoptionIncludeErrorHandler=n \
-DoptionIncludeExamples=y \
-DoptionIncludeFrontendModule=angular \
-DpackageGroup=wknd \
-DsiteName="WKND Site" 
```

**Comment by claudiab** [comment]
Thanks @3ch023!  I was able to generate the project but I am not seeing Angular specific files generated.

**Comment by 3ch023** [comment]
@claudiab yes, you are right. I just checked it, also doesn't work for me with react option. It always generates "general", even if I try with both "optionIncludeFrontendModule" and "optionFrontendModule" params at the same time

**Comment by godanny86** [comment]
In archetype 22 the React and Angular options are not available. This will be available once archetype 23 is released. @gabrielwalt what is the recommendation for customers in the interim?

**Comment by gabrielwalt** [comment]
Until we release the SPA capabilities as part of this archetype, please continue using the SPA Archetype: https://github.com/adobe/aem-spa-project-archetype

**Comment by satishkumarjadhav** [comment]
I have tried with archteype 23 but still not able to generate ui.frontend.angular folder so is the issue still open ?
