### ISSUE TITLE
Build-time dependencies missing for common annotations (@Inject, @Named, @Nullable)

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#322]
# Update:

It appears for `@Inject` and `@Named`  ... the 6.5.0 uberjar (which AEM Maven Archetype defines) does work, however 6.5.1 and 6.5.2 of uberjar do not work, but 6.5.3 seems to re-introduce the dependencies and works.  IDK if it's worth adding the javax dependency for 6.5 builds to polyfill 6.5.1 and 6.5.2, or if we should just be documented (or added, commented out, stating its only required if you are on 6.5.1/6.5.2?)

# Expected Behaviour

Maven Archetype provides all the dependencies needed for normal AEM development.

### Actual Behaviour

The AEM project will not build due to missing dependencies for:
 
* Sling Model @Inject annotation
* Sling Model @Named annotation
* @Nullable/@Nonnullable annotations

#### Steps to Reproduce

* Create a Sling Model that uses the aforementioned annotations

#### Steps I took to solve 

Added dependencies 

```
       <dependency>
                <groupId>com.google.code.findbugs</groupId>
                <artifactId>jsr305</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>javax.inject</groupId>
                <artifactId>javax.inject</artifactId>
                <version>1</version>
            </dependency>
```

#### Platform and Version

* AEM as a Cloud Service SDK Quickstart
* Java 11
* Archetype 22 + 6.5.2 Uberjar

**Comment by glasert** [comment]
CQ-4287978

**Comment by vladbailescu** [comment]
@davidjgonzalez , the  `@Inject` and `@Named` annotations are included into the AEM as a Cloud Service SDK:
