### ISSUE TITLE
Configure allowedExpressionOptions with htl-maven-plugin

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#323]
### Expected Behaviour
HTL validation succeeds.

### Actual Behaviour
HTL validation might fail due to vendor-specific options

### Reproduce Scenario (including but not limited to)
Just use a htl file with the following directive
```
<sly data-sly-resource="${'child' @ decoration=true}"></sly>
```
It will incorrectly emit the the warning "Unknown option 'decoration'"

This is due to https://issues.apache.org/jira/browse/SLING-6779 and should be fixed with an appropriate configuration of the htl-maven-plugin via parameter `allowedExpressionOptions`. For a reasonable default set in AEM look at https://github.com/adobe/aem-core-wcm-components/pull/879/files#diff-06785c6c4064f4138325648231a99658R77

**Comment by bpauli** [comment]
@kwin Thank you for this request!
