### ISSUE TITLE
Upgrade to filevault-package-maven-plugin 1.1.4

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#325]
The newly added validation capabilities (http://jackrabbit.apache.org/filevault-package-maven-plugin/validators.html) are beneficial for all projects, therefore the archetype should be updated to use the `filevault-package-maven-plugin` in version 1.1.0 and all content-packages within the archetype should be explicitly marked as a specific package type != mixed (instead of relying on automated tagging).

This is especially helpful for AEM as a Cloud Service (https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html#package-types)

**Comment by kwin** [comment]
According to https://issues.apache.org/jira/browse/JCRVLT-170 container packages must not contain any content packages. IMHO this makes sense, as otherwise the container would contain mutable and immutable content.

**Comment by DominikSuess** [comment]
@kwin  I think the statement about content packages is not fully clear. Yes one can read it like that but in fact based on the discussions we had back then it would make sense to have container packages not contain content (directly) but implicitly as content-packages. Otherwise you currently have no mechanism to define a common container for correclating application with some "default" content.

**Comment by kwin** [comment]
@DominikSuess Please create a follow-up JIRA then in FileVault to clarify what should be allowed within Containers!

**Comment by kwin** [comment]
This is discussed now in https://issues.apache.org/jira/browse/JCRVLT-401.

**Comment by kwin** [comment]
This issue should be fixed in the upcoming f-p-m-p 1.1.2.

**Comment by kwin** [comment]
@bpauli Maybe you want to try with the just release filevault-package-maven-plugin 1.1.2. You just need to clean up your applications package, as that is not supposed to contain OSGi config nor bundles (https://issues.apache.org/jira/browse/JCRVLT-170) but currently does (https://github.com/adobe/aem-project-archetype/tree/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/config.author and https://github.com/adobe/aem-project-archetype/blob/7944da9ccc47da5f74ccdd74cbd3b1280b83c603/src/main/archetype/ui.apps/pom.xml#L66)

**Comment by kwin** [comment]
@bpauli @vladbailescu @gabrielwalt @DominikSuess  Any update? I can provide a PR as well if you agree that the archetype should rather follow JCRVLT-170 than the Adobe documentation! Otherwise please create a new issue for Jackrabbit Filevault to discuss relaxing the "application" package filter rules.

**Comment by timdonovanuk** [comment]
Please do update as currently trying to fix the broken example WKND project by using filevault-package-maven-plugin 1.1.0 breaks it new ways à la this issue.

**Comment by godanny86** [comment]
@timdonovanuk 
WRT:
> fix the broken example WKND project...

Upgrading `filevault-package-maven-plugin` looks to be an enhancement. The WKND example should be working. What issues are you having?

**Comment by timdonovanuk** [comment]
Actually apologies @godanny86 , I see the WKND is using filevault-package-maven-plugin v1.1.0. I was getting the errors reported in #358 and some weird errors about uninstalling java 1.8 when I remove Java project facets, but they seem to disappear after restarting Eclipse.

**Comment by DominikSuess** [comment]
@kwin It would be very much appreciated if you could provide some guidance on how we could in a first step refactor the structure without having to shift the install folders. I agree that we eventually would want to shift install and config folders to the container package but especially when it comes to inclusion of 3rd party libraries customers may not have the luxury of being able to refactor right away, so having a set of validators that pass on a legacy setup would help a lot.

**Comment by kwin** [comment]
@DominikSuess As you are Jackrabbit committer as well I would suggest that you create a JIRA issue at https://issues.apache.org/jira/projects/JCRVLT/issues and refer to https://issues.apache.org/jira/browse/JCRVLT-170. Relaxing the validation would require code changes (as this is not compliant with the package type definition). Please compare with https://issues.apache.org/jira/browse/JCRVLT-411 which introduced such a flag for complex rules!

So right now you could only rely on package type "MIXED" to not make validation fail!

**Comment by kwin** [comment]
>  I agree that we eventually would want to shift install and config folders to the container package but especially when it comes to inclusion of 3rd party libraries customers may not have the luxury of being able to refactor right away, so having a set of validators that pass on a legacy setup would help a lot.

This is the archetype project which is only used at project start. If you do not start with the recommended setup at that point in time I don't know when? Why can't you follow those rules at least in the archetype (which should be the perfect setup/configuration to start with).

Old projects don't care about the archetype at all, right?

**Comment by kwin** [comment]
@DominikSuess @gabrielwalt Any update here? I think the archetype should reflect best practices and currently it just violates the package type definitions of FileVault which makes validation of projects created with the archetype fail!

**Comment by joerghoh** [comment]
I had to include recent bundles which already have JPMS support, so I have to bump the filevault to at least 1.10.0 (JCRVLT-418). But now I have to rework the complete package structure coming from the archetype to get the project getting properly validated, because the archetype structure does not (yet) follow these guidelines.

Would really love to get these changes implemented.

**Comment by bpauli** [comment]
@kwin can you please review the PR? Thanks!
