### ISSUE TITLE
Dependencies on sub-projects should use ${project.version} for their version (and not hardcode the version specified at archetype generation)

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#326]
### Expected Behaviour

Auto-generated project dependencies should use `${project.version}` for their dependencies version. For example, in my generated `ui.apps` project,  the following dependencies should have version variables added as these are ~always kept in sync across the project.

This should be expanded across any generated sub-project, and only using `ui.apps` as an example.

```
    <dependencies>
        <dependency>
            <groupId>com.adobe.aem.guides</groupId>
            <artifactId>com.adobe.aem.guides.wknd-mobile.core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.adobe.aem.guides</groupId>
            <artifactId>com.adobe.aem.guides.wknd-mobile.repository-structure</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
        </dependency>
```

### Actual Behaviour

Auto-generated project dependencies hardcodes the version specified during archetype execution into the , in this case `2.0-SNAPSHOT` into the dependencies.

```
    <dependencies>
        <dependency>
            <groupId>com.adobe.aem.guides</groupId>
            <artifactId>com.adobe.aem.guides.wknd-mobile.core</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.adobe.aem.guides</groupId>
            <artifactId>com.adobe.aem.guides.wknd-mobile.repository-structure</artifactId>
            <version>2.0-SNAPSHOT</version>
            <type>zip</type>
        </dependency>
```

### Reproduce Scenario (including but not limited to)

Generate a new project from v22

#### Steps to Reproduce

Generate a new project from v22

**Comment by bpauli** [comment]
@davidjgonzalez Thanks for the hands up!
