### ISSUE TITLE
Sling Logger configurations should align to common env-specific use-cases

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#331]
### Expected Behaviour

It would be nice if the custom Sling Logger generated by the Archetype would set up to align to common log-use patterns for the supported environments (dev, stage, prod)

* `/apps/..../config` -> (Default) For LocalDev/Dev, set logger to **DEBUG** level to the **error.log**
* `/apps/../config.author|publish.stage` -> For Stage, set logger to **WARN** level to the **error.log**
* `/apps/.../config.author|publish.prod` -> For Prod, set logger to **ERROR** level (or leave undefined) to the **error.log**

### Actual Behaviour

The Sling Logger configuration provided by the Archetype routes log messages for the bundles root package to a custom log file (`project-xxxx.log`) at the **INFO** level.

#### Platform and Version

The proposal to route all the messages to `error.log` is to allow the log messages to be easily obtained via Cloud Manager which only exposes withe `error.log` as the `aemerror` log. 

If Cloud Manager supports exposing custom log files in the future, then this could be revisited, however it seems prudent to align w/ the current state/near-future-state.
 
#### Feedback

I'd like to hear feedback on the default Logger level configurations and granularity to ensure they jive w/ others general needs.

EDIT: Per Rubens Slack feedback for AMS support; make default log level as `DEBUG` for local quickstart dev, and specific stage and prod runmodes explicitly.

**Comment by bpauli** [comment]
fixed in 90735aa900ab62ab7c5d61a988d2d90cf8d742f1
and 6cff98d6286b579d0eb323494c59d038c274284f
