### ISSUE TITLE
Mapping/Rewrite rules don't support Image Core Component

### ISSUE THREAD

**Issue by bstopp** [adobe/aem-project-archetype#337]
### Expected Behaviour

When using the dispatcher module with the associated Resource Resolver Factory rewrite rule, images referenced in `/content/wknd` should resolve. 

### Actual Behaviour

Any images in the Image Core Component don't resolve correctly due to rewrite and mapping rules.

The image component maps the path from `/content/wkdn/us/en/....` to `/us/en/...` causing them to return 404 at Apache/Dispatcher as they are not mapping to the page's path in the repository.

#### Steps to Reproduce

Following the WKND Tutorial identified an issue.

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-project-archetype/commit/7f008a50d700c99dad41bb934a48c60b86c8012d
