### ISSUE TITLE
Rename `repository-structure` project to `ui.apps.structure`

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#339]
It would be nice to adjust the naming of the `repository-structure` to be more semantic AND idiomatic.
I propose the naming: `ui.apps.structure` and the prefix of `ui.apps` helps convey the scope of the `structure` project (ie. it defines the root repo structure expectations OF the ui.apps project). 

The additional benefit is it just looks nicer when its listed in Eclipse/Intellij next to all the other "nicely" named projects. :)

**Comment by vladbailescu** [comment]
We are using the best practices documented at https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/developing/repository-structure-package.html

@DominikSuess , would it be ok to update the name of this module?

**Comment by DominikSuess** [comment]
@vladbailescu  - makes sense from my perspective.

**Comment by davidjgonzalez** [comment]
@vladbailescu ill update that document you linked as well.

**Comment by davidjgonzalez** [comment]
@vladbailescu FYI - the documentation is updated and ready to release whenever.
