### ISSUE TITLE
Adjust bnd-maven-plugin configuration

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#341]
The configuration for the bnd-maven-plugin at https://github.com/adobe/aem-project-archetype/blob/186586e9bc1e31f9990b83d91845cf0267ff0d09/src/main/archetype/core/pom.xml#L45 should be adjusted to 

- Support reproducible builds (https://github.com/bndtools/bnd/issues/3521)
- Export only non-conditional, versioned packages (https://issues.apache.org/jira/browse/SLING-9033)

In addition the version should be increased to 5.0.

Also since this configuration is not specific for a particular bundle it should rather be set in the root pom (that way other bundle modules will inherit that configuration automatically).

**Comment by bpauli** [comment]
@kwin Thank you for the pointers!

Can you please have a look to the PR I created to address this issue? Thanks!
