### ISSUE TITLE
Remove Hobbes.js tests

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-project-archetype#345]
Since Hobbes.js will[ no longer be supported](https://docs.adobe.com/content/help/en/experience-manager-65/release-notes/deprecated-removed-features.html), we should remove the test example/

**Comment by richardhand** [comment]
@vladbailescu - should we also remove the `/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/tests` folder?

**Comment by tyge68** [comment]
Also note the README need to be updated
