### ISSUE TITLE
Update supported AEM versions

### ISSUE THREAD

**Issue by vladbailescu** [adobe/aem-project-archetype#349]
* Remove 6.3
* Update 6.4 and 6.5 to latest SPs
* Make `cloud` the default AEM version

**Comment by msagolj** [comment]
Some notes:
> Make cloud the default AEM version
Got fixed with  #380 
> Remove 6.3
Partially fixed with #476
> Update 6.4 and 6.5 to latest SPs
Release 24 will contain core components 2.11.0 which requires AEM 6.5.5.0 or AEM 6.4.8.1.
