### ISSUE TITLE
Responsive Grid layout does not work on AEM 6.3, grid_base.less wrong path

### ISSUE THREAD

**Issue by joemaffia** [adobe/aem-project-archetype#353]
If the target AEM version is 6.3.3 the grid_base.less file is pointing to the wrong path...

### Expected Behaviour
`@import (once) "/etc/clientlibs/wcm/foundation/grid/grid_base.less";`

### Actual Behaviour
`@import (once) "/libs/wcm/foundation/clientlibs/grid/grid_base.less";
`
### Reproduce Scenario (including but not limited to)
Open the new example template created by the archetype and try to change the layout...

#### Platform and Version
AEM 6.3.3

**Comment by bpauli** [comment]
@joemaffia Thank you for the hands up! 
However, as we drop the support for AEM 6.3 with the next release (#349 ) of the archetype we're not going to solve this issue. We hope for your understanding.
