### ISSUE TITLE
Revamp it.tests to use aem-testing-clients

### ISSUE THREAD

**Issue by volteanu** [adobe/aem-project-archetype#354]
### Expected Behaviour
The archetype should generate an it.tests module that is using https://github.com/adobe/aem-testing-clients and follows best practices from https://github.com/adobe/aem-test-samples
### Actual Behaviour
A deprecated way of writing tests is generated as part of the archetype

**Comment by volteanu** [comment]
@vladbailescu I'd like to check if this idea is good before starting working on a PR. WDYT?

**Comment by vladbailescu** [comment]
@volteanu , +1 from my side.

**Comment by vladbailescu** [comment]
Fixed by #369
