### ISSUE TITLE
core.wcm.components.version for AEM Version 6.4.3 should be set to 2.5.0

### ISSUE THREAD

**Issue by yakulto** [adobe/aem-project-archetype#355]
### Expected Behaviour
Generation of project with aemVersion=6.4.3 should use the core component version that is compatible with 6.4.3

### Actual Behaviour
Generated core.wcm.components.version is 2.8.0 which is not compatible with 6.4.3

### Reproduce Scenario (including but not limited to)
Generate a project with archetype 23 and aemVersion=6.4.3

#### Steps to Reproduce
mvn -B archetype:generate -D archetypeGroupId=com.adobe.granite.archetypes -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=23 -D aemVersion=6.4.3 -D appTitle="My Site" -D appId="mysite" -D groupId="my.com.website" -D frontendModule=general -D languageCountry=en_us -D singleCountry=n -D includeErrorHandler=n -D includeDispatcherConfig=n -D includeExamples=n 

Open generated POM.xml and see core.wcm.components.version

#### Platform and Version
AEM 6.4.3 (on premise)
#### Sample Code that illustrates the problem
mvn -B archetype:generate -D archetypeGroupId=com.adobe.granite.archetypes -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=23 -D aemVersion=6.4.3 -D appTitle="My Site" -D appId="mysite" -D groupId="my.com.website" -D frontendModule=general -D languageCountry=en_us -D singleCountry=n -D includeErrorHandler=n -D includeDispatcherConfig=n -D includeExamples=n 

#### Logs taken while reproducing problem

**Comment by vladbailescu** [comment]
With #349 we will be updating the supported AEM versions.
