### ISSUE TITLE
[Feature Request] Interactive Run

### ISSUE THREAD

**Issue by VikashKotharyWork** [adobe/aem-project-archetype#357]
Is it possible to run the generate command interactively? Where the properties are requested?

**Comment by vladbailescu** [comment]
Yes, you can run it in interactive mode, just remove `-B`. Also, please note this [known issue](https://github.com/adobe/aem-project-archetype#known-issues):

> When executing the archetype in interactive mode (without the `-B` parameter), the properties with default values cannot be changed, unless the final confirmation gets dismissed, which then repeats the questions by including the properties with default values in the questions (see [ARCHETYPE-308](https://issues.apache.org/jira/browse/ARCHETYPE-308) for details).
