### ISSUE TITLE
[22] Rollout is giving error on default language-masters pages , livecopy relationship is not correct on default generated content pages 

### ISSUE THREAD

**Issue by duchauha** [adobe/aem-project-archetype#360]
#### Expected Behaviour
Once the project is created using the archetype 22  and deployed to local AEM, the User can see default content structure under site console. When the user tries to roll out any changes on any page  under "/content/appFolerName/language-masters/en" to "/content/appFolerName/us/en"  this should work.

#### Actual Behaviour

When the user tries to roll out any changes on any page  under "/content/appFolerName/language-masters/en" to "/content/appFolerName/us/en"   this is giving error.

#### Steps to Reproduce

-  Create a sample project using the command at [1]
 [1] https://docs.adobe.com/content/help/en/experience-manager-learn/getting-started-wknd-tutorial-develop/project-setup.html#create
- Now, build and deploy the code to local AEM
- After the project is deployed to local AEM, go-to site console and open /content/appFolerName/language-masters/en page or create any child page under en and open that.
- Once the page is open in edit mode, try to roll out page using page information pop up.
- Select default live copy from Showing 1 Live Copies window and roll out.
- Roll out will not work and it will show error like ERROR 1 Rollout Operations Failed.

#### Platform and Version
Archetype 22

#### Root Cause:- 
I have added this section myself as I know the root cause.
The default generated content  page /content/appFolderName/us/en/jcr:content missing jcr:mixinTypes = cq:LiveRelationship property.

####  Logs taken while reproducing problem
18.03.2020 16:37:35.967 *ERROR* [0:0:0:0:0:0:0:1 [1584529655954] POST /bin/wcmcommand HTTP/1.1] com.day.cq.wcm.msm.impl.commands.RolloutCommand Error during roll-out.
java.lang.NullPointerException: null
	at com.day.cq.wcm.msm.impl.RolloutManagerImpl$RolloutSettings.fromRelationship(RolloutManagerImpl.java:1224) [com.day.cq.wcm.cq-msm-core:5.12.36]
	at com.day.cq.wcm.msm.impl.RolloutManagerImpl.rollout(RolloutManagerImpl.java:537) [com.day.cq.wcm.cq-msm-core:5.12.36]
	at com.day.cq.wcm.msm.impl.MoveLiveCopyResourceConflictHandler.handleConflict(MoveLiveCopyResourceConflictHandler.java:139) [com.day.cq.wcm.cq-msm-core:5.12.36]
	at com.day.cq.wcm.msm.impl.MoveLiveCopyResourceConflictHandler.handleNameConflict(MoveLiveCopyResourceConflictHandler.java:103) [com.day.cq.wcm.cq-msm-core:5.12.36]

**Comment by vladbailescu** [comment]
@duchauha Thanks for reporting this, along with the probable root cause. To speed up fixing this bug we would greatly appreciate a contribution in the form of a PR.

**Comment by duchauha** [comment]
@vladbailescu  Sure !! I'll try to fix it asap(maybe tomorrow as right now it is very late here in India) and raise a PR.

**Comment by duchauha** [comment]
@vladbailescu   I have made the fix but I am not able to push it, getting wrong user/password error although the same is working when logging into github.com. 
can you please help me with the process to raise a PR.
I have tried a few things : -
1) Took clone of  https://github.com/adobe/aem-project-archetype.git and create my bugfix branch but not able to push it.
2) Took clone of https://github.com/duchauha/aem-project-archetype.git and create my bugfix branch but again not able to push it.

can you please help me with the process?
Thanks

**Comment by duchauha** [comment]
@vladbailescu  Ignore my previous comments. After generating the  PAT, I was able to push it.
Although I am a bit confused about the process, I have raised the PR:- https://github.com/adobe/aem-project-archetype/pull/361

so if you see something is not correct about my PR (process or flow vise) let me know.
