### ISSUE TITLE
License not included in generated project nor in derived binary artifacts

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#364]
This archetype is licensed under the ASL 2.0 license (http://www.apache.org/licenses/LICENSE-2.0.html). The requires the redistribution of the license for any derivative work. Please at least include the license in the container artifact (i.e. the `all` package) as well as in the source generated from this archetype.

**Comment by msagolj** [comment]
@kwin just wondering if this applies here, as the generated project is the outcome of using the software so its not a derivative of the archetype. But maybe my understanding of the world 'derivative' is incorrect in this context :)

**Comment by kwin** [comment]
The generated code contains copyright headers referring to ASL 2.0. Therefore I would assume that even the generated pom.xml and other source files are covered by the license. Maven modules containing those source files with copyright headers are IMHO derivative work

**Comment by msagolj** [comment]
@kwin ah yes , the generated code itself has ASL 2.0 reference. Thank you for clarification :)

**Comment by gabrielwalt** [comment]
I don't think it's necessary to add the license to compiled packages. The license makes sense only in relation to the sources.

**Comment by kwin** [comment]
I am not a lawyer but I would say that that even compiled packages count as "derivative work" and must therefore contain a license as well.
