### ISSUE TITLE
Generated project fails on maven install:install plugin goal

### ISSUE THREAD

**Issue by dontsu** [adobe/aem-project-archetype#365]
I've generated a project using 

`mvn archetype:generate -B -D archetypeGroupId=com.adobe.granite.archetypes -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=23 -D appTitle="testzouw" -D appId="testzouw" -D artifactId="testzouw" -D groupId="com.testzouw" -D package="com.testzouwu" -D version=0.0.1-SNAPSHOT -D aemVersion=6.5.0 -D includeDispatcherConfig=n -D frontendModule=general -D includeErrorHandler=y `

Opened it in my IDE, run a mvn clean and then mvn install:install on root project and I get:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-cli) on project testzouw.core: The packaging for this project did not assign a file to the build artifact -> [Help 1]`

Any idea what am I doing wrong?

Thanks in advance!

**Comment by bpauli** [comment]
Instead of only running the `mvn install:install` goal you have to execute the `mvn install` livecycle as other plugins are also assigned to this livecycle.
