### ISSUE TITLE
[React] Page Template contains non-spa components

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-project-archetype#366]
### Expected Behaviour

The page template generated to be used with the SPA Editor should be configured to only allow components that are compatible with the SPA Editor. This should be just the Text component...

### Actual Behaviour

The template policy initially includes several components, none of which work with the SPA Editor:

![image](https://user-images.githubusercontent.com/8974514/78733723-16a11000-78fb-11ea-9c6c-7722a3f42a6f.png)

Even the Text component is missing.

### Reproduce Scenario (including but not limited to)

This occurs on a fresh project creation

#### Steps to Reproduce

1. Generate a fresh project using version **24-SNAPSHOT** (master branch) and the following parameters:

```plain
# Parameters used to generate this project with aem-project-archetype

groupId=com.aem.guides.wknd.app
artifactId=aem-guides-wknd-app
version=1.0.0-SNAPSHOT
package=com.aem.guides.wknd.app
appId=wknd-app
appTitle=WKND App
aemVersion=6.5.0
sdkVersion=latest
languageCountry=en_us
includeExamples=n
includeErrorHandler=n
frontendModule=react
singleCountry=y
includeDispatcherConfig=y
```

2. Build and deploy project to AEM
3. Navigate to http://localhost:4502/editor.html/content/wknd-app/us/en/home.html and http://localhost:4502/editor.html/conf/wknd-app/settings/wcm/templates/spa-page-template/structure.html

#### Logs taken while reproducing problem

**Comment by godanny86** [comment]
The page policy for the http://localhost:4502/editor.html/conf/wknd-app/settings/wcm/templates/spa-app-template/structure.html is also missing the SPA Editor JS:

![image](https://user-images.githubusercontent.com/8974514/78734069-1ce3bc00-78fc-11ea-99e1-1e61c4231a2b.png)

**Comment by msagolj** [comment]
@godanny86 thx for reporting. I added it to the next release milestone.

**Comment by godanny86** [comment]
Thanks @msagolj I also checked with angular:

```
groupId=com.aem.guides.wknd.app
artifactId=aem-guides-wknd-app
version=1.0.0-SNAPSHOT
package=com.aem.guides.wknd.app
appId=wknd-app
appTitle=WKND App
aemVersion=6.5.0
sdkVersion=latest
languageCountry=en_us
includeExamples=n
includeErrorHandler=n
frontendModule=angular
singleCountry=y
includeDispatcherConfig=y
```

And I get the same behavior. I can file another issue or can re-name this one. Whatever is easiest for you...

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-project-archetype/commit/6978b1f890a14c46aa476aa8f5ca9bd6ad8de798
