### ISSUE TITLE
Nice to have: Generate .gitignore file in the root project folder

### ISSUE THREAD

**Issue by ksurendra** [adobe/aem-project-archetype#367]
Most of us use git based repositories to manage code and `.gitignore` is a good file that excludes development files (required locally on developer machine) that are not required to be on a repository. Generating that file along with the archetype would be of great help to developer teams. 

One of the main reason, is excluding "node_modules" folder that holds tons of dependencies files.

### Expected Behaviour
Would be nice if `.gitignore` file is also generated in the root project folder with necessary exclusions. 
The same file is under the archetype source https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/.gitignore

### Actual Behaviour
The file `.gitignore` does not get generated in the generated project root folder.

### Reproduce Scenario (including but not limited to)
Building a new project using archetype command

#### Steps to Reproduce
1. Run the command:
`
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=6.5.0 \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=general \
 -D includeExamples=n
`

2. Go into the project folder `cd mysite`

File `.gitignore` is not found.

<img width="545" alt="Screen Shot 2020-04-08 at 5 01 18 PM" src="https://user-images.githubusercontent.com/902972/78837887-a4900000-79ba-11ea-81dd-acf393e108c1.png">

#### Platform and Version

- Archetype 23
- MacOs

#### Logs taken while reproducing problem

**Comment by godanny86** [comment]
FWIW I tried on my local machine and the archetype did produce the fie `.gitignore`. Also from your screenshot it looks like its there for you?

![image](https://user-images.githubusercontent.com/8974514/78855337-73bec380-79d8-11ea-8776-ef034dcd1f02.png)

**Comment by msagolj** [comment]
@godanny86 thank your for checking. Tested also with different settings and the .gitignore is there everytime. It also has a section for excluding node modules:

```
# NPM
node_modules/
package-lock.json
yarn.lock
```
Closing for now, please reopen if we missed something.

**Comment by ksurendra** [comment]
Thanks for confirming and sorry for my ignorance. Maybe my Os did not show the ".xx" files or the IDE.
