### ISSUE TITLE
Test archetypes in Eclipse before release

### ISSUE THREAD

**Issue by timdonovanuk** [adobe/aem-project-archetype#368]
This is a feature request to please ensure archetype compatibility with Eclipse + AEM plugin before release. The archetype is supposed to be a springboard for developers (particularly new ones), but it never seems to be a smooth process. Every release seems brings new problems, and requires lots of pom hacking and Googling to ensure an error free project. 

As an example, the latest archetype (23):

- hangs windows Eclipse during AEM project creation (probably related to #329)
- requires manually changing filevault-package-maven-plugin to a later version (#358)
- has `jackrabbit-filter: Node is not contained in any of the filter rules` errors
- has `Project build error: Unknown packaging: content-packagepom.xml` errors

I know end to end testing of everything is not possible, but it would be nice if the default path of _Eclipse -> New AEM project_ always worked without half a dozen errors and warnings. 

Thank you!

**Comment by timdonovanuk** [comment]
And a picture being worth a thousand words, this is what a new developer will see after using the latest archetype in Eclipse to create a fresh project:

![2020-04-09 14_37_02-Window](https://user-images.githubusercontent.com/8156439/78901207-e3cc5880-7a6f-11ea-9ef0-c456f0f78dbe.png)

**Comment by timdonovanuk** [comment]
Oh and one other thing...the project should actually build without errors too! If you were unfortunate enough to specify `frontendModule=general` you'll find your shiney new project doesn't actually _mvn clean install_:

[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.foo:foo:0.0.1-SNAPSHOT (C:\eclipse-workspace-2\foo\pom.xml) has 1 error
[ERROR]     Child module C:\eclipse-workspace-2\foo\ui.frontend of C:\eclipse-workspace-2\foo\pom.xml does not exist

and requires commenting out the frontend modules in the root pom.xml.

**Comment by timdonovanuk** [comment]
And if you tick the publish to server box, you'll get yet another error...

```
Publishing failed
Failed installing bundle : Manifest does not have a Bundle-SymbolicName
Manifest does not have a Bundle-SymbolicName
Failed publishing path=/conf/foo/settings/wcm/policies/rep:policy, result=JcrResult[ success:false, exception: org.apache.sling.ide.transport.RepositoryException - javax.jcr.nodetype.ConstraintViolationException: {internal}policy is protected.]
```

**Comment by timdonovanuk** [comment]
And if you try building from the command line you get....

```
[INFO] Scanning for projects...
[ERROR] [ERROR] Project 'org.foo:foo.ui.frontend:0.0.1-SNAPSHOT' is duplicated in the reactor @
[ERROR] Project 'org.foo:foo.ui.frontend:0.0.1-SNAPSHOT' is duplicated in the reactor -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DuplicateProjectException
```

**Comment by msagolj** [comment]
- verified that the project builds without errors
- verified that the project does not throw anymore filevault-package-maven-plugin warnings
- verified that the generated project can be imported in eclipse (there are still some eclipse specific warnings that require changes in eclipse settings but are unrelated to the archetype project itself )
- Due to the changed groupId the released archetype 24 will not be found/selectable in the eclipse AEM plugin tool. This requires a new release of the AEM plugin tool which will be tackled right after the release.

**Comment by msagolj** [comment]
https://github.com/adobe/aem-eclipse-developer-tools/issues/91

**Comment by gabrielwalt** [comment]
Closing this issue as it's more of a task that impacts the Eclipse plugin than the Archetype
