### ISSUE TITLE
Maven execution stops at middle while creating new project

### ISSUE THREAD

**Issue by srikanta72** [adobe/aem-project-archetype#370]
### Expected Behaviour
The project should ve created by maven after running the below command with cloud
```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype23 \
 -D archetypeVersion=23 \
 -D aemVersion=cloud \
 -D appTitle="My AEM Cloud01" \
 -D appId="myaemcloud01" \
 -D groupId="com.aem" \
 -D frontendModule=general \
 -D includeExamples=y
```

### Actual Behaviour
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/aem-project-archetype23/23/aem-project-archetype23-23.pom
[WARNING] The POM for com.adobe.granite.archetypes:aem-project-archetype23:jar:23 is missing, no dependency information available
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/aem-project-archetype23/23/aem-project-archetype23-23.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:22 min
[INFO] Finished at: 2020-04-13T12:28:07+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.adobe.granite.archetypes:aem-project-archetype23:23) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
#### Platform and Version
MAC OS Catelina 10.15.4
Apache Maven 3.6.2
npm --version
6.13.7
node --version
v13.8.0
java --version
java 11.0.5 2019-10-15 LTS
#### Sample Code that illustrates the problem
```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype23 \
 -D archetypeVersion=23 \
 -D aemVersion=cloud \
 -D appTitle="My AEM Cloud01" \
 -D appId="myaemcloud01" \
 -D groupId="com.aem" \
 -D frontendModule=general \
 -D includeExamples=y
```
#### Logs taken while reproducing the problem
Please look above the actual result.

Do let me know any further details are required.

**Comment by vladbailescu** [comment]
` -D archetypeArtifactId=aem-project-archetype23 \` should be just ` -D archetypeArtifactId=aem-project-archetype \`

**Comment by vladbailescu** [comment]
@srikanta72 , did updating the artifact id solve your issues?

**Comment by srikanta72** [comment]
Hi Team,
I am still facing some issues because it gets stuck after the below step for a long time. Not moving to next for a long time. I will try a couple of times this week, if it doesn't work I will continue with the archetype-22. Please check whether this archetype is completely and correctly working in every scenario.

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode

# Waited almost 15 min still it's stuck.

**Comment by srikanta72** [comment]
Do let me know what could be the problem. I do not have any settings.xml inside user/m2/repository folder

**Comment by srikanta72** [comment]
<img width="557" alt="Screenshot 2020-04-18 at 5 18 19 PM" src="https://user-images.githubusercontent.com/25590140/79636979-2c36f500-8199-11ea-9d58-12ee942ae912.png">

I tried with Eclipse as well which is not working. Please look at the screenshot provided above.

**Comment by Integritus** [comment]
I had the same error, or at least the same exact errors from maven. What solved it for me was to add the repository profile to my settings.xml in my .m2 folder from https://helpx.adobe.com/experience-manager/kb/SetUpTheAdobeMavenRepository.html

Now this alone did not fix it. Even after I added that it wasn't picking that profile to pull the resources needed to generate the project from their repo.

I noticed this line
`<activation>
        <activeByDefault>false</activeByDefault>
      </activation>`

And changed it to: 
`<activation>
        <activeByDefault>true</activeByDefault>
      </activation>`

And it worked! Try that and see if that fix it for you. Trying to determine if this is something they messed up on that adobe help article or particular to my local.

**Comment by Integritus** [comment]
After reading a little, instead of changing the activateByDefault flag from false to true, you can add to your command mvn command `-P adobe-public`

In your example that would look like:
`mvn -B archetype:generate -P adobe-public -D archetypeGroupId=com.adobe.granite.archetypes -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=23 -D aemVersion=cloud -D appTitle="My AEM Cloud01" -D appId="myaemcloud01"  -D groupId="com.aem" -D frontendModule=general -D includeExamples=y`

**Comment by srikanta72** [comment]
The issue persists till today,
PFA the screenshot.
<img width="1440" alt="Screenshot 2020-05-11 at 6 54 38 PM" src="https://user-images.githubusercontent.com/25590140/81566843-12b05400-93b9-11ea-9a78-f24545f93d66.png">

**Comment by vladbailescu** [comment]
@srikanta72 , did you follow the advice above to configure the Adobe Maven repository and enable the associated profile?

**Comment by srikanta72** [comment]
I tried the below
1. https://github.com/adobe/aem-project-archetype/issues/370#issuecomment-612951754
2. https://github.com/adobe/aem-project-archetype/issues/370#issuecomment-618733473

What I've not tried:
I did not add any settings.xml or I deleted the existing one in my m2 folder, so that I'll be sure the project should be able to create with default settings. 

Am I the only one getting this issue or others are also getting this?
I checked with one of my colleague that he's also getting the similar issue. 

Please let me know if the issue is specific to me, I'll try to research on system of any fix is available. 


Even I tried Eclipse plugin also there was an issue as I commented earlier. 

Hope I'll get a good stable fix to go with my practice project.

**Comment by srikanta72** [comment]
If you see my last screenshot, I did not change anything in the command and tried to run the exact command given in archetype documentation and still it doesn't work.

**Comment by srikanta72** [comment]
Hi team, I just got the below command from my colleague which is working. However, the below command takes the aemVersion=6.5.0 by default and asks for other parameter values (I guess interactive mode).
```
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \
-DarchetypeGroupId=com.adobe.granite.archetypes \
-DarchetypeArtifactId=aem-project-archetype \
-DarchetypeVersion=23 \
-DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/ 
```

Please fix the given documentation in aem-archetype and make sure that should be working with the given instruction.

**Comment by vladbailescu** [comment]
@srikanta72 , adding `-DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/` is equivalent to https://helpx.adobe.com/experience-manager/kb/SetUpTheAdobeMavenRepository.html . Setting up the Maven environment is a mandatory stept, which you did not do, an documented at https://github.com/adobe/aem-project-archetype#system-requirements.

Will close this; I'm glad you found an alternate solution, but I respectfully suggest you do add the proper configuration, it will help later on too.

**Comment by srikanta72** [comment]
Hi @vladbailescu thanks for closing this with appropriate reason. I'm adding the below link which tells setting up settings.xml is must in m2 folder and will help others who will visit this issue.
Following the below adobe doclink to fix the issue:
https://docs.adobe.com/content/help/en/experience-manager-learn/cloud-service/local-development-environment-set-up/development-tools.html

**Comment by oscar-maldonado** [comment]
Hello,

Here my small contribution. Using https://repo.adobe.com/, when creating a project with the version 23, I had this error (already reported):

```bash
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.adobe.granite.archetype:aem-project-archetype:23) -> [Help 1]
```
Reading this issue, I just noticed that in the README.md file (https://github.com/adobe/aem-project-archetype) says:

`
Note: To run above command with older versions, you have to use the old archetypeGroupId: -D archetypeGroupId=com.adobe.granite.archetype
`

Actually, it should say (the "s" is missing :) )

`
Note: To run above command with older versions, you have to use the old archetypeGroupId: -D archetypeGroupId=com.adobe.granite.archetypes
`

and it works! :)
