### ISSUE TITLE
Auto clean in all pom.xml causing maven release plugin delete the artifactory before releaase.

### ISSUE THREAD

**Issue by bipinbitla** [adobe/aem-project-archetype#378]
Question: Why do we have auto-clean execution here https://github.com/adobe/aem-project-archetype/blob/3d328281d7e4f33d38d8f469e60fbc2ff8be94ef/src/main/archetype/all/pom.xml#L117 when the mvn clean command already does clean and then do install or deploy or whatever? The reason I ask is we are using maven-release-plugin to deploy our app code in artifactory and every time the release plugin is used to build the artifacts and deploy to artifactory this plugin inclusion deletes the artifactory just before deploying. Is it ok to comment this plugin inclusion in all pom.xml ?

**Comment by stefanseifert** [comment]
this is a bug and already fixed the latest versions of the archetype (reported in #289).
it was fixed with #303, i recommend to apply the same fix to your project.
