### ISSUE TITLE
Question: Why do we need "spa.project.core" for SPA projects?

### ISSUE THREAD

**Issue by ksurendra** [adobe/aem-project-archetype#384]
### Expected Behaviour

The "Page" component under `mysite/ui.apps/src/main/content/jcr_root/apps/mysite/components`  has `sling:resourceSuperType="spa-project-core/components/page"` instead of `sling:resourceSuperType="core/wcm/components/page/v2/page"`

Is this because the Core component "Page" `sling:resourceSuperType="core/wcm/components/page/v2/page"` is not SPA ready?

### Actual Behaviour

Observed that the main `pom.xml` of the archetype has the below if the project is "spa" type:
```
<core.wcm.components.version>2.8.0</core.wcm.components.version>
...
<spa.project.core.version>1.0.6</spa.project.core.version>
```
And if we add `$includeExamples "y"` then "core.wcm.components.examples-2.8.0.zip" is installed on AEM.

The "spa-project-core" is installed as a separate folder:

<img width="921" alt="Screen Shot 2020-05-01 at 3 42 36 PM" src="https://user-images.githubusercontent.com/902972/80840251-86d14780-8bc2-11ea-8ae9-7800179bb823.png">

**Usage**:

- The React component "Page" Maps to `${appId}/components/page`
- And `${appId}/components/page` refers to `https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/page`
- The `.content.xml` in this has `sling:resourceSuperType="spa-project-core/components/page"` 
- Can we change this to `sling:resourceSuperType="core/wcm/components/page/v2/page"` ?
- When we tried using `sling:resourceSuperType="core/wcm/components/page/v2/page"`, the template would not load any content. And does not show the components.

#### Steps to Reproduce

Build a new project with v23

```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=6.5.0 \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=general \
 -D includeExamples=n
```

Observe the `mysite\pom.xml` 

#### Platform and Version
AEM 6.5.0
Mac Mojave 10.14

#### Logs taken while reproducing problem

**Comment by ksurendra** [comment]
Also the way this was used in https://github.com/adobe/aem-sample-we-retail-journal looks (maybe better):

React Page component -->  ui.apps/<project>/react/components/react/structure/page
                                                                     |
                                                ui.apps/<project>/spa/components/structure/page 
                                                                     |
                                                ui.apps/core/wcm/components/page/v2/page
                                                                     |
                                                wcm/foundation/components/basicpage/v1/basicpage

**Comment by msagolj** [comment]
The spa.project.core has gone open source meanwhile.  See their documentation /sources there for more information:

https://github.com/adobe/aem-spa-project-core

**Comment by pfauchere** [comment]
We are well aware of the diverging paths the 2 projects took. We are planning a convergence in the form of a contribution to the Page Core Component. This as soon as our roadmaps allow it.
