### ISSUE TITLE
ui.frontend (general) _helloworld.js build error

### ISSUE THREAD

**Issue by jimfrenette** [adobe/aem-project-archetype#392]
### Expected Behaviour
The _helloworld.js builds without any errors

### Actual Behaviour
ERROR in ./src/main/webpack/components/_helloworld.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/ui.frontend/src/main/webpack/components/_helloworld.js
  18:13  error    Unexpected aliasing of 'this' to local variable  @typescript-eslint/no-this-alias
  18:13  warning  'that' is assigned a value but never used        @typescript-eslint/no-unused-vars
  21:13  error    'init' was used before it was defined            @typescript-eslint/no-use-before-define
  87:6   warning  Newline required at end of file but not found    eol-last

#### Platform and Version
node v10.15.0

#### Sample Code that illustrates the problem
in ui.frontend/src/main/webpack/site/main.ts,
add this import
``` 
import "../components/*.js";
```

#### Logs taken while reproducing problem
Version: webpack 4.42.1
Time: 3442ms
Built at: 05/16/2020 9:55:26 PM
Environment (--env): "dev"
 2 assets
Entrypoint site = clientlib-site/site.css clientlib-site/site.js

WARNING in ./src/main/webpack/site/main.ts
Module Warning (from (webpack)-import-glob-loader/index.js):
(Emitted value instead of an instance of Error) Empty results for "import "./**/*.js""
NonErrorEmittedError: (Emitted value instead of an instance of Error) Empty results for "import "./**/*.js""
    at Object.emitWarning (~/dev/aem/aem-project/src/aem-dev-myproject/ui.frontend/node_modules/webpack/lib/NormalModule.js:160:16)
    at replacer (~/dev/aem/aem-project/src/aem-dev-myproject/ui.frontend/node_modules/webpack-import-glob-loader/index.js:85:12)
    at String.replace (<anonymous>)
    at Object.module.exports (~/dev/aem/aem-project/src/aem-dev-myproject/ui.frontend/node_modules/webpack-import-glob-loader/index.js:91:20)

ERROR in ./src/main/webpack/components/_helloworld.js
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

~/dev/aem/aem-project/src/aem-dev-myproject/ui.frontend/src/main/webpack/components/_helloworld.js
  21:13  error  'init' was used before it was defined  @typescript-eslint/no-use-before-define

✖ 1 problem (1 error, 0 warnings)

**Comment by jckautzmann** [comment]
@jimfrenette Thx for your PR https://github.com/adobe/aem-project-archetype/pull/393 that fixes this issue.
