### ISSUE TITLE
Embeds of packages is incorrect for non-cloud projects

### ISSUE THREAD

**Issue by chetanyajain** [adobe/aem-project-archetype#394]
### Expected Behaviour
If my aemVersion != "cloud", then the embeds in the all project should be /etc/packages/<appId>, since /apps/<appId>-packages/<application|content>/install is supported only in AEM Cloud version.

### Actual Behaviour
For all types of AEM version, its currently creating the embeds in /apps/<appId>-packages/<application|content>/install. Non cloud version doesn't install the package from /apps location.

#### Steps to Reproduce
- Create a sample project with aemVersion=6.5.0
- Build the project and manually uplooad only the "appId.all-<version>.zip" package to AEM
- Install the package. This will not install all the embedded projects 

#### Platform and Version
AEM 6.5.x

**Comment by kwin** [comment]
Even in AEM <= 6.5.x packages should be installed via the OSGi installer from `/apps/.../install`! To debug this issue further please check the osgi-installer log for the embedded packages at `/system/console/osgi-installer`

**Comment by chetanyajain** [comment]
you are right @kwin. I didn't realize the /apps/../install. Thank you!
