### ISSUE TITLE
Use Maven central for the AEM as a cloud service SDK

### ISSUE THREAD

**Issue by rombert** [adobe/aem-project-archetype#395]
The AEM SDK is now deployed on Maven Central, so there is no need to use an additional Maven repository anymore.

**Comment by stefanseifert** [comment]
this is great - but on maven central there are not the latest versions?
https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/ -> 2020.5.3360
https://downloads.experiencecloud.adobe.com/content/maven/public/com/adobe/aem/aem-sdk-api/ -> 2020.5.3372

**Comment by rombert** [comment]
This is caused by an issue with the deployment pipeline - we were trying to deploy the `aem-sdk-api` and `aem-sdk-deprecated-6.5-api` together. Since the deprecated artifact had the same version the promotion to Maven Central was rejected, causing the full promotion to fail.

I expect to have a fix for this today and the two repos will be in sync (well, with a small delay of ~10 minutes for Maven Central due to how the deployment process works )

**Comment by rombert** [comment]
@stefanseifert - the two are now again in sync, and Maven Central will be lagging with at most 10 minutes, but I guess that is acceptable.

**Comment by stefanseifert** [comment]
thanks! (and yes, 10min is definitely acceptable...)
