### ISSUE TITLE
which version of org.apache.commons.csv AEM 6.5 support?

### ISSUE THREAD

**Issue by vandsvna** [adobe/aem-project-archetype#401]
I have updated AEM 6.0 to AEM 6.5.

AEM 6.5 doesn't support org.apache.commons.csv . I have tried version 1.8, 1.7, 1.6

Always got below error
org.apache.commons.csv -- Cannot be resolved

Kindly help

**Comment by vladbailescu** [comment]
AEM 6.5 does not include Apache Commons CSV, as you can see in the [Uber-Jar](https://repo.adobe.com/nexus/content/repositories/public/com/adobe/aem/uber-jar/6.5.4/).

You will need to embed that dependency in your bundle, see https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#embedding-dependencies

**Comment by vandsvna** [comment]
I have tried to add below dependency
<plugin>
    <groupId>org.apache.felix</groupId>
    <artifactId>maven-bundle-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <instructions>
            <Embed-Dependency>*;
                |commons-csv
            </Embed-Dependency>
            <Embed-Transitive>true</Embed-Transitive>
        </instructions>
    </configuration>
</plugin>
 
it's not working
