### ISSUE TITLE
Sample code should have low cyclomatic complexity

### ISSUE THREAD

**Issue by badvision** [adobe/aem-project-archetype#411]
### Expected Behaviour
Sample code should follow all best practices, including low cyclomatic complexity and unit test support

### Actual Behaviour
See IDE's reaction to the sample hello-world.js file:
![image](https://user-images.githubusercontent.com/5144198/84421890-d18ea800-abe1-11ea-926e-2a89fa4cd1a4.png)

### Suggested solution
If we are trying to avoid ES6 classes (not sure why, because they're basically standard) then we should use a module pattern and flatten IFFE's in client libraries.  The reason is two-fold: 
1) It helps cut down cyclomatic complexity.  
2) Module pattern lends itself to unit testing (QUnit, Mocha, etc) whereas you cannot unit test anonymous functions such as IFFE pattern.

**Comment by badvision** [comment]
(ES6 = ES2015 -- but the point is here you can cut that cyclomatic complexity from 8 down to 3 for a constructor and 5 for an init function, either using ES2015 class or the older Prototype pattern.  Also should expose HelloWorld externally either by declaring the HelloWorld class in the outer scope or by returning it at the bottom of the IFFE such as:
```
    return {
        HelloWorld : HelloWorld,
        onDocumentReady : onDocumentReady
    };
```
and also at the top:
```
var HelloWorldComponent = (function() {
...
```

That way in a unit test we can access the HelloWorldComponent.HelloWorld and assert behaviors in a test and so on.

**Comment by gabrielwalt** [comment]
Hi @badvision, thanks for the feedback! Your contribution to improving that be very welcome, feel free to go ahead with a PR if you have the time to do so.

**Comment by gabrielwalt** [comment]
Hi @badvision, I'm closing this issue for now, but please reopen/clone this issue in case you're picking it up with a PR.
