### ISSUE TITLE
Switch to more inclusive language

### ISSUE THREAD

**Issue by macdonst** [adobe/aem-project-archetype#412]
Could you please take some time in the next few days to make changes to some terminology in your repos and content as much as is possible:

- Whitelist/blacklist to Allowed List and Blocked List (or Approve List/Deny List - some software uses this instead) respectively. Google and many developers are formalizing allowlist and blocklist. You might want to lobby for those terms to be used in the UI.
- Master/Slave to master and replica (or subordinate, if that makes more sense) respectively.

If you cannot remove the term because the writing for example reflects the UI or the code, please make a note and send me an email to Grp-opensourceoffice@adobe.com so we can bring it that team’s attention. Thanks for your efforts in this matter.

**Comment by msagolj** [comment]
Did a full text search on the project:
- slave: does not occur
- master: occurs in the context of site master/live copy (MSM) or master/variation (XF), which is ok according to above description.
- blacklist: one occurrence as a config option for an external tool named tslint:
https://github.com/adobe/aem-project-archetype/blob/f1eba34a5a0dacc8a95674346d4f18250fa4d2ae/src/main/archetype/ui.frontend.angular/tslint.json#L14
- whitelist: appears several times in the dispatcher configs. This files are provided by the Adobe team that maintains the dispatcher configs. They got the same issue assigned. So once they remove it we should get an update.

So currently there is nothing that can or has to be done in this project. closing.
