### ISSUE TITLE
Update README archetype generate command

### ISSUE THREAD

**Issue by austen-wade** [adobe/aem-project-archetype#414]
### Expected Behaviour
Pasting the archetype generate command from the README to the terminal should result in a successfully generated project.

### Actual Behaviour
Pasting the archetype generate command from the README to terminal results in `The desired archetype does not exist (com.adobe.aem:aem-project-archetype:23)` error message.

Changing -DarchetypeGroupId to `com.adobe.granite.archetypes` resulted in a successful build for me.

#### Steps to Reproduce
1. Copy, paste `mvn archetype:generate -DarchetypeGroupId=com.adobe.aem -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=23 -DaemVersion=cloud -DappTitle="My Site" -DappId="mysite" -DgroupId="com.mysite" -DfrontendModule=general -DincludeExamples=n` to terminal.

2. Run command.

3. Results in error.

#### Platform and Version
Archetype 23, Mac OS Mojave

**Comment by msagolj** [comment]
@austen-wade thx for the report. Your right, the GroupId change does not apply the the archetype 23 example in the README until next release.

reverted the change with commit a0ff35bb34b9941d5b0fb0535c3476076363a6b8
