### ISSUE TITLE
How do you properly use SPA ResponsiveGrid & Container?

### ISSUE THREAD

**Issue by besimhu** [adobe/aem-project-archetype#415]
I am going to ignore the suggested issue template as none of the headings are applicable to my question and I am out of places to ask. 

My question is how do you properly use the ResponsiveGrid and Container? Both components can be imported. But the documentation on https://www.npmjs.com/package/@adobe/cq-react-editable-components#srccomponentsresponsivegridjs is of no help. 

I found the same question asked on https://experienceleaguecommunities.adobe.com/t5/adobe-experience-manager/aem-spa-react-component-with-a-responsive-grid/qaq-p/317853# .... but they marked it as resolved even though they marked it resolved with the incorrect response. 

I would like to be able to create a custom component that I can include the responsive grid inside off of. It is possible through HTL. 

In fact, we were able to create resources through a Java backer and then reference them like so in our react component:

```jsx
<ResponsiveGrid
  key={grid.cqPath}
  isInEditor={Utils.isInEditor()}
  cqPath={grid.cqPath}
  gridClassNames={item.gridClassNames}
  columnClassNames={item.columnClassNames}
  columnCount={item.columnCount}
  cqItems={item[':items']}
  cqItemsOrder={item[':itemsOrder']}
  cqType={item[':type']}
/>
```
(Side note, where do you even find the appropriate props to pass? One of my teammates was able to come up with the props above based on the model.json data and Java itself)

The issue however is that we have to refresh the page each time any changes take place in the layout container inside of the react component. 

Sure, I could nest the Layout Container that is included, HOWEVER, it is severely limiting for layout purposes and we do not wish to use the float approach. 

Furthermore, there are styles applied on the whole body tag to give it a max-width for content. The ideal approach would be to have a parsys/responsiveGrid on the main content and then be able to drag a sectional type component with a responsive grid inside. 

Any help would be beneficial. 

Thanks.

**Comment by pfauchere** [comment]
Hi @besimhu,

> I would like to be able to create a custom component that I can include the responsive grid inside off of. It is possible through HTL.

If that is what I think it is and called _composite components_, it isn't yet supported by the SPA Editor and SDK. No strong commitment, but we currently have the goal to support that capability before the end of the year.

Some customers have worked around the lack of support but the solution is sub-optimal and requires refreshing the editor on one side and passing the edit configuration on the other... The recommendation is not to use composite components until we implement it OOTB.

> Side note, where do you even find the appropriate props to pass? One of my teammates was able to come up with the props above based on the model.json data and Java itself

We are well aware of the problem for you to access the source code. Your first option is to refer to the blueprint and the API of the npm package [0,1]. A common transformation rule between the JSON response and the react properties is that the fields prefixed with the colon character (:) from the JSON object are replaced by the term <cq> and that the rest of the property name is _camelcased_. e.g. <:itemsOrder> -> <cqItemsOrder>

Currently, if you need to access the source code, you have to reach out to your account manager and sign an NDA.

[0] https://docs.adobe.com/content/help/en/experience-manager-65/developing/headless/spas/spa-blueprint.html#meta-fields
[1] https://www.npmjs.com/package/@adobe/cq-react-editable-components#api

**Comment by pfauchere** [comment]
Closing the ticket for now. Feel free to reopen the conversation should you have more questions or feedback
