### ISSUE TITLE
[Logging] Align Log configurations to AEM as a Cloud Service recommendations

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-project-archetype#420]
### Expected Behaviour

Logger configurations should be in the JSON format, and not provide unnecessary properties.

### Actual Behaviour

Logger provides a log format that does not conform w/ expected AEM as a Cloud Service logger patterns, resulting in mixed log statement formates in the AEM as a Cloud Services aemerror log.

#### Steps to Reproduce

Deploy a AEM Project Archetype generated archetype to AEM as a Cloud Service,  invoke code that uses the custom loggers, and review the aemerror log.

#### Platform and Version

AEM as a Cloud Service

#### Logs taken while reproducing problem

See SKYOPS-7378

**Comment by msagolj** [comment]
According to SKYOPS-7378 the conclusion was to ignore any logger settings coming form customer in AEMaaS.  So this would only serve as a short therm solution until SKYOPS-7378 is implemented, so:
- its anyway going to be ignored in the future
- current PR needs investigation into potential NPE for 6.4.x and 6.5.x and my result in additional changes
- changing the default logger format for non AEMaaS might cause trouble for already exiting tooling that parses current log format.

So I will close this PR/Issue for now. Should still really be needed please reopen.
