### ISSUE TITLE
Change to node version or autoprefixer version, for compatibility with Cloud Manager build pipelines

### ISSUE THREAD

**Issue by greggthomason** [adobe/aem-project-archetype#424]
### Expected Behaviour
Local builds and Cloud Manager builds should be identical.

### Actual Behaviour
Cloud Manager builds fail.

### Reproduce Scenario (including but not limited to)
Trigger a build using Cloud Manager.

#### Steps to Reproduce
Trigger a build using Cloud Manager.

#### Platform and Version
archetypeVersion=23 and aemVersion=6.5.0

#### Sample Code that illustrates the problem
The default archetype.

#### Logs taken while reproducing problem
The following error kills the build:

15:38:07,969 [Exec Stream Pumper] [INFO] Error: Package exports for '/build_root/build/appian/ui.frontend/node_modules/kleur' do not define a valid './colors' target

Earlier in the log we see this:

15:38:00,881 [Exec Stream Pumper] [WARNING] npm WARN notsup Unsupported engine for autoprefixer@9.8.3: wanted: {"node":"^6 || ^7 || ^8 || ^9 || ^10 || ^11 || ^12 || >=13.7"} (current: {"node":"13.5.0","npm":"6.13.4"})

According to the upstream at https://github.com/postcss/autoprefixer/issues/1328 the fix is:
    Update Node.js to 14 or >13.7.
    Update Autoprefixer to 9.8.1

Note that https://stackoverflow.com/questions/62481678/react-app-failed-to-compile-after-install suggests you can also downgrade 9.8.0, presumably if you can't do both.

**Comment by msagolj** [comment]
This seems no longer reproducible. Closing for now, please reopen if still an issue.
