### ISSUE TITLE
Question: Different group id for "master" and public release versions?

### ISSUE THREAD

**Issue by ksurendra** [adobe/aem-project-archetype#440]
### Question

The group id is different for Master and Release branches as:

- Master branch: **<groupId>com.adobe.aem</groupId>**

- Release branches: **<groupId>com.adobe.granite.archetypes</groupId>**

Was this to help working on the archetype code on local computer to test the builds ?

I'm using the commands as:

1. To test locally built archetypes use: **-D archetypeGroupId=com.adobe.aem**

    `mvn -B archetype:generate -D archetypeGroupId=com.adobe.aem -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=24-SNAPSHOT -D aemVersion=6.5.0 -D appTitle="Demo Site" -D appId="demosite" -D groupId="com.demo.site" -D frontendModule=general -D includeExamples=y -DarchetypeCatalog=local`

2. And as documented use: **-D archetypeGroupId=com.adobe.granite.archetypes** for public releases

   `mvn -B archetype:generate -D archetypeGroupId=com.adobe.granite.archetypes -D archetypeArtifactId=aem-project-archetype -D archetypeVersion=24-SNAPSHOT -D aemVersion=6.5.0 -D appTitle="Demo Site" -D appId="demosite" -D groupId="com.demo.site" -D frontendModule=general -D includeExamples=y`

**Comment by msagolj** [comment]
Hi @ksurendra , yes we changed the group Id on master for future releases. The reasoning is that there is an ongoing effort to align all our public artifacts related to AEM to follow the same naming patterns and to get rid of internal/superfluous/confusing parts like in our case `granite.archetypes` . See #406 for more details.
