### ISSUE TITLE
Only use relative includes in dispatcher configuration

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#441]
To ease reusing the dispatcher configuration (both `dispatcher.ams` and `dispatcher.cloud` ) the include directives (https://httpd.apache.org/docs/2.4/mod/core.html#include) and `$include` macros in dispatcher configuration (https://docs.adobe.com/content/help/en/experience-manager-dispatcher/using/configuring/dispatcher-configuration.html#dispatcher-configuration-files) should only use relative file paths.

That allows to reuse the same configuration on multiple platforms (Windows and Unix/Linux/Mac) and makes the configuration files smaller at the same time.

**Comment by gabrielwalt** [comment]
Hi @kwin, do you maybe have the possibility to contribute the relative paths?

**Comment by gabrielwalt** [comment]
Many thanks for your contribution, @kwin! We'll review it in the next days, tentatively making it part of release 24.

**Comment by gabrielwalt** [comment]
Many thanks for your contribution, @kwin! We'll review it in the next days, tentatively making it part of release 24.
