### ISSUE TITLE
Enforce that immutable dispatcher configuration files are not changed

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#442]
By using a maven enforcer rules like https://maven.apache.org/enforcer/enforcer-rules/requireFileChecksum.html one can easily enforce at build time that certain files are not touched. That would help to ensure that all files listed in https://helpx.adobe.com/experience-manager/kb/ams-dispatcher-manual/immutable-files.html and https://docs.adobe.com/content/help/en/experience-manager-cloud-service/implementing/content-delivery/disp-overview.html#file-structure respectively are not modified.

**Comment by gabrielwalt** [comment]
Hi @kwin, do you maybe have the possibility to contribute such enforcer rules?

**Comment by gabrielwalt** [comment]
Many thanks for your contribution, @kwin! We'll review it in the next days, tentatively making it part of release 24.
