### ISSUE TITLE
Default build command not working with recent AEM SDK

### ISSUE THREAD

**Issue by pun-ky** [adobe/aem-project-archetype#444]
### Expected Behaviour

Default build command / AEM packages deployment working correctly.

### Actual Behaviour

![image](https://user-images.githubusercontent.com/10673561/89300776-0448a000-d669-11ea-9e03-2863e9f3a8a5.png)

The second package installation fails ("ui.content") as AEM is not responsive. Suspecting inactive component `PackageManagerServlet` at the time of installation. Observed many retries performed by Maven content package plugin when listing packages without effect. After waiting for some time (awaiting stabilization of `PackageManagerServlet`) second attempt using the same command ends with success.

Also observed many OSGi events being triggered infinitely which suggests general instance instability (observable just after turning on instance / regardless package installation), originally spotted here: https://github.com/Cognifide/gradle-aem-plugin/issues/726

#### Steps to Reproduce

Set up AEM author and publish instance using "aem-sdk-quickstart-2020.7.3902.20200716T022312Z-200604.jar"
Generate project from archetype snapshot (actual master) using values

```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.granite.archetypes \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=23 \
 -D aemVersion=cloud \
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite" \
 -D frontendModule=general \
 -D includeExamples=n
```

#### Platform and Version

```
Apache Maven 3.6.3 
Java version: 1.8.0
OS name: "mac os x", version: "10.15.4", arch: "x86_64", family: "mac"
```

**Comment by godanny86** [comment]
@pun-ky what maven command are you running?

**Comment by pun-ky** [comment]
@godanny86 Is visible on screenshot.

I was checking documented build command plus deploying also on publish. So I added autoInstallPackagePublish. 

Right now I've got even more concerns. 

1) what is most recommended command to build? 
2) is it possible to deploy to author and publish during single Maven execution (to avoid building artifacts twice) or I need to run build twice with different profiles? It would be nice if it will be documented.
3) when I have run command on screenshot again then the build ended with success, however 'all' package was also deployed on instance. Strange. I am totally sure that I haven't activated that profile that you mentioned. My intention is to have only deployed ui.apps and ui.content. 

I am aware that AEM dislikes installing package one after another however documentation here is not telling anything which command / approach is most preferred.

**Comment by godanny86** [comment]
The profiles to build+deploy the entire project (running from the root of the parent pom) would be `autoInstallSinglePackage` (author) and `autoInstallSinglePackagePublish`(publish).

If you want to build the modules individually you can navigate into the folder (i.e `cd ui.apps`) and use the `autoInstallPackage` / `autoInstallPackagePublish` profiles.

Agreed that this needs to be reflected in the generated README and in the Docs:

* https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/README.md
* https://docs.adobe.com/content/help/en/experience-manager-core-components/using/developing/archetype/using.html#building-and-installing

Is there other documentation you noticed that needs more information on recommended build commands?

**Comment by pun-ky** [comment]
Indeed, the ability to build modules individually **only from the subdirectory** is a clue here which answers to my problem reported. The second thing is the primary build command to be updated. 

> Is there other documentation you noticed that needs more information on recommended build commands?

That's all right now. Thanks @godanny86

**Comment by msagolj** [comment]
@godanny86 thank you for the contribution :) merged PR,
