### ISSUE TITLE
Import aem-sdk-api additionally with scope "import"

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#456]
In https://github.com/adobe/aem-project-archetype/blob/77a15cdc3d862fb106764187b3b29a9e00dbbbf3/src/main/archetype/pom.xml#L724 the`aem-sdk-api` should be imported additionally with scope `import` (and type `pom`) to also manage the transitive dependencies of `aem-sdk-api`

(e.g. 
```
<dependency>
<groupId>org.apache.sling</groupId>
<artifactId>org.apache.sling.servlets.annotations</artifactId>
<version>1.2.4</version>
</dependency>
```
) defined in https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2020.8.4039.20200813T011654Z-200730/aem-sdk-api-2020.8.4039.20200813T011654Z-200730.pom

**_A prerequisite for that is, that the transitive dependencies of aem-sdk-api are managed in a dependencyManagement section which is currently not the case._**

That way modules can decide whether they want to depend on the big artifact `aem-sdk-api` or on individual open source artifacts (like JCR or Sling API). The latter has the advantage that this eases to enforce usage of a a specific API (e.g. Sling API rather than JCR API) and on the hand keeps the classpath smaller which eases things like "Organize Imports" in IDEs (due to less class name duplicates).

**Comment by kwin** [comment]
A prerequisite for that is, that the transitive dependencies of `aem-sdk-api` are managed in a `dependencyManagement` section which is currently not the case.

**Comment by msagolj** [comment]
Talked to @cziegeler about the prerequisite requirement in the SDK. He agreed that this is required but its currently not planned to be done in the near future. So for now I will close the issue and we can have another look at it, once the transient dependencies becomes part of the SDK pom.
