### ISSUE TITLE
mvn test fails with FileNotFoundException

### ISSUE THREAD

**Issue by sashafirsov** [adobe/aem-project-archetype#483]
### Expected Behaviour
after generated project is created, `mvn test` command passed tests and completed successfully.

### Actual Behaviour
build fails

#### Steps to Reproduce
1. generate project
`mvn    -B archetype:generate    -D archetypeGroupId=com.adobe.granite.archetypes    -D archetypeArtifactId=aem-project-archetype    -D archetypeVersion=23    -D aemVersion=6.5.0    -D appTitle="shop" -D appId="shop"    -D groupId="org.xxx.shop"    -D frontendModule=general
`
2. `mvn test`
3. build is failed 
```
Failed to execute goal org.apache.jackrabbit:filevault-package-maven-plugin:1.0.4:generate-metadata (default-generate-metadata) on project jkp-shop-plans.ui.content: java.io.FileNotFoundException: C:\aWork\shop\ui.apps\target\classes (Access is denied)
```

other commands like `mvn clean install` are successful. The sequence of build and then test does not change the outcome.

#### Platform and Version
In osx and windows 10 up to date version failed with same error.

#### Sample Code that illustrates the problem
n/a
#### related bugs
https://github.com/adobe/aem-project-archetype/issues/161
could not reopen the bug. The bug is identical, the closing reason is not given, definitely not fixed.

**Comment by viveksr2** [comment]
I was facing the same issue, trying with the user having proper permissions resolved the issue for me.

**Comment by msagolj** [comment]
#161 is not showing the same error message so its not the same issue.
Solution was provided in previous comment, thx @viveksr2 . Closing issue.
