### ISSUE TITLE
Fix erroneous and misleading message output by the maven-enforcer-plugin

### ISSUE THREAD

**Issue by justinedelson** [adobe/aem-project-archetype#503]
### Expected Behaviour

The error message output by the enforcer plugin should be an accurate reflection of the error condition.

### Actual Behaviour

It isn't.

The message defined at https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/pom.xml#L130-L134 states "Project must be compiled with Java 8 or higher". This is an *inaccurate* description of what the `requireJavaVersion` rule does.

The `requireJavaVersion` looks at the JRE (the enforcer docs say JDK but that's also incorrect) used by the Maven process in which the enforcer plugin is run. This may or may not be the same as the JRE/JDK used for compilation. Essentially all this rule does is look at the system property `java.version` does some light manipulation of it and compares it to the `version` configuration parameter.

There are two ways I can see to resolve this:

1. If there is truly a requirement for archetype-generated projects to enforce the use of a 1.8 or higher JRE, the message should instead be `Maven must be executed with a Java 8 JRE or higher."
2. If there is not a requirement for archetype-generated projects to enforce this, just remove the enforcer plugin configuration (or at least this rule if the rule for the Maven version is required).

#### Logs taken while reproducing problem

**Comment by kwin** [comment]
Bnd 5.x requires Java 8
