### ISSUE TITLE
archetype 24 does not getting creating says Archetype not found 

### ISSUE THREAD

**Issue by amit-gup** [adobe/aem-project-archetype#507]
###Getting below Error while creating an archetype###

[WARNING] Archetype not found in any catalog. Falling back to central repository.
[WARNING] Add a repository with id 'archetype' in your settings.xml if archetype's repository is elsewhere.
[WARNING] The POM for com.adobe.granite.archetypes:aem-project-archetype:jar:24 is missing, no dependency information available

# try below command in any new machine where your archetype not installed####

mvn org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate -B -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=24 -DfrontendModule=angular -DgroupId="John" -Dversion=1.0-SNAPSHOT -Dpackage="com.DummyProject" -DappId="DummyProject" -DartifactId="DummyProject" -DappTitle="DummyProject" -DincludeDispatcherConfig=n -DincludeErrorHandler=n -DincludeExamples=y

**Comment by nikhilkumar24dev** [comment]
It throws below error:

Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.adobe.granite.archetypes:aem-project-archetype:24)

**Comment by kwin** [comment]
For some reason it seems that the `aem-project-archetype` is not listed in https://repo1.maven.org/maven2/archetype-catalog.xml. @vladbailescu Maybe you need to raise a ticket at Sonatype to ask why the catalog has not been automatically updated.

**Comment by vladbailescu** [comment]
Starting with version 24, the archetype is deployed directly to Maven Central (vis OSSRH). Please not that the `groupId` has changed to `com.adobe.aem` (via #406), which was documented at https://github.com/adobe/aem-project-archetype/commit/41c5905432872072ff421ce3e919b200f6737ee0#diff-04c6e90faac2675aa89e2176d2eec7d8L48

**Comment by nikhilkumar24dev** [comment]
@vladbailescu  Thanks you for the update!! 
I see the griupId is updated and now I was able to generate the Archetype 24 project locally.

**Comment by amit-gup** [comment]
> Starting with version 24, the archetype is deployed directly to Maven Central (vis OSSRH). Please note that the `groupId` has changed to `com.adobe.aem` (via #406), which was documented at [41c5905#diff-04c6e90faac2675aa89e2176d2eec7d8L48](https://github.com/adobe/aem-project-archetype/commit/41c5905432872072ff421ce3e919b200f6737ee0#diff-04c6e90faac2675aa89e2176d2eec7d8L48)

Thanks, it is getting creating now at windows as well as linux.  But it's failing in ubuntu 16.04  while doing the build. I will create a separate bug for it.
