### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#508]
Since maven-archetype-plugin 3.0 giving a remote repository URL or archetype catalog via CLI is no longer supported. Compare with https://issues.apache.org/jira/browse/ARCHETYPE-438, https://issues.apache.org/jira/browse/ARCHETYPE-439, https://issues.apache.org/jira/browse/ARCHETYPE-519 and https://issues.apache.org/jira/browse/ARCHETYPE-518.
Therefore using the aem-project-archetype only works if either

1. you have a global mirror which also includes the catalog from the Adobe Maven Repo or
2. you define the Adobe Maven repo as archetype repository (http://maven.apache.org/archetype/maven-archetype-plugin/archetype-repository.html)

Both approaches need manual adjustment of the `settings.xml`. That is not mentioned though in the current https://github.com/adobe/aem-project-archetype/blob/master/README.md.
To be able to use the archetype without adjusting the `settings.xml` the Adobe AEM Archetype should be deployed to Maven Central instead of the Adobe Repo as that is being looked up by default.

Look at https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2273 on how this was done for ACS AEM Commons.

This will also solve issue #507.

**Comment by nikhilkumar24dev** [comment]
@kwin - What are the updates that should be done as part of settings,xml to get 24 archetype project generated. Didn't got much context on http://maven.apache.org/archetype/maven-archetype-plugin/archetype-repository.html.

**Comment by kwin** [comment]
I missed, that the archetype is in fact already available at Central (being added via https://github.com/adobe/aem-project-archetype/pull/505): https://search.maven.org/artifact/com.adobe.aem/aem-project-archetype/24/maven-archetype.

So the issue in #507 must have some other reason.
