### ISSUE TITLE
Archetype 24- Project build is failing at Linux (Ubuntu 16.04) at ui.frontend module (for angular)

### ISSUE THREAD

**Issue by amit-gup** [adobe/aem-project-archetype#509]
### Expected Behaviour

The project should be built if run "mvn clean install" from the home directory after getting created from archetype 24.

### Actual Behaviour

  Failing at front module

### Reproduce Scenario (including but not limited to)

just try mvn clean install

#### Platform and Version

Ubuntu 16.04

#### Logs taken while reproducing problem

[INFO] Reactor Summary for DummyProject 1.0-SNAPSHOT:
[INFO]
[INFO] DummyProject ....................................... SUCCESS [  0.202 s]
[INFO] DummyProject - Core ................................ SUCCESS [  6.668 s]
[INFO] DummyProject - UI Frontend ......................... FAILURE [  9.131 s]
[INFO] DummyProject - Repository Structure Package ........ SKIPPED
[INFO] DummyProject - UI apps ............................. SKIPPED
[INFO] DummyProject - UI content .......................... SKIPPED
[INFO] DummyProject - UI config ........................... SKIPPED
[INFO] DummyProject - All ................................. SKIPPED
[INFO] DummyProject - Integration Tests ................... SKIPPED
[INFO] DummyProject - UI Tests ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.062 s
[INFO] Finished at: 2020-09-15T02:33:29-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm install) on project DummyProject.ui.frontend: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]

**Comment by joerghoh** [comment]
Do you have ``npm`` installed?

**Comment by msagolj** [comment]
- Automation builds different archetype test scenarios on each [commit](https://github.com/adobe/aem-project-archetype/tree/master/src/test/resources/projects), including one for each frontend module type. 
- They get executed on Windows, Ubuntu and MacOS (Java 8 and 11 each)
- All passed at time of [release](https://github.com/adobe/aem-project-archetype/runs/1103504205)

I therefore assume its something wrong with your setup, as @joerghoh already suggested.

**Comment by amit-gup** [comment]
@joerghoh  @msagolj see all below is installed.

echo| node -v
v14.8.0
echo| nodejs -v
v10.22.0
 echo| npm -v
6.14.7

**Comment by msagolj** [comment]
Does it give any more information about the error in the command line output at the end of the frontend module build section ?

**Comment by amit-gup** [comment]
@msagolj  yes at it says :=> Failed at the puppeteer@5.3.0 install script.

[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! puppeteer@5.3.0 install: `node install.js`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the puppeteer@5.3.0 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR]
[ERROR] npm ERR! A complete log of this run can be found in:

**Comment by msagolj** [comment]
so:
`[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
is there anything useful above ?
`[ERROR] npm ERR! A complete log of this run can be found in:`
is there anything useful in the log mentioned ?
did you check the internet if puppeteer has trouble running with Ubuntu 16.04 ?

**Comment by bpauli** [comment]
@amit-gup Can you please try run the npm install script manually and share the output in this issue?
1. Switch to the ui.frontend folder in your created project `cd ui.frontend`
2. run the npm install command inside of the `ui.frontend` folder `npm install puppeteer@5.3.0`

**Comment by amit-gup** [comment]
@bpauli  @msagolj  It's working now.
