### ISSUE TITLE
Can not see products in Commerce console.

### ISSUE THREAD

**Issue by nikhilkumar24dev** [adobe/aem-project-archetype#515]
I can not see the products in Commerce console, although products get populated in the product section of drag and drop section of page. 
![image](https://user-images.githubusercontent.com/71063587/93891657-45743c80-fd09-11ea-8471-95894c9ff6b1.png)

I see below error in OOTB Teaser component:
![image](https://user-images.githubusercontent.com/71063587/93891218-d26ac600-fd08-11ea-8ebe-365acb34281b.png)

**Comment by mhaack** [comment]
@nikhilkumar24dev does this happen on the local SDK or AEM Cloud instance?

For AEM Cloud instance this is a provisioning issue, please contact support. For AEM Cloud local SDK follow the instructions: https://docs.adobe.com/content/help/en/experience-manager-cloud-service/commerce/develop.html

**Comment by nikhilkumar24dev** [comment]
@mhaack - Thanks for reverting quickly!
I have followed the steps as per the mentioned link, I am getting the product list as part of side panel on page. But can not see it in the Commerce console.
I am using local SDK with CIF Addon.

**Comment by mhaack** [comment]
Ok I see there is something missing in the local SDK documentation. Please see https://github.com/adobe/aem-core-cif-components/tree/master/react-components#prerequisites, you need that local proxy for your Magento env. to deal with CORS. In your AEM CIF config use then `http://localhost:3002/graphql` instead of `/api/graphl`.

**Comment by nikhilkumar24dev** [comment]
@mhaack 
Tried local proxy, products load at http://localhost:3002/graphql but getting same error in AEM 
![image](https://user-images.githubusercontent.com/71063587/93903842-cc7be180-fd16-11ea-93e4-1f3231744132.png)


I suspect something missing as part CIF addon for AEMaaCs SDK.

**Comment by mhaack** [comment]
Your config points still to `/api/graphql` see the error message. You have to update the CIF Cloud Service Config (http://localhost:4502/libs/cif/shell/content/configuration.html/conf/venia) and point the GraphQL URL to `http://localhost:3002/graphql`.

**Comment by nikhilkumar24dev** [comment]
@mhaack - Configuration is already in place.
![image](https://user-images.githubusercontent.com/71063587/93906040-52992780-fd19-11ea-9995-508f9b5c7fac.png)

**Comment by mhaack** [comment]
That looks correct indeep, but looks like it is not used by the console?

**Comment by nikhilkumar24dev** [comment]
Yeah, the console doesn't recognize the new endpoint it seems, and the product teaser throws the error for the new endpoint configured.
![image](https://user-images.githubusercontent.com/71063587/93906663-15816500-fd1a-11ea-8a0b-f6635c42d3ee.png)
 
I am using the Archetype 24 which is CIF loaded.

**Comment by mhaack** [comment]
Can you do a GraphQL call to `http://localhost:3002/graphql` with a GraphQL client? Does it work.

**Comment by herzog31** [comment]
@nikhilkumar24dev can you please provide the SDK and CIF add-on version you are using? Please also share the output of the `npx` proxy command and the JavaScript console of the product console or the dialog (please enable verbose output) of AEM.

**Comment by nikhilkumar24dev** [comment]
AEM SDK : aem-sdk-2020.8.4119.20200827T010735Z-200730.zip
CIF version: cif-cloud-ready-feature-pkg-2020.9.2-cq-commerce-addon-authorfar
Proxy command: npx local-cors-proxy --proxyUrl https://<magenton-namespace>.adobesandbox.com/ --port 3002 --proxyPartial graphql

**Comment by nikhilkumar24dev** [comment]
@mhaack -
No query doesn't get executed at this end point. It throws below error:
{
  "message": "Unexpected token < in JSON at position 0",
  "stack": "SyntaxError: Unexpected token < in JSON at position 0"
}

**Comment by herzog31** [comment]
The command is wrong. Please use the exact command as documented.

**Comment by nikhilkumar24dev** [comment]
@herzog31 -
Tried exact command but didn't work out 
npx local-cors-proxy --proxyUrl https://<magento-namespace>.adobesandbox.com --port 3002 --proxyPartial ''

As the endpoint authored in Osgi Config is https://<magento-namespace>.adobesandbox.com/graphql.  So, I alsi tried below command:
npx local-cors-proxy --proxyUrl https://<magento-namespace>.adobesandbox.com/grapghql --port 3002 --proxyPartial ''

But with
![image](https://user-images.githubusercontent.com/71063587/93913744-2387b380-fd23-11ea-8225-bb5dc76d03c4.png)

**Comment by herzog31** [comment]
`npx local-cors-proxy --proxyUrl https://.adobesandbox.com --port 3002 --proxyPartial ''` is the correct command.

**Comment by nikhilkumar24dev** [comment]
Am I missing commerce-cif-connector on AEM instance ?
As I am using Acrhtype 24. So that should's be required . Right ?

**Comment by herzog31** [comment]
For Cloud SDK you use the CIF add-on. For AEM 6.5 you use the CIF connector. Don't install both.

**Comment by nikhilkumar24dev** [comment]
@herzog31  - Yep got it. Using SDK with Addon.
I will try to debug more on the proxy server as the mentioned command didn't work.
Let me know if you can replicate the issue.

Thank @herzog31  for the quick responses.

**Comment by herzog31** [comment]
Can you please elaborate why it doesn't work?

**Comment by nikhilkumar24dev** [comment]
It shows it did not return a valid schema.
![image](https://user-images.githubusercontent.com/71063587/93919588-84b38500-fd2b-11ea-82f5-3b5eef77097e.png)

Mentioned command in Docs:
![image](https://user-images.githubusercontent.com/71063587/93919516-706f8800-fd2b-11ea-8fce-f5f5a6380f3d.png)

**Comment by herzog31** [comment]
Please check that http://localhost:3002/graphql is a valid GraphQL endpoint. I need to double check that the command works properly on Windows. 

Additionally the JS console in the developer tools in your browser give you more information on what's wrong with the endpoint. Make sure you enable verbose/debug logs.

**Comment by herzog31** [comment]
@nikhilkumar24dev In Windows PowerShell, the command should be:
```
npx local-cors-proxy --proxyUrl https://.adobesandbox.com --port 3002 --proxyPartial '""'
```
The argument `--proxyPartial` needs to receive an empty string.

**Comment by nikhilkumar24dev** [comment]
npx local-cors-proxy --proxyUrl https://.adobesandbox.com --port 3002 --proxyPartial "" 
This command worked for me and was able to get the same response as magento end point. 
But Product Teaser shows it's incompatible with CIF.
![image](https://user-images.githubusercontent.com/71063587/93990206-79eb0580-fda8-11ea-9b2b-ec22a15f1dda.png)

**Comment by herzog31** [comment]
@nikhilkumar24dev Please provide the JS console (enable verbose/debug) output as requested.

**Comment by nikhilkumar24dev** [comment]
@herzog31 Below are the verbose logs:
![image](https://user-images.githubusercontent.com/71063587/93992585-5b3a3e00-fdab-11ea-9c03-4997860c3277.png)

**Comment by herzog31** [comment]
According to the logs, your Magento instance does not provide a valid version 2.3.5 or 2.4.0 schema. Those are the only versions that are supported at the moment.
Which version of Magento are you using?

**Comment by nikhilkumar24dev** [comment]
v2.3.4

**Comment by herzog31** [comment]
I suggest to upgrade your instance to at least v2.3.5 then.

**Comment by sprince1504** [comment]
Hi @mhaack @herzog31 

I am facing the same issue and I run the command 

npx local-cors-proxy --proxyUrl <magento_endpoint_Url> --port 3002 --proxyPartial '""'

but when I am trying to hit the http://localhost:3002/graphql then it is giving me an error.

![image](https://user-images.githubusercontent.com/10127683/108634599-51268380-74a0-11eb-8820-e8f6b89a352a.png)


Can you please help me here? I am stuck in this issue from last 3 weeks.

Also if you can guide me on, how I can directly call the Magento Endpoint using the servlet and send the graphQL queries to Magento and get the response back.

**Comment by mhaack** [comment]
@sprince1504 this command is just a local reverse proxy. If it does not work likely, it is an issue with you origin Magento GraphQL endpoint. Does that work?

Also with the last CIF Add-On release we removed the need for the local-cors-proxy. It is not needed any more and now build into the CIF Add-On, please have a look at updated instructions (text! video is not updated yet) at: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/commerce/develop.html?lang=en#project

**Comment by sprince1504** [comment]
Hi @mhaack , I am getting error that Graphql can not connect to an endpoint. the same which was mentioned at the top.

Can you please help us, because we are facing this issue for the last 3 weeks and not able to resolve it?

Thanks

**Comment by herzog31** [comment]
@sprince1504 It looks like your configuration is wrong. With the changes @mhaack mentioned, the components should access Magento via `/api/graphql`. Please double check the documentation.

**Comment by sprince1504** [comment]
@herzog31  - Configuration which I have set

![image](https://user-images.githubusercontent.com/10127683/109273386-25a4ef80-7838-11eb-84b7-82e5d52fedf5.png)


![image](https://user-images.githubusercontent.com/10127683/109273514-4ec58000-7838-11eb-8a52-22983702bc22.png)

I changed GraphQL Proxy Path * to /api/graphql -- it is also giving an error.

![image](https://user-images.githubusercontent.com/10127683/109273627-74528980-7838-11eb-8f91-2a42fc93befc.png)

**Comment by herzog31** [comment]
@sprince1504 Please use the default OSGi configurations and configure the endpoint using the `COMMERCE_ENDPOINT` environment variable. There are multiple OSGi configurations that require the endpoint.

**Comment by sprince1504** [comment]
@mhaack @herzog31  above issue is resolved. that was the CORS issue.

but now the issue is I am not able to see products under commerce.html

even if I drag and drop the product components, I don't see the product field.

**Comment by herzog31** [comment]
@sprince1504 Please turn on debug logs in the JS console. They will tell you what's wrong.
