### ISSUE TITLE
Mention limitations of Eclipse m2e with executing "archetype-post-generate.groovy"

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#516]
Eclipse m2e does not support executing archetype's "archetype-post-generate.groovy": https://bugs.eclipse.org/bugs/show_bug.cgi?id=514993.
This should be mentioned in the readme.

**Comment by msagolj** [comment]
Hi @kwin , so workaround would be to switch to your own maven installation here:

![image](https://user-images.githubusercontent.com/37147400/93997890-2a024380-fd94-11ea-99c6-21f19b5d67fd.png)

correct ?

**Comment by kwin** [comment]
No, I am referring to File -> New -> Maven Project. That will aways use the embedded archetype version from m2e (which is 2.x). So the only workaround is to use command line!

**Comment by msagolj** [comment]
Sorry, my mistake, mixed up maven with maven-archetype-plugin :) I added a comment in the README.md (https://github.com/adobe/aem-project-archetype/commit/acf3622c5974d0efab3a4eb3a61fa2c8a8270cac) under the `Known Issues` section. 

@kwin ok like that ?

**Comment by kwin** [comment]
LGTM, thanks
