### ISSUE TITLE
Remove use of deprecated SlingSettingsService in HelloWorldModel.java

### ISSUE THREAD

**Issue by knennigtri** [adobe/aem-project-archetype#528]
`HelloWorldModel.java` creates "Open Issue" the CS CICD pipeline.

### Expected Behaviour
CICD pipeline should not produce any open issues based solely on the archetype since this is considered best practice for AEM projects.

### Actual Behaviour
Code Scanning produces an Open Issue for `HelloWorldModel.java`. It seems like the rules of CICD seem to be updated recently to include deprecated code and HelloWorldModel.java contains deprecated code apparently. https://docs.adobe.com/content/help/en/experience-manager-cloud-manager/using/how-to-use/assets/CodeQuality-rules-latest.xlsx

File Location | Line Number | Issue | Type | Severity | Effort | Rule | Tags | Documentation
-- | -- | -- | -- | -- | -- | -- | -- | --
com.adobe.training:devops.core:src/main/java/com/adobe/training/devops/core/models/HelloWorldModel.java | 45 | Remove this use of "SlingSettingsService"; it is deprecated. | Code Smell | Minor | 15min | squid:CallToDeprecatedMethod | cert,cwe,obsolete | https://www.adobe.com/go/aem_cmcq_calltodeprecatedmeth_en

### Reproduce Scenario (including but not limited to)

- Create a project based on Archetype 23+
- Check your code into Cloud Manager Git
- Rune a CICD pipeline
- Observe the deprecated important issue produced

**Comment by gabrielwalt** [comment]
Agreed, we need to remove the deprecated `SlingSettingsService` in the generated model of the `HelloWorld` component:
https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/core/src/main/java/core/models/HelloWorldModel.java#L45

While at it, also remove the output of which instance is running at [line 63](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/core/src/main/java/core/models/HelloWorldModel.java#L63):
```java
"This is instance: " + settings.getSlingId() + "\n"
```

**Comment by kwin** [comment]
I don't see class `org.apache.sling.settings.SlingSettingsService` being deprecated in either https://github.com/apache/sling-org-apache-sling-settings/blob/ccabdd306892b7c1a2675ce7190a67c546e1ce25/src/main/java/org/apache/sling/settings/SlingSettingsService.java#L36 nor in the latest SDK at https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2020.10.4329.20201007T024940Z-200924/aem-sdk-api-2020.10.4329.20201007T024940Z-200924.jar. To me this rather looks like a false positive. @gabrielwalt Can you explain?

**Comment by vladbailescu** [comment]
@kwin , check https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2020.10.4423.20201028T010735Z-201028/

**Comment by gabrielwalt** [comment]
It's correct that we didn't deprecate the class in Sling as - in the general usage of Sling - this class still makes sense; it does not make sense in AEM as a Cloud Service. Therefore we only deprecate it in the API jar (the `aem-sdk-api` that vlad linked).

**Comment by joerghoh** [comment]
that hopefully gets rid of all these hardcoded "I can only run on author" services" 👍

**Comment by kwin** [comment]
What is the recommended way then to figure out if I am on author or on publish (there are a few edge cases where this is useful)? ACS AEM Commons has a helper relying on that in https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/fe1d698b3012909597490690b4fbcd054a10f4fa/bundle/src/main/java/com/adobe/acs/commons/util/ModeUtil.java#L180.

**Comment by joerghoh** [comment]
Can you explain these edge cases? Under what circumstances isn't it possible to rely on OSGI configuration policy?

**Comment by kwin** [comment]
One edge case is described in https://github.com/adobe/aem-core-wcm-components/pull/1248#issuecomment-723634334. Having a mandatory configuration just on author just to figure out one is on author, feels really awkward and complicated!
