### ISSUE TITLE
dispatcher.ams: Do not enable gzip for author dispatcher by default

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#529]
Enabling GZIP compression generally like in https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_author.vhost#L48 will disable chunked encoding of responses. This defers the delivery of responses which are not cached.

Only response types which are cached should be compressed, which is by default only specific path prefixes: https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/cache/ams_author_cache.any

**Comment by joerghoh** [comment]
I can understand that, but depending on the individual situation of the client a compressed payload might be faster than sending it with chunked encoding, but not compressed.

Do you have some data at hand which can shed some light into that?

**Comment by kwin** [comment]
One example is tree activate: Without chunked encoding the client feels like frozen and I cannot track progress of the individual activated pages.
I would say in general when you access the author the time to first byte is more important (at least for all textual responses like HTML and JSON which can also partially be rendered)

**Comment by joerghoh** [comment]
you are right, did not see the "author" in the headline.
