### ISSUE TITLE
Use nt:unstructured or sling:Folder instead of cq:Page for editable templates

### ISSUE THREAD

**Issue by kwin** [adobe/aem-project-archetype#531]
The nodes at

1. /conf/${appId}/settings/wcm
2. /conf/${appId}/settings/wcm/policies
3. /conf/${appId}/settings/wcm/templates

should be of type `nt:unstructured` instead of `cq:Page` as they don't have the `jcr:content` sub node required for cq:Pages.
Maybe also `sling:Folder` would work.
It is important at least for the folder at location 2. to have a node type which defines a default primary node type (https://docs.adobe.com/docs/en/spec/jcr/2.0/3_Repository_Model.html#3.7.4.2%20Default%20Primary%20Node%20Type) as otherwise the missing ancestor nodes for new policies cannot be created via UI.

**Comment by bpauli** [comment]
According to the node type definition of `cq:Page` the `jcr:content` child node is not mandatory. Also, if we change the node type at location 3. the templates get not shown anymore in the Tools console at `General > Templates`
