### ISSUE TITLE
Support aemanalyser-maven-plugin in the generated projects

### ISSUE THREAD

**Issue by bosschaert** [adobe/aem-project-archetype#533]
The aem-project-archetype should be enhanced to support the aemanalyser-maven-plugin https://github.com/adobe/aemanalyser-maven-plugin/tree/main/aemanalyser-maven-plugin 

This new maven plugin validates the content packages from the current project. It helps find issues with these before the packages are deployed into AEMaaCS, by running additional validation locally as part of the Maven build.

**Comment by bpauli** [comment]
fixed in https://github.com/adobe/aem-project-archetype/commit/2fc68879222ecf1f8c53eff1fa70b6602eec9ee6
