### ISSUE TITLE
Test Maven with JAVA8 Not work fine 

### ISSUE THREAD

**Issue by yelouardi** [adobe/aem-project-archetype#538]
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [io.wcm.testing.mock.aem.junit5.AemContext arg0] in method [void axa.fr.live.core.filters.LoggingFilterTest.doFilter(io.wcm.testing.mock.aem.junit5.AemContext) throws java.io.IOException,javax.servlet.ServletException]: org.apache.sling.testing.resourceresolver.MockResourceResolverFactoryOptions.setMangleNamespacePrefixes(Z)Lorg/apache/sling/testing/resourceresolver/MockResourceResolverFactoryOptions;
Caused by: java.lang.NoSuchMethodError: org.apache.sling.testing.resourceresolver.MockResourceResolverFactoryOptions.setMangleNamespacePrefixes(Z)Lorg/apache/sling/testing/resourceresolver/MockResourceResolverFactoryOptions;

**Comment by msagolj** [comment]
Hi @yelouardi , sorry but its not clear to me what you are referring to. Each commit is tested against Java 8  and 11, on Windows, Ubuntu and MacOS e.g. see here: https://github.com/adobe/aem-project-archetype/actions/runs/341841131

or are you referring to one of the test modules, it.test or ui.tests ?

**Comment by msagolj** [comment]
Closing. If you think this is still an issue please create a new one with more context.
