### ISSUE TITLE
Perform linting on all otherwise unprocessed files

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-project-archetype#545]
### Expected Behaviour
All files, which are expected to have a certain format (e.g. JSON or XML) but which are not processed or validated during the build process already, should be linted, so we can eliminate simple typos, which will either go completely unnoticed or will be identified very late or even after deployment.

### Actual Behaviour
Right now JSON and XML files are not validated at all.

### Suggested changes
Use the xml:validate goal to validate all XML files, for JSON https://github.com/sylvainlaurent/yaml-json-validator-maven-plugin can be used.

**Comment by kwin** [comment]
All Docview XML is validated already with https://jackrabbit.apache.org/filevault/validation.html. Which other XML files do you want to have validated?

**Comment by joerghoh** [comment]
Oh, wasn't aware of that (I just searched for the xml plugin) ....
