### ISSUE TITLE
[AMP] The pages aren't authorable upon AMP Only mode selection

### ISSUE THREAD

**Issue by VarsTheMars** [adobe/aem-project-archetype#554]
The pages in the AMP included project are not authorable in the local instance as the root container drag and drop parsys is not displayed.

The archetype command for the project creation:
```
mvn archetype:generate -DarchetypeGroupId=com.adobe.aem -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=24 -DappTitle="Archetype 24 Test Site AMP" -DappId="archetype24TestSiteAMP" -DgroupId="com.archetype24TestSiteAMP" -DartifactId="archetype-24-test-site-amp" -Damp="y"
```

Here is snapshot of the page rendition:

![amp-error](https://user-images.githubusercontent.com/59619809/99375242-82177b00-28e9-11eb-9f89-f9a6028c635c.PNG)

**Comment by msagolj** [comment]
@VarsTheMars the AMP version of a page is only for view/preview, you can't edit the page in that view. To edit you have to switch back to the normal view.

**Comment by VarsTheMars** [comment]
@msagolj I got it, the AMP mode is designed in a way which limits all the necessary JavaScript libs needed for page authoring.
