### ISSUE TITLE
Improve default logging settings

### ISSUE THREAD

**Issue by joerghoh** [adobe/aem-project-archetype#557]
### Expected Behaviour

* Log entries of custom application should be logged once (by default)
* Log entries of custom application should adhere to the product standard
* By default the custom application should not log on loglevel DEBUG

### Actual Behaviour

A [custom logger](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config~__appId__.cfg.jso) is provided by default, which has some flaws:

* Right now each log entry of the custom application is [logged twice](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config%7E__appId__.cfg.json#L8)
*  The [log pattern](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config%7E__appId__.cfg.json#L2) does not follow the product standard `{0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3} {5}`
* Right now the default is DEBUG. This should be changed to INFO because from experience I know that this settting is rarely changed if logging is not a concern. 

We should leave the configuration in place so it can serve as a basis for changes, but it has to mimic the ootb settings and not have any effect if not explicitly changed.

**Comment by vhochstein** [comment]
Maybe you want to close this issue ?
