### ISSUE TITLE
Edit Template click not working with latest archetype on-premise 

### ISSUE THREAD

**Issue by AmoghDaryapurkar** [adobe/aem-project-archetype#559]
When using the following archetype command the Edit Template option from pageinfo popover menu is not opening the template on click.

mvn -B archetype:generate  -D archetypeGroupId=com.adobe.aem  -D archetypeArtifactId=aem-project-archetype  -D archetypeVersion=24  -D appTitle="AEM Simple"  -D appId="aem-simple"  -D groupId="com.aem" -D aemVersion=6.5.6

#### Platform and Version - AEM 6.5.6 On-Premise

I do not see anything in the logs both on the frontend and backend.

Thanks,
Amogh

**Comment by msagolj** [comment]
Hi @AmoghDaryapurkar created a project and it works for me. I guess the problem lies in `aemVersion=6.5.6` since this version can not be entered yet. Only allowed values are `6.4.8` , `6.5.5` and cloud. Can you please retry with `6.5.5` ?

**Comment by AmoghDaryapurkar** [comment]
@msagolj - Confirmed - It's an issue with AEM SP 6.5.6 and working fine on AEM SP 6.5.5

**Comment by msagolj** [comment]
@AmoghDaryapurkar thx, for confirming. closing issue.
