### ISSUE TITLE
Update readme before archetype release

### ISSUE THREAD

**Issue by paul-bjorkstrand** [adobe/aem-project-archetype#580]
I recommend that the README.md is updated _before_ the archetype is released and tagged. Specifically, I have noticed on the version tags, they still list details for the previous versions in the following sections:

* Usage - lists the previous version and and the previous version's required archetype params. Example: [archetype 24 usage]
* Available Properties - lists the previous version's available values. Example: [archetype 24 available properties] - `aemVersion`
* System Requirements - lists the previous version and the previous version's requirements. Example: [archetype 24 system requirements]

[archetype 24 usage]: https://github.com/adobe/aem-project-archetype/tree/aem-project-archetype-24#usage
[archetype 24 available properties]: https://github.com/adobe/aem-project-archetype/tree/aem-project-archetype-24#available-properties
[archetype 24 system requirements]: https://github.com/adobe/aem-project-archetype/tree/aem-project-archetype-24#system-requirements

**Comment by bpauli** [comment]
For the latest 2 releases we follow the git flow workflow model so the READEM is updated before the release.
