### ISSUE TITLE
Remove too inclusive paths from Archetype

### ISSUE THREAD

**Issue by kaushalmall** [adobe/aem-project-archetype#583]
### Expected Behaviour
The mutable content package filter.xml for the _aemCloud_ version should not include inclusive paths like /content/dam/my-folder, /content/*/my-folder. For more details, please look at internal Adobe ticket CQ-4314525

### Actual Behaviour
The paths like https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.content/src/main/content/META-INF/vault/filter.xml#L4-L6 are getting added

### Reproduce Scenario (including but not limited to)
Create a new project using the aemCloud version

#### Steps to Reproduce
Create a new project using the aemCloud version

#### Platform and Version
aemCloud

#### Sample Code that illustrates the problem
https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.content/src/main/content/META-INF/vault/filter.xml#L4-L6

#### Logs taken while reproducing problem
N/A

**Comment by bpauli** [comment]
Will be part of the next release.
