### ISSUE TITLE
SPA core components 

### ISSUE THREAD

**Issue by niekraaijmakers** [adobe/aem-project-archetype#584]
### Expected Behaviour

The Latest[ React core components /](https://www.npmjs.com/package/@adobe/aem-core-components-react-base) [Angular core components](https://www.npmjs.com/package/@adobe/aem-core-components-angular-base) are hooked into the SPA react / angular modules, to provide a good example to developers on how to use this.

### Actual Behaviour

These are not included.

**Comment by bpauli** [comment]
was added in https://github.com/adobe/aem-project-archetype/commit/a2f477539b2f16d49bbe6eec1663724d3f05bc47
