### ISSUE TITLE
Experience Fragment edit in new tab is broken

### ISSUE THREAD

**Issue by ky940819** [adobe/aem-project-archetype#592]
### Expected Behaviour
When an experience fragment component has been placed on a page, the "edit in new tab" option should open a new tab to edit the content fragment variant.

### Actual Behaviour
Selecting the  "edit in new tab" option results in an error that the experience fragment component has no associated fragment.
Essentially, [this: https://github.com/adobe/aem-core-wcm-components/issues/815](https://github.com/adobe/aem-core-wcm-components/issues/815) issue persists for any project created using the aem-project archetype.

I'm not entirely sure why the `cq:editConfig` needs to be overwritten in every project instead of just inheriting it from the CC. 
The `cq:editConfig` node should either be removed, or updated to match the Core Components project.

#### Platform and Version
AEM 6.5.7.0

**Comment by bpauli** [comment]
@ky940819 Thank you for the hands up. I created #620 to sync the `editConfig` for now. We also have an internal issue to make the override of the editConfig obsolete for a proxy component and this should sonn become part of AEM.
