### ISSUE TITLE
Build is failing due to jest (create-react-app) when using react as the frontend module

### ISSUE THREAD

**Issue by ankur-rajput** [adobe/aem-project-archetype#599]
### Expected Behaviour
Build should complete successfully including the "npm test" goal defined in the frontend-maven-plugin config.

### Actual Behaviour
Build is failing due to npm ERR.

#### Steps to Reproduce
1.) Create project using latest version of archetype 24
2.) Use "react" in the "frontendModule" property
3.) Run "mvn clean install"

#### Platform and Version
OS: Windows 10 Pro
Java: Oracle JDK 11
I think it will be reproducible on any system as it is related to create-react-app's npm configuration.

#### Logs taken while reproducing problem
Getting below error while running "mvn clean install"

` >react-scripts test

● Validation Error:

  Watch plugin jest-watch-typeahead/filename cannot be found. Make sure the watchPlugins configuration option points to an existing node module.

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

npm ERR! Test failed.  See above for more details.
`

**Comment by ankur-rajput** [comment]
There are multiple npm issues (might be in create-react-app) if we use archetype 24 now. Other than the above issue in npm test, there is babel version issue as well.

In the end, I found that the archetype v25 has been release in Jan on mvnrepository and everything is working fine with that. It would be great if you guys can update the README.md file to latest version.

**Comment by bpauli** [comment]
Hi @ankur-rajput, thank you for reporting this issue. Nice to hear that everything is working as expected in v25. I update the readme in https://github.com/adobe/aem-project-archetype/commit/1338f36ce0c1107561eae46267df2208103aad9b
