### ISSUE TITLE
Cannot create a project using archetype 25 on windows

### ISSUE THREAD

**Issue by girishadobe** [adobe/aem-project-archetype#601]
#### Logs taken while reproducing problem

**Comment by girishadobe** [comment]
I am using jdk11 and maven 3.6. I get the following errors
[INFO] Parent element not overwritten in C:\AEMFormsBundles\myforms\ui.apps.structure\pom.xml
[INFO] Executing META-INF/archetype-post-generate.groovy post-generation script
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.513 s
[INFO] Finished at: 2021-02-11T13:34:40-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: Execution default-cli of goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate failed: A required class was missing while executing org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate: org/apache/ivy/core/report/ResolveReport
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-archetype-plugin:3.0.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/gbedekar/.m2/repository/org/apache/maven/plugins/maven-archetype-plugin/3.0.1/maven-archetype-plugin-3.0.1.jar
[ERROR] urls[1] = file:/C:/Users/gbedekar/.m2/repository/org/apache/maven/archetype/archetype-catalog/3.0.1/archetype-catalog-3.0.1.jar
[ERROR] urls[2] = file:/C:/Users/gbedekar/.m2/repository/org/apache/maven/archetype/archetype-descriptor/3.0.1/archetype-descriptor-3.0.1.jar
[ERROR] urls[3] = file:/C:/Users/gbedekar/.m2/repository/org/apache/maven/archetype/archetype-common/3.0.1/archetype-common-3.0.1.jar
[ERROR] urls[4] = file:/C:/Users/gbedekar/.m2/repository/net/sourceforge/jchardet/jchardet/1.0/jchardet-1.0.jar
[ERROR] urls[5] = file:/C:/Users/gbedekar/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar

**Comment by girishadobe** [comment]
The following command used to generate the project
mvn -B archetype:generate   -D archetypeGroupId=com.adobe.aem  -D archetypeArtifactId=aem-project-archetype  -D archetypeVersion=25  -D appTitle="My Forms"  -D appId="myforms"  -D groupId="com.aem.guides.myforms"  -D includeForms="y"

**Comment by msagolj** [comment]
Hi @girishadobe , This looks like the same issue as #512. I was able to run above command on Windows with JDK11 , it generated the project and I was able to build the generated project. Closing. Please reopen if you you think your issue is different from #512..

**Comment by girishadobe** [comment]
I am still getting the error. I am attaching the error log
[abc.log](https://github.com/adobe/aem-project-archetype/files/5991310/abc.log)

**Comment by girishadobe** [comment]
Can you please re-open this issue. I am still not able to generate the project using archetype 24 or 25 on windows with JDK 11.0.6, Maven 3.6.0

**Comment by girishadobe** [comment]
its working now. Thanks

**Comment by msagolj** [comment]
Hi @girishadobe , glad to hear it works now and thank you for providing the solution as this might help others that might have the same issue.
