### ISSUE TITLE
apis classifier exists no more with AEM >= 6.5.6

### ISSUE THREAD

**Issue by jpmat296** [adobe/aem-project-archetype#607]
Here is a sample of the issue:
https://github.com/adobe/aem-project-archetype/blob/98f3b4efa9834437881b31a336459abe6a89ad00/src/main/archetype/ui.content/pom.xml#L105

The change in classifiers is documented here:
https://github.com/AdobeDocs/experience-manager-65.en/blob/cb531bfc009fc766bab20d28cf332856b1e95c7b/help/sites-developing/ht-projects-maven.md#which-uberjar-to-use-which-uberjar-to-use

I did not find documentation from Adobe to confirm.

**Comment by diogopedreira** [comment]
I guess they made it official in their 6.5.7 release notes - https://experienceleague.adobe.com/docs/experience-manager-65/release-notes/service-pack/sp-release-notes.html?lang=en#uber-jar

![image](https://user-images.githubusercontent.com/3101820/109975008-0f90a680-7cf2-11eb-93a5-4daa75abb14d.png)
