### ISSUE TITLE
core bundle for archetype25 does not start when installed on v6.5.0[bug]

### ISSUE THREAD

**Issue by jaydubb12** [adobe/aem-project-archetype#608]
###Issue
When package for Archetype 25 is installed on a clean version of 6.5.0 the core bundle does not start. 

###Error Message
Core bundle not starting
org.apache.sling.api.resource,version=[2.12,3) -- Cannot be resolvedorg.apache.sling.api.servlets,version=[2.3,3) -- Cannot be resolved

com.day.cq.wcm.api,version=[1.29,2) -- Cannot be resolved

### Expected Behaviour
* Documentation would call out minimum version dependencies OR....Bundles would start when installed OOTB 

### Actual Behaviour
* Bundles do not start

#### Steps to Reproduce
1. Create a project using the properties referenced in the attachment
2. Run the command mvn install -DskipTests -PautoInstallSinglePackage 
3. Observe bundle in the Felix Console, as it will be in the "installed" status vs "started"
[archetype.properties.txt](https://github.com/adobe/aem-project-archetype/files/6001592/archetype.properties.txt)

#### Platform and Version
6.5.0

**Comment by kwin** [comment]
Look at https://github.com/adobe/aem-project-archetype#system-requirements.

You need 6.5.5 or newer with archetype 25.

**Comment by jaydubb12** [comment]
@kwin ah...major face-palm on that one!  That is 100% a miss on my end. Apologies for the trouble. Closing ticket
