### ISSUE TITLE
SPA Core Bundle Does not Start - Archetype25 [bug]

### ISSUE THREAD

**Issue by jaydubb12** [adobe/aem-project-archetype#610]
### Issue
When a new site / project is generated using the properties in the attachment for Archetype25, the SPA Core bundle does not start due to an issue with a minimum version requirement not being met

### Additional Info
Tracked the issue back to the SPA Core Project itself, whereas it is leveraging v2.11.1 of the core components. Given this issue is likely needing to be resolved via the SPA Core project I have logged the following ticket, but wanted to log this ticket herein as this is technically an issue with the Archetype25 dependencies

### Related Ticket
https://github.com/adobe/aem-spa-project-core/issues/27
[archetype.properties.txt](https://github.com/adobe/aem-project-archetype/files/6001685/archetype.properties.txt)

### Expected Behaviour
Generated dependencies for the Archetype would build without error and start once installed

### Actual Behaviour
com.adobe.aem:spa.project.core.core:1.2.0 does not start.  message displayed is - com.adobe.cq.wcm.core.components.models,version=[12.15,13) -- Cannot be resolved

### Reproduce Scenario (including but not limited to)
Generate project using attached Archetype25 properties

#### Platform and Version
6.5.0
6.5.7

**Comment by bpauli** [comment]
As pointed out in https://github.com/adobe/aem-spa-project-core/issues/27 please use `aemVersion=6.5.7` while generating the project.
