### ISSUE TITLE
Remove unnecessary / duplicate htl dependency

### ISSUE THREAD

**Issue by jaydubb12** [adobe/aem-project-archetype#614]
### Request
Streamline the dependency management process for the htl validation of the ui.apps module by removing the dependency on line 147

```
  <!-- HTL dependencies needed for the HTL Maven Plugin source code generation -->
  <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.scripting.sightly.compiler</artifactId>
      <version>1.2.4-1.4.0</version>
      <scope>provided</scope>
  </dependency>

```

### Additional Info
Based on the [documentation for the plugin,](https://sling.apache.org/components/htl-maven-plugin/usage.html) as of v1.2.2 of the htl-maven-plugin only 1 dependency is needed
![Screen Shot 2021-02-18 at 5 10 48 AM](https://user-images.githubusercontent.com/21325640/108341567-c7c53780-71a7-11eb-9e10-102948a7958d.png)

```
<!-- HTL dependencies needed for the HTL Maven Plugin source code generation -->
<dependency>
    <groupId>org.apache.sling</groupId>
    <artifactId>org.apache.sling.scripting.sightly.runtime</artifactId>
    <version>1.2.0-1.4.0</version>
    <scope>provided</scope>
</dependency>
```

### Expected Behaviour
* Archetype dependencies would be optimized / tuned to meet the requirements of the versions which are set

### Actual Behaviour
* A legacy dependency has been retained, and can be removed

### Reproduce Scenario (including but not limited to)
* Generate a project using Archetype25

**Comment by bpauli** [comment]
@jaydubb12 Thank you for the hands up. Please have a look to the PR at #625 which removes the obsolete dependency.
