### ISSUE TITLE
maven-assembly-plugin fails the build for module it.tests- Archetype25 on MacOS

### ISSUE THREAD

**Issue by jaydubb12** [adobe/aem-project-archetype#615]
### Issue
When building the OOTB Archetype 25 project, the build fails and the maven console references an issue with the maven-assembly-plugin, which ties back to a potential issue with the MacOS when the value for <tarLongFileMode> = gnu

### Version
macOS Big Sur 11.2.1

### Reference Doc
[Controlling the Archive Format](https://www.gnu.org/software/tar/manual/html_chapter/tar_8.html)

### Remediation in local env
Modified the configuration to leverage posix vs gnu

```<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>${project.basedir}/assembly-ui-test-docker-context.xml</descriptor>
                    </descriptors>
                    <tarLongFileMode>posix</tarLongFileMode>
```

### Excerpt from Stack Exchange on this issue
The answer to this issue turned out to be that the User's GroupID number on that one mac exceeded the 2097151 size specified for the library-code when in standard mode. The OSX GroupIDs differ depending on the MacBook generations. The reason that "posix" can solve the underlying issue, is that the POSIX mode has a larger variable-size to hold the GroupID internally, and the newer MacBooks then don't fail trying to put a big number in it. So it had nothing to do with the Maven-Assembly's functionality at all, but with the underlying library's code-base. Specifying the POSIX mode is a work-around, not a requirement, but could be considered as a potentially valid 'recommended' for all POM use-cases since it would prevent niche-machines failing the build-phase.

### Expected Behaviour
OOTB build process would execute without error

### Actual Behaviour
Build process fails due to the maven-assembly-plugin failure regardless of whether system is built on Windows or MacOS

**Comment by bpauli** [comment]
@jaydubb12 Thank you for reporting this bug. I created #624 which contains a default configuration of the plugin with the `posix` property.
