### ISSUE TITLE
Redundant deployment of packages due to content-package-maven-plugin

### ISSUE THREAD

**Issue by B3r** [adobe/aem-project-archetype#616]
### Expected Behaviour
Archetype should deploy the "all" package only

### Actual Behaviour
Each package which has the content-package-maven-plugin as a build step will be deployed to the instance redundantly before the "all" package

### Reproduce Scenario (including but not limited to)
1. Shut down your AEM instance
2. Execute a `mvn clean install -PautoInstallPackage` on the main project
3. It will fail on com.mysite:mysite.ui.apps:content-package while connecting to an aem instance.
However it should not fail here, it should fail in the "all" package

#### Platform and Version
Windows, Archetype 25, Maven 3.6.3

#### Sample Code that illustrates the problem
![image](https://user-images.githubusercontent.com/5477168/108854053-b638c100-75e7-11eb-9bda-d4f332e07c87.png)

#### Logs taken while reproducing problem
`Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:1.0.2:install (install-package) on project mysite.ui.apps: Connection refused: connect`

**Comment by vladbailescu** [comment]
@B3r , as described in https://github.com/adobe/aem-project-archetype/tree/master/src/main/archetype#how-to-build, the archetype will setup two profiles for deploying packages:
* `autoInstallPackage` - for **individual** package deployment, skips installing `all`
* `autoInstallSinglePackage` - for **container** (`all`) package deployment

**Comment by B3r** [comment]
I am sorry, should have read the manual completely 😕
