### ISSUE TITLE
Replace/Fork `webpack-import-glob-loader` in package.json

### ISSUE THREAD

**Issue by soluml** [adobe/aem-project-archetype#630]
## Problem
The dependency [`webpack-import-glob-loader`](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.frontend.general/package.json#L52) has been left untouched for 2 years after being forked [from a project](https://github.com/terpiljenya/import-glob) which was been untouched for 4 years. It still works fine for most cases but I've run across a couple of issues:

1. It does not support the new Sass at-rules [@use](https://sass-lang.com/documentation/at-rules/use) and [@forward](https://sass-lang.com/documentation/at-rules/forward). Granted, the plugin is called webpack-_import_-glob-loader, however, the [@import directive has been deprecated](https://sass-lang.com/documentation/at-rules/import) by the Sass team.
2. Webpack's resolver configuration (like aliasing) doesn't work with the plugin.

## Solution
As I couldn't get movement on the `webpack-import-glob-loader` repo I created my own tool [glob-import-loader](https://www.npmjs.com/package/glob-import-loader). It's been copied from the original repo and retooled to support both aliasing and the new Sass rules. I've been using this for my company's AEM work.

I propose that either the archetype adopt an alternative like glob-import-loader or fork the project and make the necessary updates to ensure compatibility with future versions of Sass.

**Comment by bpauli** [comment]
@soluml May I ask you to create a PR with this enhancement. Thank you!

**Comment by soluml** [comment]
@bpauli - Done: #653 

I only PR'd into `develop`, I assume that's fine.

**Comment by bpauli** [comment]
Thanks @soluml! Merged and will be part of the next release.
