### ISSUE TITLE
ui.apps.structure doesn't have a CloudManager by-pass definied

### ISSUE THREAD

**Issue by tomaszsoczyk-cognifide** [adobe/aem-project-archetype#635]
### Expected Behaviour
As per documentation: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/repository-structure-package.html?lang=en#creating-the-repository-structure-package the ui.apps.structure should have 
`                <properties>
                    
                    <cloudManagerTarget>none</cloudManagerTarget>
                </properties>
                `
### Actual Behaviour
In current version of the archetype deploying structure package to CloudManager is not disabled:
https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.apps.structure/pom.xml

Any ideas what's going on in here? Are the docs wrong or is the archetype wrong?

**Comment by bpauli** [comment]
Will be fixed in the next release.
