### ISSUE TITLE
Build fail for /core with default value of Archetype(#25) property -  'includeCommerce=n'

### ISSUE THREAD

**Issue by dspathak21** [adobe/aem-project-archetype#636]
### Issue
Maven build failed on the project created with Archetype#25, using the default property value (includeCommerce=n)

### Observation
- It seems some of the commerce classes are getting created  if we are not mentioning 'includeCommerce' property in archetype#25 scaffolding command (same result if we give 'includeCommerce=n' explicitly).
- In Absence of commerce CIF dependency the build got failed for 'core' module.

### Expected Behaviour
- The OOTB project generated by the maven Archetype25 should build without error

### Actual Behaviour
- Build for 'core' module got failed

#### Steps to Reproduce
-  Generate a new project using Archetype25 and the properties referenced herein
- [archetype#25.txt](https://github.com/adobe/aem-project-archetype/files/6121095/archetype.25.txt)

#### Platform and Version
- Windows 10
- Apache Maven 3.6.3
- java version "11.0.9" 2020-10-20 LTS
- Archetype 25

#### Logs taken while reproducing problem
- ![buid_error](https://user-images.githubusercontent.com/45150349/110752175-e8465600-826a-11eb-8e2d-7a701e51cc19.png)

#### Note
The build works fine with property - 'includeCommerce=y' in Archetype 25

**Comment by bpauli** [comment]
@dspathak21 This java files shouldn't exist when the parameter `includeComer=n` is set. There is a groovy (archetype-post-generate.groovy) which gets executed during the project creation. As you can see in https://github.com/adobe/aem-project-archetype/blob/aem-project-archetype-25/src/main/resources/META-INF/archetype-post-generate.groovy#L120 the directory is deleted. Can you please create a project again with the same parameter and check if the groovy script gets executed? If not , maybe you can post the whole console output here? Thanks!
