### ISSUE TITLE
Dispatcher immutable config files are out-of-sync with Dispatcher SDK counterpart files

### ISSUE THREAD

**Issue by krystiannowak** [adobe/aem-project-archetype#668]
### Expected Behaviour
Diff calculated between immutable dispatcher config files in [AEM as a Cloud Service SDK](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-as-a-cloud-service-sdk.html) and the ones generated by archetype is empty.

### Actual Behaviour
There are differences in immutable dispatcher config files in [AEM as a Cloud Service SDK](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-as-a-cloud-service-sdk.html) vs archetype.

### Reproduce Scenario (including but not limited to)
Run [validate.sh script in Dispatcher SDK](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/content-delivery/disp-overview.html?lang=en#local-validation) against archetype-generated dispatcher configs - immutable files comparison fails.

#### Steps to Reproduce
* download [AEM as a Cloud Service SDK](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-as-a-cloud-service-sdk.html)
* copy archetype-generated dispatcher configs for cloud
* run [validate.sh script from Dispatcher SDK](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/content-delivery/disp-overview.html?lang=en#local-validation)

#### Platform and Version
* [Dispatcher SDK 2.0.45](https://experience.adobe.com/#/downloads/content/software-distribution/en/aemcloud.html)
* archetype v. 27

#### Sample Code that illustrates the problem
```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=27 \
 -D appTitle="Dispatcher config immutability check" \
 -D appId="dispatcher-config-immutability" \
 -D groupId="com.adobe.aem" \
 -D aemVersion=cloud
```

#### Logs taken while reproducing problem
```
$ bin/validate.sh archetype/dispatcher-config-immutability/dispatcher/src
Phase 1: Dispatcher validator
Cloud manager validator 2.0.26
2021/03/30 14:18:55 No issues found
Phase 1 finished
Phase 2: httpd -t validation in docker image
(...)
Syntax OK
Phase 2 finished
Phase 3: Immutability check
reading immutable file list from /etc/httpd/immutable.files.txt
(...)
** error: immutable file 'conf.d/available_vhosts/default.vhost' has been changed!
```

**Comment by jwadolowski** [comment]
I'm glad it is being addressed here 👍  

FYI, I reported the same issue back in February via Adobe's support portal: E-000324810
