### ISSUE TITLE
Failure to deploy, no Analyse artifact

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-project-archetype#679]
### Expected Behaviour

When using the Analyse module as recommend part of an AEM project a user should be able to deploy and release artifacts to a repository.

### Actual Behaviour

The Analyse module does not generate any artifacts, therefore when performing a Maven release errors like below can occur.

```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project aem-guides-wknd.analyse: The project artifact has not been assembled yet. Please do not invoke this goal before the lifecycle phase "package". -> [Help 1]
```

Similar modules like `ui.frontend`, `dispatcher`, `ui.tests` generate artifacts and thus do not have the same issue. 

Potential fixes:

1. add an `assembly.xml` file to the `analyse` module similar to the `dispatcher` module to generate an artifact containing the output of the analyse process.
2. Or modify the generated project so that the `analyse` module is skipped when a release is performed...

**Comment by godanny86** [comment]
@bosschaert I know you have been working closely with the analyse module...

**Comment by kwin** [comment]
I think executing the aemanalyzer-maven-plugin inside the 'all' module is much more in line with Maven. That way you have one main artifact to deploy per module and less overhead. This would also solve the issue with the maven-gpg-plugin

**Comment by godanny86** [comment]
@kwin yes that makes sense to me. @bosschaert wdyt? Might be a change we make to the archetype? The Analyse module would still get run each time, but no module is needed and no need to generate an artifact

**Comment by bosschaert** [comment]
Sorry for the late reply, @godanny86 I was on PTO. Yes what you and @kwin are suggesting makes sense. I see that the PR is already merged, is this issue still open?

**Comment by godanny86** [comment]
@bosschaert welcome back! Yes I created the pr in `aem-guides-wknd` to un-block some activities. Ideally we keep `aem-guides-wknd` and the `project-archetype` in sync. If you like the approach used in https://github.com/adobe/aem-guides-wknd/pull/230 I can raise a PR to this repo...

**Comment by bosschaert** [comment]
Hi @godanny86 yes that sounds good to me.

**Comment by krystiannowak** [comment]
Closing this one as per consultation with @bosschaert and @cziegeler
