### ISSUE TITLE
Root pages for a new site should use Core Component Page instead of foundation/components/redirect

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-project-archetype#690]
### Expected Behaviour

The Project Archetype should stop using Foundation components - and use Core Components instead. The Page Core Components supports redirect.

https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.content/src/main/content/jcr_root/content/__appId__/.content.xml
https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.content/src/main/content/jcr_root/content/__appId__/us/.content.xml

Is using foundation/components/redirect - and should use ${appId}/components/page

This will also enable the use of the PWA feature for sites build with the Project Archetype.

**Comment by gabrielwalt** [comment]
We have an identical issue for the Site Template:
https://github.com/adobe/aem-site-template-basic/issues/38.
