### ISSUE TITLE
Archetype 28 - Code Smell

### ISSUE THREAD

**Issue by pekdemira** [adobe/aem-project-archetype#772]
### Expected Behaviour
There should be no code smell when using Archetype 28 OOTB components. They should reflect the recommended best practices out of the box without getting flagged by the code quality tools of the cloud platform.

### Actual Behaviour
Some of the (Archetype 28) OOTB components fail at code quality tools. Reporting that the components listed below extend the legacy foundation component `wcm/foundation/components/parsys/newpar`.

#### Platform and Version
AEM as Cloud Service / Archetype 28

Code smell for the following components as they extend the legacy foundation component `wcm/foundation

/apps/xxx/components/container/new
/apps/xxx/components/accordion/new
/apps/xxx/components/tabs/new
/apps/xxx/components/carousel/new

**Comment by niekraaijmakers** [comment]
Problem is that we need these for the SPA editor container components (accordion,carousel,tabs) to work. We'll have to figure out a solution here

**Comment by pekdemira** [comment]
Thanks for sharing that context Niek, I might take a look at this if I can get back to this sooner.
