### ISSUE TITLE
LogManager OSGI configs incompatible with latest cloud SDK

### ISSUE THREAD

**Issue by niekraaijmakers** [adobe/aem-project-archetype#787]
### Expected Behaviour
When opting for aemversion "cloud", LogManager osgi config files are generated, that subsequently will not produce any errors building with the latest SDK.

### Actual Behaviour
When opting for aemversion "cloud", LogManager osgi config files are generated, that subsequently do  produce errors building with the latest SDK.

**Comment by cziegeler** [comment]
@niekraaijmakers Isn't this solved?
