### ISSUE TITLE
Using aem cloud sdk keep downloading maven dependencies every few days

### ISSUE THREAD

**Issue by pawee-del** [adobe/aem-project-archetype#845]
### Expected Behaviour
once dependencies are downloaded it should not download again
### Actual Behaviour
maven dependencies are redownloaded again
#### Steps to Reproduce
use latest cloud sdk and build with wknd project, use vs code
#### Logs taken while reproducing problem

**Comment by cziegeler** [comment]
This has been fixed with archetype 33
