### ISSUE TITLE
Issues executing UI Tests on v33+ 

### ISSUE THREAD

**Issue by marcovlara** [adobe/aem-project-archetype#891]
One of my clients faces issues when running ui.test locally on a vanilla project created by the latest archetype (v35). They follow the ui.test documentation[0](https://github.com/adobe/aem-project-archetype/tree/develop/src/main/archetype/ui.tests), and execute mvn verify -Pui-tests-local-execution . I was able to validate the test execution failures on the latest version. Furthermore, I also was able to validate that the tests failed for a few previous versions, newer than v32. v32 and older seem fine to execute the test locally. 

[0] https://github.com/adobe/aem-project-archetype/tree/develop/src/main/archetype/ui.tests

I am attaching the execution output files on both projects created using archetypes 32, and 35.

Perhaps there are changes in the versions of node or maven, but those should be part of the documentation.

### Expected Behaviour
Archetype on all versions should execute successful UI Tests 

### Actual Behaviour
UI Test execution failures on archetype versions 33+.

#### Steps to Reproduce
Execute the commands under "Sample Code that illustrates the problem"

#### Platform and Version
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1715.60.5.0.0 (iBridge: 19.16.10647.0.0,0)
  OS Loader Version:	540.60.2~89
  Activation Lock Status:	Disabled

##### Failed Project 
```
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=35\
 -D appTitle="SampleUiTest35" \
 -D appId="sampleuitest35" \
 -D groupId="com.sampleuitest35"
...
cd ./sampleuitest35
mvn clean install -PautoInstallSinglePackage
...
mvn verify -Pui-tests-local-execution
```

##### Pass Project 
```
mvn -B archetype:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=32 \
 -D appTitle="SampleUiTest32" \
 -D appId="sampleuitest32" \
 -D groupId="com.sampleuitest32"
...
cd ./sampleuitest32
mvn clean install -PautoInstallSinglePackage
...
mvn verify -Pui-tests-local-execution
```

#### Logs taken while reproducing problem
[sampleuitest35.txt](https://github.com/adobe/aem-project-archetype/files/8050882/sampleuitest35.txt)
[sampleuitest32.txt](https://github.com/adobe/aem-project-archetype/files/8050883/sampleuitest32.txt)
[2022-02-11T18_10_37_216Z-debug.35.log](https://github.com/adobe/aem-project-archetype/files/8050885/2022-02-11T18_10_37_216Z-debug.35.log)

**Comment by stefanseifert** [comment]
i'm running into the same problem - PR https://github.com/adobe/aem-project-archetype/pull/905 fixes it.
