### ISSUE TITLE
Adding support for AEM Dispatcher Tools 2.0.91 and latest dispatcher configuration

### ISSUE THREAD

**Issue by patrickheinzelmann** [adobe/aem-project-archetype#917]
The latest AEM SDK used the AEM Dispatcher Tools 2.0.91, which has three updated immutable files for dispatcher configuration.

src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf
src/main/archetype/dispatcher.cloud/src/conf.d/available_vhosts/default.vhost
src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/filters/default_filters.any

### Expected Behaviour

Generate a new AEM project using the current version of the archetype

````
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=36\
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite"
````

Copy the folder bin of the AEM Dispatcher Tools 2.0.91 into the folder dispatcher of the generated project and run following command:

````
./bin/docker_immutability_check.sh src
`````

The check should be successful.

### Actual Behaviour

The check fails with following error message.

````
checking 'conf.d/available_vhosts/default.vhost' immutability (if present)
checking existing 'conf.d/available_vhosts/default.vhost' for changes
immutable file 'conf.d/available_vhosts/default.vhost' has been changed:
--- /etc/httpd/conf.d/available_vhosts/default.vhost
+++ /etc/httpd-actual/conf.d/available_vhosts/default.vhost
@@ -1,5 +1,5 @@
 #
-# This is the default publish virtualhost definition for Apache. 
+# This is the default publish virtualhost definition for Apache.
 #
 # DO NOT EDIT this file, your changes will have no impact on your deployment.
 #
@@ -23,7 +23,7 @@
 	<IfModule mod_headers.c>
 		Header add X-Vhost "publish"
 	</IfModule>
-	<Directory />
+	<Directory "${DOCROOT}">
 		<IfModule disp_apache2.c>
 			# Some items cache with the wrong mime type
 			# Use this option to use the name to auto-detect mime types when cached improperly
@@ -37,16 +37,13 @@
 		</IfModule>
 		Options FollowSymLinks
 		AllowOverride None
+		Require all granted
 		# Insert filter
 		SetOutputFilter DEFLATE
 		# Don't compress images
 		SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|png)$ no-gzip dont-vary
 		# Prevent clickjacking
 		Header always append X-Frame-Options SAMEORIGIN
-	</Directory>
-	<Directory "${DOCROOT}">
-		AllowOverride None
-		Require all granted
 	</Directory>
 	<IfModule disp_apache2.c>
 		# Enabled to allow rewrites to take affect and not be ignored by the dispatcher module
** error: immutable file 'conf.d/available_vhosts/default.vhost' has been changed!
````

**Comment by godanny86** [comment]
@krystiannowak, @patrickheinzelmann doesn't the immutable file list at dispatcher/pom.xml also need to be updated?

**Comment by patrickheinzelmann** [comment]
@godanny86 The dispatcher/pom.xml will be generated during the creating based on one of the templates dispatcher.ams or dispatcher.cloud. The hash values of the immutable file will be calculated based on the files include into the archetype.

https://github.com/adobe/aem-project-archetype/blob/c85f75f2c05fba6b0327468497e99bbb0e475e06/src/main/archetype/dispatcher.cloud/pom.xml#L53

The AEM Dispatcher Tools can export the included immutable files via `$ ./bin/docker_immutability_check.sh src extract` , but it isn't generating any hash values. The AEM Dispatcher Tools doesn't know anything about Apache Maven.

If you upgrade to a new version of the AEM Dispatcher Tools which contains the new set of immutable files, you have to update the hash values manually. I simply generated a new project based on the updated archetype and copy and pasted the hash values into the  pom.xml of the existing project. 

The archetype isn't using the AEM Dispatcher Tools, both are only loosely coupled via the files included into the folder dispatcher.cloud.

**Comment by krystiannowak** [comment]
@godanny86 As @patrickheinzelmann wrote it is generated by [archetype-pre-package.groovy](https://github.com/adobe/aem-project-archetype/blob/c85f75f2c05fba6b0327468497e99bbb0e475e06/src/main/resources/META-INF/archetype-pre-package.groovy)

See also https://github.com/adobe/aem-guides-wknd/pull/339 by @froesef as an example.

**Comment by godanny86** [comment]
Thank @krystiannowak and @patrickheinzelmann ! I was actually trying to update the wknd project to be compatible with the latest dispatcher files and @froesef took care of it!
