### ISSUE TITLE
Archetype-38 gives BUILD FAILURE error

### ISSUE THREAD

**Issue by SachinMali** [adobe/aem-project-archetype#992]
### Expected Behaviour

When using the 'Archetype-38 ' command from README (or by making project-specific tweaks) it should create AEM project successfully.

### Actual Behaviour

Below error message is reported

$mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=38\
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.2.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.2.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.2.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [com.adobe.aem:aem-project-archetype:37] found in catalog remote
[WARNING] The POM for com.adobe.aem:aem-project-archetype:jar:38 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.013 s
[INFO] Finished at: 2022-09-22T09:30:39-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.adobe.aem:aem-project-archetype:38) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

#### Steps to Reproduce
- Copy the README.md command and run in your shell..
- You should see the error message

#### Logs taken while reproducing problem

**Comment by davidjgonzalez** [comment]
Experiencing the same.

Did we skip 38 and go straight to 39?

https://search.maven.org/artifact/com.adobe.aem/aem-project-archetype

Thought, 39 also fails ...

```
 tmp mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
 -D archetypeGroupId=com.adobe.aem \
 -D archetypeArtifactId=aem-project-archetype \
 -D archetypeVersion=39\
 -D appTitle="My Site" \
 -D appId="mysite" \
 -D groupId="com.mysite"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.2.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.2.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.2.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [com.adobe.aem:aem-project-archetype:37] found in catalog remote
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/adobe/aem/aem-project-archetype/39/aem-project-archetype-39.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/adobe/aem/aem-project-archetype/39/aem-project-archetype-39.pom (9.7 kB at 69 kB/s)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/adobe/aem/aem-project-archetype/39/aem-project-archetype-39.jar
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/adobe/aem/aem-project-archetype/39/aem-project-archetype-39.jar (29 MB at 11 MB/s)
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: aem-project-archetype:39
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.mysite
[INFO] Parameter: artifactId, Value: mysite
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: package, Value: com.mysite
[INFO] Parameter: packageInPathFormat, Value: com/mysite
[INFO] Parameter: includeForms, Value: n
[INFO] Parameter: includeFormsenrollment, Value: n
[INFO] Parameter: country, Value: us
[INFO] Parameter: amp, Value: n
[INFO] Parameter: groupId, Value: com.mysite
[INFO] Parameter: enableDynamicMedia, Value: n
[INFO] Parameter: language, Value: en
[INFO] Parameter: appTitle, Value: My Site
[INFO] Parameter: enableSSR, Value: n
[INFO] Parameter: appId, Value: mysite
[INFO] Parameter: artifactId, Value: mysite
[INFO] Parameter: includeFormscommunications, Value: n
[INFO] Parameter: singleCountry, Value: y
[INFO] Parameter: includeErrorHandler, Value: n
[INFO] Parameter: datalayer, Value: y
[INFO] Parameter: precompiledScripts, Value: n
[INFO] Parameter: includeDispatcherConfig, Value: y
[INFO] Parameter: sdkFormsVersion, Value: latest
[INFO] Parameter: package, Value: com.mysite
[INFO] Parameter: includeExamples, Value: n
[INFO] Parameter: commerceEndpoint, Value: https://hostname.com/graphql
[INFO] Parameter: includeFormsheadless, Value: n
[INFO] Parameter: version, Value: 1.0.0-SNAPSHOT
[INFO] Parameter: aemVersion, Value: cloud
[INFO] Parameter: includeCommerce, Value: n
[INFO] Parameter: frontendModule, Value: general
[INFO] Parameter: sdkVersion, Value: latest
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.662 s
[INFO] Finished at: 2022-09-22T09:43:15-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: A Maven project already exists in the directory /Users/davidg/tmp/mysite -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by kevinolivar** [comment]
@davidjgonzalez it states `A Maven project already exists in the directory /Users/davidg/tmp/mysite`, maybe delete and redo?

**Comment by vladbailescu** [comment]
@davidjgonzalez , we skipped release 38 due to errors with release automation. @kevinolivar is right, removing the existing project should allow you to create a new one.
